### PR TITLE
neurodamus-core: update to 2.10.1 in bbp-packages

### PR DESCRIPTION
**Pull request by jorblancoa**

### CODE REVIEW

**Review by pramodk — DISMISSED** [review]

**Review by matz-e — DISMISSED** [review]

**Review by pramodk — DISMISSED** [review]

**Comment by jorblancoa** [comment]
retest this please jenkins

**Review by matz-e — DISMISSED** [review]

**Comment by jorblancoa** [comment]
retest this jenkins please

**Comment by jorblancoa** [comment]
retest this please jenkins

**Comment by pramodk** [comment]
@jorblancoa : Is this updating module or still have the same issue?

**Review by pramodk — DISMISSED** [review]

**Review by pramodk — DISMISSED** [review]

**Review by pramodk — APPROVED** [review]

**Pull request merged**
