### PR TITLE
bbp-workflow: new package

### PR DESCRIPTION
**Pull request by matz-e**
Closes #881.

### CODE REVIEW

**Comment by matz-e** [comment]
Retest this please

**Comment by matz-e** [comment]
Retest this please

**Comment by genric** [comment]
Any luck with this?

**Comment by matz-e** [comment]
Jenkins finished building, we just got a bunch of distracting tests that I'm still testing.

```
unset MODULEPATH
. /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/pulls/1001/config/modules.sh
```
should give you access to test modules…

I'll rotate back to this on my own once I've fixed the tests, feel free to test in the meantime. I tried to take all essential commits from your branch, skipping over most of the upstream updates and zeromq stuff.

**Comment by genric** [comment]
Great, thanks for the update!

**Comment by matz-e** [comment]
Retest this please

**Review by genric — APPROVED** [review]

**Comment by genric** [comment]
I'll bump the versions in another PR. Are we good to merge it?

**Comment by matz-e** [comment]
Yes, I can merge this if you're "happy"

**Comment by genric** [comment]
Yes, very happy :)

**Comment by matz-e** [comment]
Great! Sorry this took a while!

**Comment by pramodk** [comment]
too much happiness around! 🇨🇽 🎄 🎅 🎁

**Pull request merged**
