### PR TITLE
py-sonata-network-reduction 0.1.8

### PR DESCRIPTION
**Pull request by asanin-epfl**

### CODE REVIEW

**Review by matz-e — APPROVED** [review]

**Comment by asanin-epfl** [comment]
retest this please

**Comment by asanin-epfl** [comment]
retest this please

**Comment by asanin-epfl** [comment]
CI fails repeatedly on the test:

```
lib/spack/spack/test/cmd/list.py::test_list_format_version_json FAILED
```

What should I do here?

**Comment by matz-e** [comment]
> CI fails repeatedly on the test:
> 
> ```
> lib/spack/spack/test/cmd/list.py::test_list_format_version_json FAILED
> ```
> 
> What should I do here?

Seems weird, this doesn't normally happen

**Comment by asanin-epfl** [comment]
Thank you!

**Pull request merged**
