### PR TITLE
Deploy py-neurodamus 2.3.1

### PR DESCRIPTION
**Pull request by WeinaJi**

### CODE REVIEW

**Comment by WeinaJi** [comment]
please retest

**Review by iomaganaris — APPROVED** [review]

**Review by ferdonline — APPROVED** [review]

**Comment by matz-e** [comment]
Why the close/re-open?

**Comment by iomaganaris** [comment]
> Why the close/re-open?

There was an update in the `py-neurodamus` tag and I wanted to rerun the deplyoment CI + module testing. Sorry for the noise :slightly_smiling_face:

**Comment by matz-e** [comment]
> > Why the close/re-open?
> 
> There was an update in the `py-neurodamus` tag and I wanted to rerun the deplyoment CI + module testing. Sorry for the noise slightly_smiling_face

Just wanting to make sure that this does what you think it does? I would check if anything is actually getting rebuilt, since the hash of the git commit does not make it into the DAG hashes (updated tag = changed commit id?). Would be safer to delete the PR directory for a clean slate, then a simple "Retest this please"… or did you monitor that the directory got deleted by one of the other plans?

**Comment by iomaganaris** [comment]
> Just wanting to make sure that this does what you think it does? I would check if anything is actually getting rebuilt, since the hash of the git commit does not make it into the DAG hashes (updated tag = changed commit id?). Would be safer to delete the PR directory for a clean slate, then a simple "Retest this please"… or did you monitor that the directory got deleted by one of the other plans?

Ahh you're right. It might not rebuild because of the same hash... I didn't delete the directory beforehand, so it probably won't rebuild. I will check this and do what you suggested otherwise. Thank you!

**Comment by iomaganaris** [comment]
Retest this please

**Pull request merged**
