### PR TITLE
Ultraliser depends on Eigen

### PR DESCRIPTION
**Pull request by NadirRoGue**
cc @marwan-abdellah

### CODE REVIEW

**Review by marwan-abdellah — DISMISSED** [review]

**Review by matz-e — COMMENTED** [review]
Probably needs a rebase on `develop`

**Comment by NadirRoGue** [comment]
@matz-e does spykfunc depends on ultraliser?

**Comment by matz-e** [comment]
@NadirRoGue no, I restarted that one test.

FWIW, `@develop` in a module will not get updated, but is rather frozen in time. I'd prefer a fixed commit with some temporary version, like `0.3.2022-08-04`.

**Comment by NadirRoGue** [comment]
Thanks, Ill ask for a version tag to be created

**Comment by NadirRoGue** [comment]
This PR is not needed anymore.

**Pull request closed without merging**
