### PR TITLE
Update fmt package with new versions

### PR DESCRIPTION
**Pull request by iomaganaris**
- Added conflict of version 9.0.0 with certain compilers due to https://github.com/fmtlib/fmt/issues/3028
- Merged in upstream https://github.com/spack/spack/pull/32527

### CODE REVIEW

**Review by olupton — DISMISSED** [review]

**Review by matz-e — COMMENTED** [review]
These changes will be lost on the next rebase/merge with upstream. Can you please use `spack augment` for this stuff?

And yes, should probably go upstream.

**Comment by iomaganaris** [comment]
I've also opened https://github.com/spack/spack/pull/32527

**Review by matz-e — DISMISSED** [review]

**Review by matz-e — COMMENTED** [review]
I _think_ that the flake stuff should be happier when doing
```
from spack.package import *
```
since we're now using directives.

**Comment by iomaganaris** [comment]
The package got updated in upstream https://github.com/spack/spack/pull/32527. Shall I just apply the changes from upstream to our `spack`?

**Comment by matz-e** [comment]
> The package got updated in upstream [spack#32527](https://github.com/spack/spack/pull/32527). Shall I just apply the changes from upstream to our `spack`?

Yes, please

**Review by matz-e — APPROVED** [review]

**Pull request merged**
