### PR TITLE
update bglibpy to 4.4.6

### PR DESCRIPTION
**Pull request by anilbey**

### CODE REVIEW

**Review by matz-e — APPROVED** [review]

**Comment by asanin-epfl** [comment]
@anilbey According to `setup.py` the deployed version of BGLIbPy requires those additional dependencies:
"pyrsistent<0.17.1",
"pandas",
"bluepy-configfile>=0.1.2.dev1",
"h5py"

Please verify that the deployed version of BGLibPy works, and that the latest deployed version of bluepy also works with those changes.

**Comment by anilbey** [comment]
Thanks @asanin-epfl, nice catch! I will update the dependencies. The latest versions, namely py-bglibpy/4.4.6 and py-bluepy/0.14.14 work fine together.

**Comment by matz-e** [comment]
Hm, I should see if I can add some check to the CI for this…

**Comment by asanin-epfl** [comment]
`py-pyrsistent` package can be taken from here https://github.com/BlueBrain/spack/blob/324ef4f7757780c60b398e115816367e89d607a2/var/spack/repos/builtin/packages/py-pyrsistent/package.py. Anyway my PR seems to stuck.

**Comment by anilbey** [comment]
Those dependencies are no longer needed for bglibpy 4.4.10 version.
`bluepy-configfile` and `pyrsistent` come from `bluepy`. `pandas` was not needed anyways. `h5py` is already mentioned in the spack package.

 Here is another PR for bglibpy v4.4.10: #938

**Pull request merged**
