### PR TITLE
spark et al: bump to 3.1.1

### PR DESCRIPTION
**Pull request by matz-e**

### CODE REVIEW

**Comment by matz-e** [comment]
Retest this please

**Comment by pramodk** [comment]
Are these changes "stable" to deploy in production?

**Comment by matz-e** [comment]
Needs another fix to Spykfunc, but apart from that, yes.

**Comment by matz-e** [comment]
Started a custom CI run here using this Spack branch: https://bbpcode.epfl.ch/ci/blue/organizations/jenkins/building.Spykfunc/detail/building.Spykfunc/1537/pipeline

**Comment by matz-e** [comment]
@pramodk seems good to merge now.

**Review by pramodk — APPROVED** [review]
LGTM

**Pull request merged**
