### PR TITLE
Adds Brion version 3.3.8

### PR DESCRIPTION
**Pull request by NadirRoGue**
And missing 3.3.7 for completeness

### CODE REVIEW

**Review by matz-e — DISMISSED** [review]

**Comment by NadirRoGue** [comment]
@matz-e Hey, seems like intel compiler 19.1.3.304 is not available anymore: 
```
nroman@bbpv1:~$ module load unstable
nroman@bbpv1:~$ module load intel
intel/20.0.4                     intel-oneapi-compilers/2021.4.0  
```
but the viz stack expects it, since it does not work with intel 20. Can the viz stack use an archive with the intel 19 compiler?

EDIT: Nevermind, it is availabe, but I dont understand why it cannot find it:
```
nroman@bbpv1:~$ spack compilers
==> Available compilers
-- clang rhel7-x86_64 -------------------------------------------
clang@13.0.0  clang@12.0.1  clang@11.1.0  clang@3.4.2

-- gcc rhel7-x86_64 ---------------------------------------------
gcc@11.2.0  gcc@9.4.0  gcc@4.8.5

-- intel rhel7-x86_64 -------------------------------------------
intel@2021.4.0  intel@19.1.3.304

-- nvhpc rhel7-x86_64 -------------------------------------------
nvhpc@22.2  nvhpc@22.1  nvhpc@21.11  nvhpc@21.2

-- oneapi rhel7-x86_64 ------------------------------------------
oneapi@2021.4.0  oneapi@2021.1

```

**Comment by matz-e** [comment]
@NadirRoGue this seems very strange. I see the compiler on different PRs just fine. I'll poke around a little.

**Comment by matz-e** [comment]
@NadirRoGue Seems like the license server upgrade is interfering with the CI. Will have to wait until CS is done with that…

**Comment by NadirRoGue** [comment]
@matz-e Thanks a lot for finding out!

**Review by matz-e — APPROVED** [review]

**Comment by matz-e** [comment]
@NadirRoGue I retriggered a whole bunch of stuff, seems like we're all green now!

**Comment by NadirRoGue** [comment]
Perfect, thanks a lot!

**Pull request merged**
