### PR TITLE
py-sonata-network-reduction v0.0.5

### PR DESCRIPTION
**Pull request by asanin-epfl**

### CODE REVIEW

**Review by matz-e — APPROVED** [review]

**Review by pramodk — APPROVED** [review]

**Comment by asanin-epfl** [comment]
Is it ok that CI is in progress for more than 2 hours?

**Comment by matz-e** [comment]
> Is it ok that CI is in progress for more than 2 hours?

no

**Comment by asanin-epfl** [comment]
@pramodk or @matz-e  Can you please restart CI here?

**Comment by matz-e** [comment]
Retest this please

**Comment by matz-e** [comment]
All good now :)

**Comment by asanin-epfl** [comment]
Thank you!

**Pull request merged**
