### PR TITLE
Added neurodamus module with coreneuron and knl support for hippocamp…

### PR DESCRIPTION
**Pull request by iomaganaris**
…us circuit

### CODE REVIEW

**Comment by st4rl3ss** [comment]
please retest

**Comment by iomaganaris** [comment]
please retest

**Review by pramodk — APPROVED** [review]

**Comment by iomaganaris** [comment]
please retest

**Comment by iomaganaris** [comment]
please retest

**Comment by iomaganaris** [comment]
please retest

**Comment by matz-e** [comment]
The error message indicates a problem with modules.

When switching to a `/knl` suffix, you're trying to replace an existing file with a directory…

**Comment by matz-e** [comment]
Retest this please.

I should have removed the offending directory.

**Pull request merged**
