### PR TITLE
remove brion from serial packages

### PR DESCRIPTION
**Pull request by ppodhajski**

### CODE REVIEW

**Review by matz-e — APPROVED** [review]

**Comment by ppodhajski** [comment]
It seems removing brion from serial prevents emsim module being generated:
`
$ find /gpfs/bbp.[...] jenkins/pulls/631/modules/ |grep emsim
$
`

**Comment by ppodhajski** [comment]
It seems removing brion from serial prevents emsim module being generated:
`
$ find /gpfs/bbp.[...] jenkins/pulls/631/modules/ |grep emsim
$
`

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Pull request closed without merging**
