### PR TITLE
Merge llnl

### PR DESCRIPTION
**Pull request by ohm314**
merge in latest upstream changes

### CODE REVIEW

**Comment by tristan0x** [comment]
Anyone to review this one? :)

**Comment by ohm314** [comment]
I was hoping someone could OK this so we can have some reasonably up-to-date packages...

**Comment by tristan0x** [comment]
I could not agree more. @pramodk maybe?

**Comment by pramodk** [comment]
review? :)
but let me re-build entire stack today with this PR so that we are sure it's not breaking anything.

**Comment by pramodk** [comment]
@tristan0x @ohm314 : as discussed, force pushed develop and its now synced with llnl/develop.

**Pull request merged**
