### PR TITLE
deploy brion 3.3.0 as a module

### PR DESCRIPTION
**Pull request by ppodhajski**

### CODE REVIEW

**Review by matz-e — APPROVED** [review]

**Review by matz-e — COMMENTED** [review]
Looks actually like the module verification will have to be adjusted depending on the module version?

**Comment by ppodhajski** [comment]
I assume the module verification is checking for a presence of a generated python module?
This https://github.com/BlueBrain/spack/pull/946/files addresses the fact _brain_ module was renamed to _brion_ .

**Comment by matz-e** [comment]
> I assume the module verification is checking for a presence of a generated python module?
> This https://github.com/BlueBrain/spack/pull/946/files addresses the fact _brain_ module was renamed to _brion_ .

This is actually happening in the `jenkins-pipeline` project on Gerrit… see here: https://bbpcode.epfl.ch/code/#/c/46870/

**Comment by ppodhajski** [comment]
> This is actually happening in the `jenkins-pipeline` project on Gerrit… see here: https://bbpcode.epfl.ch/code/#/c/46870/

@matz-e  If I understand correctly this checks only the default module (being 3.3.0)

**Comment by ppodhajski** [comment]
please retest this

**Comment by ppodhajski** [comment]
retest this please

**Pull request merged**
