### PR TITLE
docs: add cache path to reduce installation directory confusion

### PR DESCRIPTION
**Pull request by matz-e**

### CODE REVIEW

**Comment by cattabiani** [comment]
May you also differentiate what is needed to do for installing your local spack and what is needed every time you want to use it? Because atm it was not clear to me what I needed to do once and what I needed to do every time I wanted to use this local spack

**Comment by matz-e** [comment]
@cattabiani better?

**Comment by cattabiani** [comment]
it looks like you just need to add the 2 paths. There is also module load spack foe example and . /.../ spack-env

**Comment by matz-e** [comment]
> it looks like you just need to add the 2 paths. There is also module load spack foe example and . /.../ spack-env

I don't understand. The `module load spack` is for basic usage when one does not modify anything…

**Comment by cattabiani** [comment]
ah so it is not to be used every time I want to use this. Maybe that was another of my mistakes

**Review by cattabiani — APPROVED** [review]
LGTM! Thx for adding this. Useful for noobs like me :D

**Pull request merged**
