### PR TITLE
bbp-workflow version 2.1.2 hotfix docutils dependency

### PR DESCRIPTION
**Pull request by genric**
Also fix the notebook module name which was forgotten in the previous commit.

### CODE REVIEW

**Comment by genric** [comment]
I think it is the same error that shows up in the build log:
```
Error: unorderable types: NoneType() < str()
```

**Comment by matz-e** [comment]
> I think it is the same error that shows up in the build log:
> 
> ```
> Error: unorderable types: NoneType() < str()
> ```

Yes… sorry about that! Trying to come up with a fix that will not paper over some other potential issue

**Comment by matz-e** [comment]
Retest this please

Repeatedly retriggering (this is not deterministic), until by chance we pass :(

**Review by matz-e — APPROVED** [review]

**Comment by genric** [comment]
Retest this please

No worries :) As long as this is expected behavior even if not deterministic.
Is there a way to trigger `unstable` redeploy after this one is merged?

**Comment by matz-e** [comment]
OK, it's running and past that one point of failure. `unstable` should be automatically triggered by a merge commit. If not, there's something wrong

**Comment by genric** [comment]
Hmm, last time I didn't see it triggered by merge. Let's see what happens when we merge this...

**Comment by matz-e** [comment]
CS ticket filed: https://bbpteam.epfl.ch/project/issues/browse/HELP-13470

**Pull request merged**
