### PR TITLE
Update Bluepymm to 0.7.49

### PR DESCRIPTION
**Pull request by anilbey**

### CODE REVIEW

**Review by matz-e — DISMISSED** [review]

**Comment by pramodk** [comment]
@anilbey : can be rebased & merged?

**Comment by anilbey** [comment]
@pramodk there seems to be an error. Please let me know if there's something I can do.

**Comment by matz-e** [comment]
Retest this please.

This happens every now and then from a failed deployment. We need to redeploy some stages to get rid of this. Rerunning the Jenkins plan normally helps, if you're in the right teams, you should be able to do that yourself, too.

**Comment by anilbey** [comment]
What's the status here? Can this be merged?

**Comment by matz-e** [comment]
Could you rebase it on the latest `develop`, please?

**Comment by anilbey** [comment]
Is it ok now?

**Comment by matz-e** [comment]
Yes, apparently I don't even have to re-approve.

**Comment by anilbey** [comment]
Great. Is there something else needed to perform the merge?

**Comment by matz-e** [comment]
> Great. Is there something else needed to perform the merge?

Codecoverage is not essential. Can you "Squash and merge" yourself now?

**Comment by anilbey** [comment]
The button appears but it's grayed out. It says: "Merging can be performed automatically with 1 approving review."

**Comment by anilbey** [comment]
Can you review again, I think it is required because of the merge

**Review by matz-e — APPROVED** [review]

**Pull request merged**
