### PR TITLE
environment modifications: use better before environment

### PR DESCRIPTION
**Pull request by matz-e**
Replace os.environ by bash reference environment to catch modifications
done by the profile/rc files.

### CODE REVIEW

**Comment by matz-e** [comment]
See [this gist](https://gist.github.com/matz-e/949bf5a76e81905a1b6697cbe9806d4b) for differences.

**Comment by pramodk** [comment]
> Replace os.environ by bash reference environment to catch modifications done by the profile/rc files.

@matz-e  : could you provide some more context for this please? I didn't get what issue this is solving...

**Comment by matz-e** [comment]
It fixes #263. When deploying, the environment that `spack` is executed in (and thus `os.environ`) may be different than executing a vanilla shell (here `bash). Thus additional differences, e.g., from bash profile/rc files may be picked up.

**Comment by pramodk** [comment]
Ok...re-generating module will be sufficient?

**Review by pramodk — APPROVED** [review]

**Comment by matz-e** [comment]
Yes, should be.

**Pull request merged**
