### PR TITLE
Bglibpy 4.4.10

### PR DESCRIPTION
**Pull request by anilbey**
The additional dependencies of bglibpy that are not mentioned in the spack package are removed in this version. They were not directly required by bglibpy in the first place.

### CODE REVIEW

**Review by wvangeit — APPROVED** [review]

**Comment by asanin-epfl** [comment]
Now as we deleted those dependencies from `package.py`, how old versions of BGLibPy will behave? They still require it. I'm not a spack expert. @matz-e please advice.

**Comment by matz-e** [comment]
> Now as we deleted those dependencies from package.py, how old versions of BGLibPy will behave? They still require it. I'm not a spack expert. @matz-e please advice.

If dependencies are missing and not otherwise provided, installation of older versions will be incomplete.

If you drop a dependency, you can add a `when` guard:
```
depends_on('my_favorite_dependency', when='@:4.46')
```
will depend on the dependency until (and including) 4.46.

**Comment by anilbey** [comment]
In fact, we did not delete the dependencies from `package.py`. We only deleted those extra dependencies from the `setup.py` of BGLibPy. Those dependencies were not in the `package.py` for the old versions and the package was working fine since those dependencies are already a dependency of BluePy(another dependency of BGLibPy).

**Comment by asanin-epfl** [comment]
Great to hear it didn't bring problems before.

**Pull request merged**
