### PR TITLE
omega-h: use official repository, add/deploy 9.32.0

### PR DESCRIPTION
**Pull request by tristan0x**

### CODE REVIEW

**Comment by matz-e** [comment]
Meh. Bogus url for `netcdf`?

**Comment by matz-e** [comment]
@tristan0x you should update `trilinos`, as there were some changes recently: https://github.com/spack/spack/blob/f83d98a62d0100b8f9b510d7e7b58af81d63af0a/var/spack/repos/builtin/packages/trilinos/package.py#L330

Of course, the awesome folks from `netcdf` delete old versions from their mirror :)

**Review by matz-e — CHANGES_REQUESTED** [review]
Switch URLs to the Github mirror, please: https://github.com/Unidata/netcdf-c/releases

**Comment by tristan0x** [comment]
The version I wanted to use is actually missing a contribution we made. Closing this.

**Pull request closed without merging**
