### PR TITLE
Enabled synthesis `placement-algorithm`

### PR DESCRIPTION
**Pull request by arsenius7**
* placement-algorithm -> 2.0.3
 * morph-tool -> 0.1.2
 * new packages:
   * py-munkres@1.0.11
   * py-region-grower@0.0.2
   * py-tmd@2.0.3
   * py-tns@1.0.4

### CODE REVIEW

**Comment by pramodk** [comment]
@matz-e @arsenius7  : before merging this, we should add new non-bbp python packages in serial libraries.

```
==> Successfully installed placement-algorithm
  Fetch: 3.03s.  Build: 3.79s.  Total: 6.82s.
[+] /gpfs/bbp.cscs.ch/apps/hpc/jenkins/pulls/217/deploy/applications/2019-02-05/linux-rhel7-x86_64/gcc-6.4.0/placement-algorithm-2.0.3-jq3ncy6wq3
==> Error: 'ascii' codec can't encode character u'\u2018' in position 142741: ordinal not in range(128)
```
@matz-e  : I thought you fixed this?

**Comment by pramodk** [comment]
Please retest

**Comment by matz-e** [comment]
> @matz-e @arsenius7 : before merging this, we should add new non-bbp python packages in serial libraries.
> 
> ```
> ==> Successfully installed placement-algorithm
>   Fetch: 3.03s.  Build: 3.79s.  Total: 6.82s.
> [+] /gpfs/bbp.cscs.ch/apps/hpc/jenkins/pulls/217/deploy/applications/2019-02-05/linux-rhel7-x86_64/gcc-6.4.0/placement-algorithm-2.0.3-jq3ncy6wq3
> ==> Error: 'ascii' codec can't encode character u'\u2018' in position 142741: ordinal not in range(128)
> ```
> 
> @matz-e : I thought you fixed this?

Yes… I thought so, too.

**Comment by arsenius7** [comment]
Can it be merged now that it passes CI?
As for the non-BBP packages, the only one here is `munkres`, and if necessary we can make it optional.

**Comment by pramodk** [comment]
@arsenius7  : I meant [this change](https://github.com/BlueBrain/spack/pull/217/files#diff-b2a49fad343c4e33f91cabc0d4eda9ab). The new dependencies like `py-scikit-learn` could be enabled in python-packages so that if someone try to install locally, all those dependencies are already present in cache.

**Review by matz-e — COMMENTED** [review]
LGTM

**Review by matz-e — APPROVED** [review]

**Comment by matz-e** [comment]
Please retest

**Comment by arsenius7** [comment]
> The new dependencies like py-scikit-learn could be enabled in python-packages so that if someone try to install locally, all those dependencies are already present in cache.

I see; thanks.

**Pull request merged**
