### PR TITLE
add scipy dependency in py-neurodamus

### PR DESCRIPTION
**Pull request by WeinaJi**

### CODE REVIEW

**Comment by pramodk** [comment]
@WeinaJi : if this is needed, can you make this PR ready? thanks!

**Review by pramodk — DISMISSED** [review]
LGTM at least.

I assume @ferdonline don't have concern about extra dependency?

**Comment by pramodk** [comment]
Retest this please

**Review by pramodk — APPROVED** [review]

**Comment by pramodk** [comment]
@matz-e : could you confirm if mvdtool upgrade is fine? (asking because it impacts/rebuilds many packages...)

**Comment by pramodk** [comment]
Retest this please

**Review by matz-e — APPROVED** [review]

**Pull request merged**
