### PR TITLE
omega-h: bump to 9.33.0.dev1

### PR DESCRIPTION
**Pull request by tristan0x**

### CODE REVIEW

**Review by matz-e — COMMENTED** [review]
Any chance this stuff will make it upstream? Newer versions of Spack update this recipe…

**Comment by tristan0x** [comment]
not this version, this is a BlueBrain one, not the official from Sandia National Labs

**Comment by matz-e** [comment]
Slowly wondering if the fork could be renamed, then? Not urgent, just thinking out loud.

**Comment by pramodk** [comment]
> Slowly wondering if the fork could be renamed, then? Not urgent, just thinking out loud.

Currently only zee/steps is consumer. So this is fine for time being.

**Comment by tristan0x** [comment]
plizz review @matz-e

**Review by pramodk — APPROVED** [review]
LGTM

**Review by matz-e — APPROVED** [review]
Fine. BTW, `zee@develop` is not really OK to deploy, can we add some pseudo-versions there, too, please?

**Comment by tristan0x** [comment]
> Fine. BTW, `zee@develop` is not really OK to deploy, can we add some pseudo-versions there, too, please?

What is the issue?

**Comment by matz-e** [comment]
Well, if you're fine with having a random version, there is none. But `@develop` is a moving target, it will be deployed once and then not updated (since `@develop` is already installed). So you will have an old version sitting around, as there's no mechanism right now to continuously rebuild `@develop` and keep it on the last commit. I think the latter was the intent?

**Pull request merged**
