### PR TITLE
Bumped MVDTool version

### PR DESCRIPTION
**Pull request by iomaganaris**

### CODE REVIEW

**Review by matz-e — DISMISSED** [review]

**Comment by matz-e** [comment]
Sorry… I think this slipped me before.

@iomaganaris I actually think that the better way would be to follow the C++ lead and use external dependencies?

See also BSD-130

**Comment by iomaganaris** [comment]
> Sorry… I think this slipped me before.
> 
> @iomaganaris I actually think that the better way would be to follow the C++ lead and use external dependencies?
> 
> See also BSD-130

I see. Yes, this makes more sense. I think that `MVDTool` cmake needs a bit of edit to try to find `pybind11` package and if not try to use the submodule, right? Or the other way around? I will create a PR to check this

**Comment by matz-e** [comment]
> > Sorry… I think this slipped me before.
> > @iomaganaris I actually think that the better way would be to follow the C++ lead and use external dependencies?
> > See also BSD-130
> 
> I see. Yes, this makes more sense. I think that `MVDTool` cmake needs a bit of edit to try to find `pybind11` package and if not try to use the submodule, right? Or the other way around? I will create a PR to check this

You could just blatantly enable external dependencies (forgot the flag), and list them all as dependencies. I think HighFive is probably also in there.

**Comment by iomaganaris** [comment]
> > > Sorry… I think this slipped me before.
> > > @iomaganaris I actually think that the better way would be to follow the C++ lead and use external dependencies?
> > > See also BSD-130
> > 
> > 
> > I see. Yes, this makes more sense. I think that `MVDTool` cmake needs a bit of edit to try to find `pybind11` package and if not try to use the submodule, right? Or the other way around? I will create a PR to check this
> 
> You could just blatantly enable external dependencies (forgot the flag), and list them all as dependencies. I think HighFive is probably also in there.

Sorry, I didn't undestand what you mean 😕 
I saw that `HighFive` for example is added in the `CMake` with `find_package(HighFive)` similar to what I've done in this draft PR: https://github.com/BlueBrain/MVDTool/pull/80
On top of the PR mentioned `py-mvdtool` spack recipe should also depend on `py-pybind11` to work.
Is there an easier way to make this work? I don't know 😕

**Comment by matz-e** [comment]
Damn… my bad! I'm sorry, I got this confused with our other Python package things! In libSONATA™ we have `-DEXTLIB_FROM_SUBMODULES=ON` to use submodules… that's what I had in my mind.

For their Python, it's always on: https://github.com/BlueBrain/libsonata/blob/master/setup.py#L89

**Comment by iomaganaris** [comment]
> Damn… my bad! I'm sorry, I got this confused with our other Python package things! In libSONATA™ we have `-DEXTLIB_FROM_SUBMODULES=ON` to use submodules… that's what I had in my mind.

Ahhh I now see. Shall we do the same in `MVDTool` then?

> For their Python, it's always on: https://github.com/BlueBrain/libsonata/blob/master/setup.py#L89

For python shouldn't it be `OFF` to use the external `pybind11` package in our case? Apart from that all the other should be similar to `libsonata` and `py-libsonata`.

**Comment by matz-e** [comment]
> > Damn… my bad! I'm sorry, I got this confused with our other Python package things! In libSONATA™ we have `-DEXTLIB_FROM_SUBMODULES=ON` to use submodules… that's what I had in my mind.
> 
> Ahhh I now see. Shall we do the same in `MVDTool` then?

Yeah, sorry, I just created more confusion there. These EXTLIB things hold for things like HighFive, but we don't use wheels and always use external installations here, anyways.

> > For their Python, it's always on: https://github.com/BlueBrain/libsonata/blob/master/setup.py#L89
> 
> For python shouldn't it be `OFF` to use the external `pybind11` package in our case? Apart from that all the other should be similar to `libsonata` and `py-libsonata`.

Really, I think this should be an issue that will come back and bite us with `{py-,}libsonata` and others, too. Maybe the simplest approach would be to see if this could be solved from the Spack side to create unique source caches.

**Comment by iomaganaris** [comment]
> Really, I think this should be an issue that will come back and bite us with `{py-,}libsonata` and others, too. Maybe the simplest approach would be to see if this could be solved from the Spack side to create unique source caches.

I agree that this will be quite helpful to avoid issues with other packages and make debugging easier

**Comment by WeinaJi** [comment]
Hello guys, 

Just wondering, what's the solution for this PR to pass the deployment test? Please let me know if I can help. I have a PR dependent on this one. Thanks!

**Comment by matz-e** [comment]
@WeinaJi this is blocked by mirror collisions. See #798, which hopefully provides a solution. Once that's verified and merged, we can proceed with this PR

**Comment by jorblancoa** [comment]
retest this please jenkins

**Review by matz-e — APPROVED** [review]

**Pull request merged**
