### PR TITLE
Adds Brion 3.3.6 release

### PR DESCRIPTION
**Pull request by NadirRoGue**

### CODE REVIEW

**Comment by NadirRoGue** [comment]
retest this please

**Review by matz-e — APPROVED** [review]

**Comment by NadirRoGue** [comment]
I've ran the commands the bot suggested, everything worked, is it ok to merge? What is the Centos6 error about?

**Comment by NadirRoGue** [comment]
Thanks!

**Comment by matz-e** [comment]
> I've ran the commands the bot suggested, everything worked, is it ok to merge? What is the Centos6 error about?

I've marked the stuff we care about as "required". If Centos6 keeps failing, I should maybe disable it :)

The bot is mostly about feedback to point out what changed / was rebuilt. Ideally, we'd have some module test to check this, too.

**Pull request merged**
