### PR TITLE
Add Region grower to whitelist

### PR DESCRIPTION
**Pull request by arnaudon**

### CODE REVIEW

**Comment by arnaudon** [comment]
@mgeplf , I guess this should do it?

**Review by matz-e — APPROVED** [review]

**Comment by mgeplf** [comment]
> @mgeplf , I guess this should do it?

If I only knew - but if @matz-e says it's cool, it's cool

**Comment by matz-e** [comment]
Any issue? We don't need all tests, the ones marked required seem to have passed :)

**Comment by arnaudon** [comment]
I think it's ok, I had forgotten to do that, so we couldn't load this module from unstable directly, we'll retry later once this is available on bb5.

**Pull request merged**
