### PR TITLE
morph-tool 2.6.0

### PR DESCRIPTION
**Pull request by asanin-epfl**

### CODE REVIEW

**Comment by mgeplf** [comment]
@matz-e is this an error on our end, or due to spack?
```
Error
ProcessError: Command exited with status 2: '/usr/bin/tar' '-oxf' '/gpfs/bbp.cscs.ch/ssd/slurmTmpFS/bbprelman/2235215/spack-stage-py-bluepy-2.3.0-6ylz5xlt74jnimsddsj23rwn2j4nsi3l/bluepy-v2.3.0.tar.gz'
Stacktrace
Traceback (most recent call last):
File "/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/pulls/1203/spack/lib/spack/spack/build_environment.py", line 848, in _setup_pkg_and_run
return_value = function(pkg, kwargs)
File "/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/pulls/1203/spack/lib/spack/spack/installer.py", line 1604, in build_process
pkg.do_patch()
File "/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/pulls/1203/spack/lib/spack/spack/package.py", line 1368, in do_patch
self.do_stage()
File "/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/pulls/1203/spack/lib/spack/spack/package.py", line 1354, in do_stage
self.stage.expand_archive()
File "/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/pulls/1203/spack/lib/spack/spack/util/pattern.py", line 18, in __call__
for item in self.container]
File "/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/pulls/1203/spack/lib/spack/spack/util/pattern.py", line 18, in <listcomp>
for item in self.container]
File "/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/pulls/1203/spack/lib/spack/spack/stage.py", line 590, in expand_archive
self.fetcher.expand()
File "/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/pulls/1203/spack/lib/spack/spack/fetch_strategy.py", line 72, in wrapper
return fun(self, *args, **kwargs)
File "/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/pulls/1203/spack/lib/spack/spack/fetch_strategy.py", line 469, in expand
decompress(self.archive_file)
File "/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/pulls/1203/spack/lib/spack/spack/util/executable.py", line 198, in __call__
proc.returncode, long_msg)
spack.util.executable.ProcessError: Command exited with status 2:
'/usr/bin/tar' '-oxf' '/gpfs/bbp.cscs.ch/ssd/slurmTmpFS/bbprelman/2235215/spack-stage-py-bluepy-2.3.0-6ylz5xlt74jnimsddsj23rwn2j4nsi3l/bluepy-v2.3.0.tar.gz'
Standard Output
Cannot open log for py-bluepy@2.3.0%gcc@9.3.0 arch=linux-rhel7-x86_64/6ylz5xlProcessError: Command exited with status 2:
'/usr/bin/tar' '-oxf' '/gpfs/bbp.cscs.ch/ssd/slurmTmpFS/bbprelman/2235215/spack-stage-py-bluepy-2.3.0-6ylz5xlt74jnimsddsj23rwn2j4nsi3l/bluepy-v2.3.0.tar.gz'
```

**Comment by matz-e** [comment]
Seems a concurrency issue locking stuff on GPFS.

Retest this please.

**Comment by asanin-epfl** [comment]
retest this please

**Comment by asanin-epfl** [comment]
oh, finally passed!

**Comment by genric** [comment]
Lucky you :) I still play this roulette...

**Review by matz-e — APPROVED** [review]

**Comment by asanin-epfl** [comment]
Hooray!

**Pull request merged**
