### PR TITLE
gcc: Avoid excessive stat calls (spack#30005)

### PR DESCRIPTION
**Pull request by sergiorg-hpc**
More information in BSD-271 and the original upstream PR:
https://github.com/spack/spack/pull/30005

### CODE REVIEW

**Comment by pramodk** [comment]
I assume:
* this needs to be a draft PR
* add new variant so that GCC would be re-deployed (would that re-trigger whole new deployment? I am not 100% sure)
* take above GCC and build some software stack like cellular simulation with new and old GCC version
* based on the above, report the build time perf results and then decide how we should proceed in production deployment

**Comment by sergiorg-hpc** [comment]
Even though the benefits for setting the flag are not outstanding in all cases, it seems evident that the change proposed in this PR generally helps to reduce compile times between 20%-60%.

For instance, using Spack and a dedicated compute node, here is an example building HDF5 1.10.7 with the default GCC 4.8.5 available locally, with the current GCC 11.2.0 deployed on BB5, and with GCC 11.2.0 from this PR:

```
                gcc@4.8.5 / 2m53.391s
gcc@11.2.0 (without flag) / 4m51.637s
   gcc@11.2.0 (with flag) / 2m59.851s
```

Despite that the PR version is located on GPFS, it can provide a compile time similar to GCC 4.8.5, that is locally available in the compute nodes. Compared to the current deployed GCC 11.2.0, the speed-up is ~1.6.

If we now build `coreneuron@develop`, which also builds HDF5 alongside `libsonata-report` and other libraries, the execution times for each version of GCC 11.2.0 also illustrate a speed-up over ~1.5:

```
gcc@11.2.0 (without flag) / 6m58.676s
   gcc@11.2.0 (with flag) / 4m37.271s
```

Finally, if we build `neuron@develop+coreneuron`, which builds all of the above plus other dependencies, the execution times are listed below:

```
gcc@11.2.0 (without flag) / 23m59.178s
   gcc@11.2.0 (with flag) / 19m31.492s
```

Here, the overall speed-up is ~1.2, a bit below what we observed in the packages above but still a 20% improvement that can save several minutes from the deployment per package.

**Comment by sergiorg-hpc** [comment]
Just an observation. The numbers above are obtained with `spack install -j 18 package%gcc@version` on a dedicated compute node. Leaving the default values and using the login node of BB5, can produce different performance results. For instance, in the login node, running `spack install hdf5%gcc@version` gives the following:

```
                gcc@4.8.5 / 2m14.251s
gcc@11.2.0 (without flag) / 3m32.369s
   gcc@11.2.0 (with flag) / 2m40.611s
```

This is still a 32.3% improvement compared to the same compiler version without the flag, but the performance difference with the local GCC 4.8.5 installed in the login node is much higher in comparison.

**Comment by matz-e** [comment]
I say no to creating temporary variants. This has come to bite us at times.

OTOH, we can add the additional `c(xx)flags` in the compiler configuration, too, without any rebuild needed if I understand some comments in the upstream PR correctly.

**Comment by olupton** [comment]
The extra variant isn't very nice, but relying on Spack to add the extra flags will also tend to limit the benefits. Unless explicitly added in multiple places, we won't benefit in standalone CMake builds, and e.g. in NEURON's nrnivmodl workflow.

Is there another trick we can play to force a rebuild/hash change? Something with `bluebrain-patches` or whatever?

**Comment by pramodk** [comment]
> I say no to creating temporary variants. This has come to bite us at times.

Just to clarify though: that was added just to force the re-build of GCC so that we can grab new GCC and test it (as mere change to spack recipe would be `no-op`).

> Unless explicitly added in multiple places, we won't benefit in standalone CMake builds, and e.g. in NEURON's nrnivmodl workflow.

I agree with this - whatever solution we would choose, I would fix that for non-spack based builds as well.

**Comment by matz-e** [comment]
> Is there another trick we can play to force a rebuild/hash change? Something with `bluebrain-patches` or whatever?

I would do a `p0` suffix or something. In `compilers.yaml`, only the `gcc --version` output counts, so we should not have any rebuilds IIRC

**Comment by sergiorg-hpc** [comment]
> > Is there another trick we can play to force a rebuild/hash change? Something with `bluebrain-patches` or whatever?
> 
> I would do a `p0` suffix or something. In `compilers.yaml`, only the `gcc --version` output counts, so we should not have any rebuilds IIRC

We could just upgrade and include GCC `11.3.0` with the flag by default, so that the compiler is always built with the flag from now onwards:

https://gcc.gnu.org/gcc-11
https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/gcc/package.py#L33

This will force a re-deployment for everything, but it will also include the flag for free, no tricks needed.

**Review by matz-e — COMMENTED** [review]
LGTM, let's see rebuild times and then merge next month!

**Comment by sergiorg-hpc** [comment]
After a call with @matz-e, I have revert back to the original commit of the PR that just included the optimization flag, and also updated the recipe to include GCC `11.3.0`. This way, we will rebuild GCC, include the flag, and re-deploy everything with the new compiler. Hence, allowing us to observe the compilation times for every page and compare the performance with the previous GCC `11.2.0`.

**Edit:** Sorry @matz-e, didn't see your message!

**Comment by pramodk** [comment]
Re-deploying the whole software stack after a few months seem a bit excessive to me. Also because we need to keep all these redeployed software for longer duration.

Anyway, I am not against it. If you guys decide to do so, even though it's a minor version bump, it would be best to inform all teams in advance (Matthias knows this better than anyone else but just saying...).

**Comment by sergiorg-hpc** [comment]
> Re-deploying the whole software stack after a few months seem a bit excessive to me. Also because we need to keep all these redeployed software for longer duration.
> 
> Anyway, I am not against it. If you guys decide to do so, even though it's a minor version bump, it would be best to inform all teams in advance (Matthias knows this better than anyone else but just saying...).

After observing that work is needed in order for some packages to build, @matz-e and I have just reverted the commit from yesterday and added a variant `+strip` to force GCC to build without re-deploying every other package. So far, we observed a clear improvement in the compilation times for LLVM, although not a major improvement.

**Review by matz-e — APPROVED** [review]

**Comment by haampie** [comment]
You might also be interested in `gcc build_type=Release +profiled` (https://github.com/spack/spack/pull/30660) for a few % speedup.

**Comment by matz-e** [comment]
Thanks, @haampie.

FWIW, I don't think I ever provided any feedback on speed-ups, sorry. Got side-tracked too much. HDF5 went from 2m20s to 1m44s on our GPFS system, we'll check if that can be a wee bit faster with this, still. OTOH, depending on the cluster load, we get widely varying file-system performance, I'd be a bit concerned that these optimizations may tune in on sub-optimal scenarios.

**Pull request merged**
