### PR TITLE
zeromq: build with IntelⓇ in external packages.

### PR DESCRIPTION
**Pull request by matz-e**

### CODE REVIEW

**Comment by matz-e** [comment]
Retest this please

**Comment by pramodk** [comment]
We will check the bluepyopt built from the PR modules.

**Comment by pramodk** [comment]
Have to dig into this but while quickly testing bluepyopt I see:

```
from . import (constants, error, message, context,
ImportError: /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/pulls/760/deploy/libraries/2020-03-30/linux-rhel7-x86_64/
gcc-8.3.0/py-zmq-17.1.2-2buh62tchs/lib/python3.7/site-packages/zmq/backend/cython/
message.cpython-37m-x86_64-linux-gnu.so: undefined symbol: zmq_msg_gets
```

**Comment by pramodk** [comment]
Partly because:

```
$ ldd /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/pulls/760/deploy/libraries/2020-03-30/linux-rhel7-x86_64/gcc-8.3.0/py-zmq-17.1.2-2buh62tchs/lib/python3.7/site-packages/zmq/backend/cython/message.cpython-37m-x86_64-linux-gnu.so
	linux-vdso.so.1 =>  (0x00007fffedb02000)
	/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/pulls/760/deploy/external-libraries/2020-03-30/linux-rhel7-x86_64/intel-19.0.4/zeromq-4.3.2-msncwceskl/lib/libzmq.so (0x00007fffed3f0000)
	libzmq.so.3 => /lib64/libzmq.so.3 (0x00007fffed1a3000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fffecf9b000)
```

I added LD_LIBRARY_PATH:

```
$ echo $LD_LIBRARY_PATH
/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/pulls/760/deploy/external-libraries/2020-03-30/linux-rhel7-x86_64/intel-19.0.4/zeromq-4.3.2-msncwceskl/lib/
```
but still the same issue.

**Comment by pramodk** [comment]
I tried installing non-external zeromq: In this case we clearly see that zeromq is added to link flags:

```
....
                 ^~~~~~~~~~~~~~~~~~~~~
/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/compilers/2020-02-01/linux-rhel7-x86_64/gcc-4.8.5/gcc-8.3.0-r24zbv3waz/bin/gcc -pthread -shared -L/usr/lib64 -L/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/tools/2020-02-01/linux-rhel7-x86_64/gcc-8.3.0/gdbm-1.14.1-frv7kcgfty/lib -L/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/external-libraries/2020-02-01/linux-rhel7-x86_64/gcc-8.3.0/expat-2.2.9-rkc5cz3vef/lib -L/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/external-libraries/2020-02-01/linux-rhel7-x86_64/gcc-8.3.0/readline-8.0-uuhvgs2hgl/lib -L/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/external-libraries/2020-02-01/linux-rhel7-x86_64/gcc-8.3.0/ncurses-6.1-esk7yfugjx/lib -L/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/tools/2020-02-01/linux-rhel7-x86_64/gcc-8.3.0/gettext-0.19.8.1-ngmcb6sv3g/lib -L/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/external-libraries/2020-02-01/linux-rhel7-x86_64/gcc-8.3.0/zlib-1.2.11-5jk2xjgi67/lib -L/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/external-libraries/2020-02-01/linux-rhel7-x86_64/gcc-8.3.0/xz-5.2.4-yl7j3yvx5w/lib -L/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/external-libraries/2020-02-01/linux-rhel7-x86_64/gcc-8.3.0/sqlite-3.30.1-2sdl4kjxw2/lib -L/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/external-libraries/2020-02-01/linux-rhel7-x86_64/gcc-8.3.0/bzip2-1.0.8-urnhhbekzr/lib -L/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/external-libraries/2020-02-01/linux-rhel7-x86_64/gcc-8.3.0/libffi-3.2.1-gbrqfaxhzz/lib64 build/temp.linux-x86_64-3.7/zmq/devices/monitoredqueue.o -L/gpfs/bbp.cscs.ch/data/project/proj16/kumbhar/pramod_scratch/BBPP42-534/soft/linux-rhel7-x86_64/intel-19.0.4.243/zeromq-4.3.1-yw3rgwawx6/lib -L/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/external-libraries/2020-02-01/linux-rhel7-x86_64/gcc-8.3.0/python-3.7.4-tfxecymrkn/lib 
-Wl,--enable-new-dtags,-R/gpfs/bbp.cscs.ch/data/project/proj16/kumbhar/pramod_scratch/BBPP42-534/soft/linux-rhel7-x86_64/intel-19.0.4.243/zeromq-4.3.1-yw3rgwawx6/lib 
-lzmq -lrt -lpython3.7m -o build/lib.linux-x86_64-3.7/zmq/devices/monitoredqueue.cpython-37m-x86_64-linux-gnu.so
==> Executing phase: 'install'
....
bash-4.2$ ldd /gpfs/bbp.cscs.ch/data/project/proj16/kumbhar/pramod_scratch/BBPP42-534/soft/linux-rhel7-x86_64/gcc-8.3.0/py-zmq-19.0.0-esgmbif5wk/lib/python3.7/site-packages/zmq/backend/cython/message.
message.cpython-37m-x86_64-linux-gnu.so  message.pxd
bash-4.2$ ldd /gpfs/bbp.cscs.ch/data/project/proj16/kumbhar/pramod_scratch/BBPP42-534/soft/linux-rhel7-x86_64/gcc-8.3.0/py-zmq-19.0.0-esgmbif5wk/lib/python3.7/site-packages/zmq/backend/cython/message.cpython-37m-x86_64-linux-gnu.so
	linux-vdso.so.1 =>  (0x00007fffedb02000)
	libzmq.so.5 => /gpfs/bbp.cscs.ch/data/project/proj16/kumbhar/pramod_scratch/BBPP42-534/soft/linux-rhel7-x86_64/intel-19.0.4.243/zeromq-4.3.1-yw3rgwawx6/lib/libzmq.so.5 (0x00007fffed3ea000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fffed1e2000)
	libpython3.7m.so.1.0 => /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/external-libraries/2020-02-01/linux-rhel7-x86_64/gcc-8.3.0/python-3.7.4-tfxecymrkn/lib/libpython3.7m.so.1.0 (0x00007fffeccaa000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fffeca8e000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fffec6c1000)
	libsodium.so.23 => /gpfs/bbp.cscs.ch/data/project/proj16/kumbhar/pramod_scratch/BBPP42-534/soft/linux-rhel7-x86_64/intel-19.0.4.243/libsodium-1.0.17-ehb2dcvxf5/lib/libsodium.so.23 (0x00007fffec407000)
	libimf.so => /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/compilers/2020-02-01/linux-rhel7-x86_64/gcc-4.8.5/intel-19.0.4-3ahwr77o2x/compilers_and_libraries_2019.4.243/linux/compiler/lib/intel64/libimf.so (0x00007fffebe67000)
	libirng.so => /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/compilers/2020-02-01/linux-rhel7-x86_64/gcc-4.8.5/intel-19.0.4-3ahwr77o2x/compilers_and_libraries_2019.4.243/linux/compiler/lib/intel64/libirng.so (0x00007fffebaf5000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fffeb7f3000)
	libcilkrts.so.5 => /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/compilers/2020-02-01/linux-rhel7-x86_64/gcc-4.8.5/intel-19.0.4-3ahwr77o2x/compilers_and_libraries_2019.4.243/linux/compiler/lib/intel64/libcilkrts.so.5 (0x00007fffeb5b6000)
	libstdc++.so.6 => /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/compilers/2020-02-01/linux-rhel7-x86_64/gcc-4.8.5/gcc-8.3.0-r24zbv3waz/lib64/libstdc++.so.6 (0x00007fffeb232000)
	libintlc.so.5 => /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/compilers/2020-02-01/linux-rhel7-x86_64/gcc-4.8.5/intel-19.0.4-3ahwr77o2x/compilers_and_libraries_2019.4.243/linux/compiler/lib/intel64/libintlc.so.5 (0x00007fffeafc0000)
	libsvml.so => /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/compilers/2020-02-01/linux-rhel7-x86_64/gcc-4.8.5/intel-19.0.4-3ahwr77o2x/compilers_and_libraries_2019.4.243/linux/compiler/lib/intel64/libsvml.so (0x00007fffe961c000)
	libgcc_s.so.1 => /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/compilers/2020-02-01/linux-rhel7-x86_64/gcc-4.8.5/gcc-8.3.0-r24zbv3waz/lib64/libgcc_s.so.1 (0x00007fffe9404000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fffe9200000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007fffe8fc9000)
	libintl.so.8 => /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/tools/2020-02-01/linux-rhel7-x86_64/gcc-8.3.0/gettext-0.19.8.1-ngmcb6sv3g/lib/libintl.so.8 (0x00007fffe8dbe000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007fffe8bbb000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fffed8e3000)
	libfreebl3.so => /lib64/libfreebl3.so (0x00007fffe89b8000)
	libiconv.so.2 => /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/tools/2020-02-01/linux-rhel7-x86_64/gcc-8.3.0/libiconv-1.16-idppdaoskq/lib/libiconv.so.2 (0x00007fffe86bc000)
```

When this is installed using external zeromq then link path for zeromq is not added!

```
/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/compilers/2020-02-01/linux-rhel7-x86_64/gcc-4.8.5/gcc-8.3.0-r24zbv3waz/bin/gcc -pthread -shared -L/usr/lib64 -L/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/tools/2020-02-01/linux-rhel7-x86_64/gcc-8.3.0/gdbm-1.14.1-frv7kcgfty/lib -L/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/external-libraries/2020-02-01/linux-rhel7-x86_64/gcc-8.3.0/expat-2.2.9-rkc5cz3vef/lib -L/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/external-libraries/2020-02-01/linux-rhel7-x86_64/gcc-8.3.0/readline-8.0-uuhvgs2hgl/lib -L/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/external-libraries/2020-02-01/linux-rhel7-x86_64/gcc-8.3.0/ncurses-6.1-esk7yfugjx/lib -L/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/tools/2020-02-01/linux-rhel7-x86_64/gcc-8.3.0/gettext-0.19.8.1-ngmcb6sv3g/lib -L/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/external-libraries/2020-02-01/linux-rhel7-x86_64/gcc-8.3.0/zlib-1.2.11-5jk2xjgi67/lib -L/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/external-libraries/2020-02-01/linux-rhel7-x86_64/gcc-8.3.0/xz-5.2.4-yl7j3yvx5w/lib -L/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/external-libraries/2020-02-01/linux-rhel7-x86_64/gcc-8.3.0/sqlite-3.30.1-2sdl4kjxw2/lib -L/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/external-libraries/2020-02-01/linux-rhel7-x86_64/gcc-8.3.0/bzip2-1.0.8-urnhhbekzr/lib -L/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/external-libraries/2020-02-01/linux-rhel7-x86_64/gcc-8.3.0/libffi-3.2.1-gbrqfaxhzz/lib64 build/temp.linux-x86_64-3.7/zmq/devices/monitoredqueue.o 
-L/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/external-libraries/2020-02-01/linux-rhel7-x86_64/gcc-8.3.0/python-3.7.4-tfxecymrkn/lib 
-lzmq -lrt -lpython3.7m -o build/lib.linux-x86_64-3.7/zmq/devices/monitoredqueue.cpython-37m-x86_64-linux-gnu.so
```
So Spack set various variables like SPACK_RPATH_DIRS, PKG_CONFIG, CMAKE_PREFIX_PATH and PATH are not set for external packages. And that's result into this behaviour.

**Comment by pramodk** [comment]
As [per documentation](https://github.com/zeromq/pyzmq/wiki/Building-and-Installing-PyZMQ#building-pyzmq-from-source), safe to set configure stage option.

**Comment by pramodk** [comment]
Merging into #545 so that it can be tested with bluepyopt and company!

**Comment by pramodk** [comment]
@matz-e : closing this as we will combine everything in one deployment in #545.

**Pull request closed without merging**
