### PR TITLE
bump bluepy-v2.4.1 and voxcell-v3.0.2

### PR DESCRIPTION
**Pull request by mgeplf**

### CODE REVIEW

**Review by matz-e — APPROVED** [review]

**Comment by mgeplf** [comment]
Is this a normal error, or have I done something wrong:
```
Standard Output
Cannot open log for py-bluepy@2.4.1%gcc@9.3.0 arch=linux-rhel7-x86_64/tiui4a5ProcessError: Command exited with status 2:
'/usr/bin/tar' '-oxf' '/gpfs/bbp.cscs.ch/ssd/slurmTmpFS/bbprelman/2490977/spack-stage-py-bluepy-2.4.1-tiui4a5f3fugdhsjjnyglwfxqxsuytv2/bluepy-v2.4.1.tar.gz'
```

**Comment by matz-e** [comment]
> stage-py-bluepy-2.4.1-tiui4a5f3fugdhsjjnyglwfxqxsuytv2/bluepy-v2.4.1.tar.gz'

Yes, SNAFU.

Retest this please, oh ye, almighty Jenkins!

**Comment by olupton** [comment]
I think that's a "standard" glitch when the fetching runs in parallel; I suggest just retrying it.

**Comment by matz-e** [comment]
(really need to do an environmental `fetch` first before doing a parallel install)

**Pull request merged**
