### PR TITLE
py-sonata-network-reduction v0.0.4

### PR DESCRIPTION
**Pull request by asanin-epfl**

### CODE REVIEW

**Review by pramodk — DISMISSED** [review]
LGTM.

Just FYI : we try to reduce the modules per software on BB5. So we "try" to combine features into few (or single) release per month.

**Review by matz-e — DISMISSED** [review]

**Comment by asanin-epfl** [comment]
> Just FYI : we try to reduce the modules per software on BB5. So we "try" to combine features into few (or single) release per month.

Ok, I will stick to it. For now unfortunately only `v0.0.4` is properly working. That is why I removed the others.
Should I update anything else for CI to pass?

**Comment by pramodk** [comment]
@asanin-epfl : before merging, please test modules from pulls dir i.e. 

```
unset MODULEPATH
source /gpfs/bbp.cscs.ch/apps/hpc/jenkins/pulls/739/config/modules.sh
```

**Comment by asanin-epfl** [comment]
I checked and it worked. Please correct me if I did anything wrong.
```
sanin@bbd-7z1lwl2:~$ ssh bbpv1
Hostname: bbpv1.epfl.ch
User: sanin
-bash-4.2$ export SPACK_INSTALL_PREFIX=$HOME/software
-bash-4.2$ . spack/share/spack/setup-env.sh
-bash-4.2$ unset MODULEPATH
-bash-4.2$ source /gpfs/bbp.cscs.ch/apps/hpc/jenkins/pulls/739/config/modules.sh
-bash-4.2$ module load py-sonata-network-reduction
ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'py-sonata-network-reduction'
-bash-4.2$ module load unstable
-bash-4.2$ module load py-sonata-network-reduction
Autoloading python/3.7.4
Autoloading py-efel/3.0.70
Autoloading py-bluepyopt/1.9.12
py-bluepyopt(37):ERROR:105: Unable to locate a modulefile for 'py-bluepyopt/1.9.12'
Autoloading py-bluepy/0.14.6
Autoloading py-bglibpy/4.2.14
Autoloading hpe-mpi/2.21
-bash-4.2$ module load neurodamus-hippocampus/0.4
Autoloading reportinglib/2.5.3
-bash-4.2$ cd /gpfs/bbp.cscs.ch/project/proj30/home/sanin/CA1.O0/
-bash-4.2$ salloc -A proj30 -t 1:00:00 -p interactive --constraint=uc3 --mem 32G -n8
salloc: Granted job allocation 186406
Hostname: r1i4n35
User: sanin
bash-4.2$ unset PMI_RANK
bash-4.2$ sonata-network-reduction network sonata/circuit_config.json ./sonata-reduced --reduction_frequency 0
...working logs here...
```
As you can see I did:
```
bash-4.2$ unset PMI_RANK
```
If I don't do it, I will receive an error:
```
bash-4.2$ sonata-network-reduction network sonata/circuit_config.json ./sonata-reduced --reduction_frequency 0
MPT ERROR: PMI2_Init
```
I thought `setup_run_environment` should take of it but it does not happen for some reason.
```
    def setup_run_environment(self, env):
        env.set('NEURON_INIT_MPI', "0")
        env.unset('PMI_RANK')
```

**Comment by pramodk** [comment]
@asanin-epfl : note that PMI_RANK is **set by salloc**. So you have to load the module **after allocation** and then module load will unset that variable.

**Comment by asanin-epfl** [comment]
Great to know, thank you! Should I recheck with that?

**Review by pramodk — APPROVED** [review]

**Comment by pramodk** [comment]
> Great to know, thank you! Should I recheck with that?

why not...but I am confident that it's the case. Feel free to merge once you test.

**Comment by asanin-epfl** [comment]
> Just FYI : we try to reduce the modules per software on BB5. So we "try" to combine features into few (or single) release per month.

@pramodk please clarify. If I have a new version now `0.0.5`. What should I do now and what should I do in month from now?
Add the new version to `package.py`, create PR with that but update `/bbp-packages.yaml` with this version only in a month from now?

**Comment by matz-e** [comment]
*My* opinion is that a more immediate update should be fine, as long as you leave only one version whitelisted in `bbp-packages.yaml`. I think ~3 releases per month should be OK, but @pramodk may differ in opinion.

**Comment by pramodk** [comment]
> If I have a new version now 0.0.5. What should I do now and what should I do in month from now?

You mean immediately after 0.0.4 being deployed? :) I see that in #742!

If we require an update, it would be Ok. But I definitely "suggest" to reduce the number of installations/modules wherever possible. For example, if modules are needed for testing and so on, the local installations can be used within the team.

Jenkins does automatic deployment and module creation but #installations over the time increases lot and then we have to solve other Spack scalability issues.

**Comment by asanin-epfl** [comment]
#742 is not urgent, I can disable/cancel it for now and bring it back in a month if you want. It's just a new better version that faster than the previous one.

**Comment by mgeplf** [comment]
Just so it's clear:
1) We can add new releases as much as we want to spack (keeping in mind that it takes time to review them, so try not to have 0.1 -> 0.2 -> 0.3.... -> 0.10 -> ... 0.100 in a short period of time - no need to overwhelm with reviews) 
2) Keep only one of them whitelisted `bbp-packages.yaml`, unless there is some *obvious* need to add the new one.

If that is correct (@matz-e, @pramodk), #742 can go in, because it satisfies both conditions.  We'll try not to have PRs for `0.0.6.....0.0.100` in the next couple weeks.

**Comment by matz-e** [comment]
@mgeplf correct. Note that all versions that were whitelisted within a month will show up for that `archive`, which may create confusion for users. That's the main reason for not trying to push too many versions.

That being said, if you start a draft PR, I think it should still get build and provide modules for testing, with no restrictions on how much you want to test for deployment.

**Comment by pramodk** [comment]
yes!

As Matthias said, if we change version in [bbp-packages.yml](https://github.com/BlueBrain/spack/blob/6f214ce811c1e6fd1b553530296946f5d4f6afe6/deploy/packages/bbp-packages.yaml#L41), then it install new version and create module for this.

Another reason we "try" to accumulate releases/versions  is the HBP deployment on external machine where our deployment cycle is long. So if user except "similar" stack on Juelich/CSCS/Cineca then we deploy less frequently if possible (but this is not applicable for every  bbp package).

**Pull request merged**
