### PR TITLE
cherry-picked spack commit fixing trilinos build

### PR DESCRIPTION
**Pull request by ohm314**
trilinos@develop build now breaks while patching superlu. The reason is that the patch that is applied is now already applied to the tirlinos codebase. This is breaking our zee builds downstream.

for further reference:
https://github.com/spack/spack/pull/9422
https://github.com/trilinos/Trilinos/pull/3209

### CODE REVIEW

**Review by matz-e — APPROVED** [review]
LGTM

**Comment by matz-e** [comment]
Please retest.

Let's see if the failure was a one-off.

**Comment by ohm314** [comment]
it was one off :)

**Comment by matz-e** [comment]
Please retest.

Configured to wipe the workspace first now.

**Comment by matz-e** [comment]
It's stuck/won't run. Feel free to merge, I think @pramodk is OK with it?

Please retest.

That's going to be one last attempt.

**Review by pramodk — APPROVED** [review]

**Pull request merged**
