### PR TITLE
deployment: ipy* considered harmful.

### PR DESCRIPTION
**Pull request by matz-e**
These packages are best installed by the user. Providing them centrally
makes local upgrades painful.

### CODE REVIEW

**Comment by pramodk** [comment]
@matz-e : I would suggest to announce this type of change so that people won't complaint for silent disappearance of ipy*. Lets get this done tomorrow: https://bbpteam.epfl.ch/project/issues/browse/HELP-10581

**Comment by genric** [comment]
So spack is no longer the preferred way of getting the dependencies? Now we should use `pip`?

**Comment by matz-e** [comment]
> So spack is no longer the preferred way of getting the dependencies? Now we should use `pip`?

You can still depend on `ipython` in regular software. This package is provided to end-users for convenience.

This is purely a *user* level change. For software development/deployment nothing changes.

**Comment by matz-e** [comment]
@pramodk we should get this merged.

**Comment by genric** [comment]
@matz-e could you please explain how do I get my `ipyparallel-6.2.2` after you merge this?
Well, maybe just to give some context: it's not actually me who will be getting that package but the automated workflow which needs that dependency to run tasks in the context of ipyparallel cluster.

**Comment by matz-e** [comment]
> @matz-e could you please explain how do I get my `ipyparallel-6.2.2` after you merge this?
> Well, maybe just to give some context: it's not actually me who will be getting that package but the automated workflow which needs that dependency to run tasks in the context of ipyparallel cluster.

Is your automated workflow in Spack? Then it should depend on `ipyparallel` and get that.

**Comment by genric** [comment]
It used to use nix to bring all the dependencies, so it didn't have to install/cleanup anything during execution. Now the strategic decision was to move to spack, so it uses spack built environment modules to bring the dependencies.
So if you are trying to delegate the support of `ipyparallel` package to us then we would appreciate if we have a time slot to implement/test the new ipyparallel module before you merge this. Thanks.

**Comment by matz-e** [comment]
> So if you are trying to delegate the support of `ipyparallel` package to us then we would appreciate if we have a time slot to implement/test the new ipyparallel module before you merge this. Thanks.

I'll add an `ipyparallel` module here. Do you have a link to sources where you actually use it?

**Comment by matz-e** [comment]
> > So if you are trying to delegate the support of `ipyparallel` package to us then we would appreciate if we have a time slot to implement/test the new ipyparallel module before you merge this. Thanks.
> 
> I'll add an `ipyparallel` module here. Do you have a link to sources where you actually use it?

So this is the current situation:
```
❯ spack dependents py-ipyparallel
py-bluepymm  py-bluepyopt  python-dev
```
Modules containing either of the former two packages will still use `ipyparallel`, and include that in their module. I didn't see any direct mention of `ipyparallel` in `BbpWorkflow`.

Please point me to a piece of code where you are directly calling `ipyparallel`. If there is no such code, I don't think you should be affected by `python-dev` not including `ipyparallel` any longer.

**Comment by pramodk** [comment]
> So spack is no longer the preferred way of getting the dependencies? Now we should use pip?
> It used to use nix to bring all the dependencies, so it didn't have to install/cleanup anything during execution. Now the strategic decision was to move to spack, so it uses spack built environment modules to bring the dependencies.

@matz-e has mentioned this already but just to clarify:

* what is changed : ipy* is being removed from python-dev package (which is equivalent of nix-full)
* why : 
  * python-dev module was created for convenience to put together few packages that commonly used (and to avoid modules) 
  * But, if use load python-dev module and install some packages via pip, pip will install other X number of packages that might overlap with packages installed by python-dev.
  * this has caused issues / confusion because of version mismatch / incompatibles
  * with nix, we attempted to chase every small python package and tried to add into nix/full. this is not possible/scalable.

So to avoid this, idea was to remove ipy* packages from "user module" python-dev. As pip is fully working (unlike nix) and users need to install many packages via pip, we thought we should remove this from this BBP specific package.

> so it uses spack built environment modules to bring the dependencies.

What are we referring here? User provided scripts that depend on `python-dev/0.2` module on BB5? OR, spack package which is depend on `python-dev` package?

Note that if there is a package `X` dependent any `ipy*` package, there is nothing changed by this PR. When you load module `X`, you still get all dependencies including `ipy*`.

**Comment by genric** [comment]
@matz-e we would need a standalone module with `ipyparallel`. This module is dynamically composed with other modules depending on what the actual workflow task is doing. I'll send you the example of the workflow config.

**Comment by pramodk** [comment]
@genric : just to understand: 

> @matz-e we would need a standalone module with ipyparallel. 

were you using python-dev before to get ipyparallel?

**Comment by mgeplf** [comment]
> this has caused issues / confusion because of version mismatch / incompatibles

Could you give an example?

Also, for the future (and it would be helpful in this case too), could you create a blog post or confluence page on how exactly someone is supposed to work around the change.    For instance, the `If you are relying on ipython, please install it locally via pip.` isn't super clear for non-tech people.  Which pip do they use? Do they do it in a virtual environment, do they have to use the `--user` option.

I have been trying to get people to use the deployed modules, so I hope they will still be supported, but they also will need time to keep up with changes like these.

Lastly, I wonder if it would be worth it to create a `py-ipython` module as well, while you're at it.

**Comment by genric** [comment]
Thanks @matz-e !
@pramodk: yes.
@mgeplf for the automated workflow stuff we could hide it behind the workflow tasks, so users even don't have to know what modules/packages they are using. We just need to make sure these are working and uptodate.

**Comment by mgeplf** [comment]
@genric I was talking about people who I recommended to use `ipython` through the module, not `ipyparallel`

**Comment by matz-e** [comment]
> @genric I was talking about people who I recommended to use `ipython` through the module, not `ipyparallel`

The module for `py-ipyparallel` should also include `ipython`.

The point of `python-dev` was not to have a `python-full` environment with everything under the sun included, but more of a bootstrap environment. *Things that need to be compiled etc.*. Do we want to replicate all software needed by everyone? If I need my `py-hipster-beard-evaluation` module, should I just get that? Or should I rather install that locally?

Contrary to `nix`, `module load python-dev; pip install --user hipster-beard-evaluation` should work and not lead to problems down the road.

**Comment by pramodk** [comment]
> > this has caused issues / confusion because of version mismatch / incompatibles

> Could you give an example?

This was all started [here](https://bbpteam.epfl.ch/project/issues/browse/HPCTM-1197).

> Also, for the future (and it would be helpful in this case too), could you create a blog post or confluence page on how exactly someone is supposed to work around the change. For instance, the If you are relying on ipython, please install it locally via pip. isn't super clear for non-tech people. Which pip do they use? Do they do it in a virtual environment, do they have to use the --user option.

I would ask help of you guys to put together this. From HPC side, we rarely use these packages (ipyparallel, ipython, bglibpy, bluepy) and have limited experience with their dependencies and how they are used.

**Comment by mgeplf** [comment]
I'm not trying to compare this to nix; I'm trying to make it easy for non-technical users to be able to use our scientific stack.  Before, I could say, to be able to load bglibpy, do:
```
module load neurodamus-hippocampus py-bglibpy/4.0.17/python3 python-dev/0.2/python3
```
And then they could use `ipython`.  Workflow changes like this take time to adapt to, and it's helpful if they have a model on how to proceed.

> Contrary to nix, module load python-dev; pip install --user hipster-beard-evaluation should work and not lead to problems down the road.

Cool.  The non-technical user doesn't know about `--user`, so they would need to understand that.  In addition, I don't know if ~/.local/bin is on the path, so they wouldn't actually be able to start the application after installing it.

> I would ask help of you guys to put together this. From HPC side, we rarely use these packages (ipyparallel, ipython, bglibpy, bluepy) and have limited experience with their dependencies and how they are used.

Sure, where is this info being placed at the moment?

**Comment by matz-e** [comment]
> The non-technical user doesn't know about --user, so they would need to understand that. In addition, I don't know if ~/.local/bin is on the path, so they wouldn't actually be able to start the application after installing it.

Pip gives the following error message:
```
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/pip-19.2.1.dist-info'
Consider using the `--user` option or check the permissions.
```
That's pretty clear in my opinion.

I guess there's the general question of what should be expected out of "users". Once you `ssh` into things, I think there's some benefit to knowing your tools.

**Comment by mgeplf** [comment]
So is the official position that people should use pip to do `--user` installs for python software?

I worry that people will then get these split installations where part of their dependencies (including python wheels, so binary ones that have API requirements) are coming locally and some from `spack`.  Explaining which should come from what - to a non-technical user - sounds quite difficult.

I think the thread above from Taylor is instructive: he has a set of dependencies that he needs filled, and has tried to solve the problem by loading modules and using a virtualenv.  This resulted in the sort of split installation I mentioned above.  He's one of the more technical users we have, and if he's getting into these positions, I doubt we can expect people with less expertise to not run into similar or even more complicated problems.

**Comment by matz-e** [comment]
> So is the official position that people should use pip to do `--user` installs for python software?

I think we should rather define the scope of the deployment: provide *our software stack* ready to use on BB5, which involves more modern compilers and an MPI stack that does not ship with vanilla RedHat. We also provide some convenience utilities, but not everything under the sun.

That latter part will mean that we would be responsible for updates and management of way more packages than we have capacity for. I think it's reasonable to provide the hard-to-compile software (including python modules, so that things play nicely together), and leave the rest up to the user.

For some weird reason, we added an emacs module for a power-user (why else would one need a modern emacs?). I think such things should be more of a user responsibility. I have my own ripgrep, neovim, fzf…

> I worry that people will then get these split installations where part of their dependencies (including python wheels, so binary ones that have API requirements) are coming locally and some from `spack`. Explaining which should come from what - to a non-technical user - sounds quite difficult.

Python dependency management is messy. That's probably why every other language did it differently. I think that our inclusion policy for central deployment of a package should be one of:

- it is used by our software, tools, or deployment/CI
- it is hard for the user to compile (most Python packages probably run under this)

Is it unreasonable to ask users to first install packages in a virtualenv? We can evaluate stuff that fails.

> I think the thread above from Taylor is instructive:

Did I miss that (since you mention above)?

> he has a set of dependencies that he needs filled, and has tried to solve the problem by loading modules and using a virtualenv. This resulted in the sort of split installation I mentioned above. He's one of the more technical users we have, and if he's getting into these positions, I doubt we can expect people with less expertise to not run into similar or even more complicated problems.

How does this work when folks use their workstations? Is there a mix of virtualenv, `~/.local`, and system packages? This is a similar situation. I doubt that the need to assist users will ever go away, but providing modules for every little requirement will overload our capacities. Wouldn't it be better to teach how to fish than handing out fish?

**Comment by pramodk** [comment]
Two things are (more) clear to me:
* we definitely need discussion for changes like this
* we (from hpc) don't have complete picture of how packages (like python-dev, pip, ipy*) are being used inside different workflows (scientists, NSE team etc)

I see both points : usability for scientists vs. practicality to maintain "everything". As there are several facets to it and this is quite important, I propose to meet for 30 minutes discussion (@matz-e @pramodk @wizmer @genric @genric).

I am glad that Mathias sent the message via status page and caught people's attention. By the way, deployment-team member from each team is supposed to keep eye here so that everyone understand the impact and we don't merge things `too fast`. In the future we will tag you guys explicitly on such PRs (including @wizmer)

**Comment by mgeplf** [comment]
@matz-e 
> We also provide some convenience utilities, but not everything under the sun. [...] That latter part will mean that we would be responsible for updates and management of way more packages than we have capacity for.

That makes sense to me.  I'm very much aware that the universe of packages is huge, and people try lots of things out.  I'm happy that spack interops better with virtualenvs (although I haven't really battle tested it enough for find the weird cases yet) then what we had previously.

Maybe one of the discussion items in either the meeting Pramod proposed or deployment team (which I think would be better a better place) should be to scope the mandate so it's clear what is a candidate for spack, and what the support mechanisms are.

> Is it unreasonable to ask users to first install packages in a virtualenv?  We can evaluate stuff that fails.

I hope not, because that has been my primary suggestion over the years.  In my experience, getting feedback on what is failing is hard, though, and people tend to find 'workarounds' that make things much more complicated to debug later.

> Did I miss that (since you mention above)?

Pramod's [comment ](https://github.com/BlueBrain/spack/pull/433#issuecomment-514614729) 'It all started here'

> How does this work when folks use their workstations? Is there a mix of virtualenv, ~/.local, and system packages? This is a similar situation.

It's similar, but there are two major differences: 
* There isn't 'module avail' for people to find software, and then have custom `$PYTHONPATH` that is providing some of the packages, and others from the venv.
* Unless someone does `--system-site-packages` (which is discouraged), the venv should be 'self consistent' with packages and versions that don't conflict.  This is related to the above, an the `$PYTHONPATH` being pretty much empty.

> I doubt that the need to assist users will ever go away, but providing modules for every little requirement will overload our capacities. Wouldn't it be better to teach how to fish than handing out fish?

For sure, but the documentation I suggested above is necessary for this - we are also overloaded on our team, so having a resource that is co-maintained would be helpful.  Then the challenge is to get people to read the docs...

@pramodk 
> Two things are (more) clear to me: ...

I think that's good a summary.  Having a face to face is a good idea.  Let me know when it's happening, and I'll be there.

> I am glad that Mathias sent the message via status page and caught people's attention. 

Completely agree - more communication is important, and I hope it will continue.  Thanks also for responding in this thread, it's appreciated.

**Comment by genric** [comment]
I think I'm changing my mind :)
I'm good with removing `py-ipykernel` and `py-ipyparallel`. Standalone module for `py-ipyparallel` should be ok for me.
Keep the `py-ipython` please.

**Comment by matz-e** [comment]
> I think I'm changing my mind :)
> I'm good with removing `py-ipykernel` and `py-ipyparallel`. Standalone module for `py-ipyparallel` should be ok for me.
> Keep the `py-ipython` please.

OK, maybe not all `py-i*` are bad :)

We can keep `py-ipython`, since that is used interactively and a separate module for that does not make that much sense. It's pretty lightweight… to many Apple-wannabees with all that i* stuff, I lobbed them all together.

Are you OK with ditching `py-ipykernel` and `py-ipyparallel` with the separate module then?

**Comment by genric** [comment]
@matz-e: yes, I'm ok with that. @mgeplf what do you think?

**Comment by mgeplf** [comment]
Having ipython is useful, imo.  I can understand that ipyparallel isn't needed (but I'd say the same about spark :))

My main concern is/was to recommend to scientists - whatever is recommended needs to be pretty stable.  I think we should consider making another metapackage for them, with a more complete stack of what they use.

**Comment by mgeplf** [comment]
That's all to say it's good with me...

**Comment by matz-e** [comment]
> Having ipython is useful, imo. I can understand that ipyparallel isn't needed (but I'd say the same about spark :))

Right, that should be purged, too. I'll get my pitchfork

**Comment by genric** [comment]
The `py-ipykernel` and `py-ipyparallel` removal will happen in this PR #476

**Pull request closed without merging**
