### PR TITLE
Avoid HOC_LIBRARY_PATH getting appended with multiple directories

### PR DESCRIPTION
**Pull request by pramodk**

### CODE REVIEW

**Review by jorblancoa — APPROVED** [review]

**Review by matz-e — APPROVED** [review]

**Review by ferdonline — COMMENTED** [review]
Hummm... within sim-model the prepend is actually required in the setup where the user loads both  neurodamus-core and a model (the new/future setup)
I see as a better solution using `set` instead of `prepend` only when it's being issued from neurodamus-model, which is not supposed to be combined

**Comment by pramodk** [comment]
Please retest

**Comment by matz-e** [comment]
Retest this please

**Comment by pramodk** [comment]
> Hummm... within sim-model the prepend is actually required in the setup where the user loads both neurodamus-core and a model (the new/future setup)

@ferdonline : what do you see as a solution? As Matthias pointed out on Slack, there is an issue with the existing modules.

**Comment by matz-e** [comment]
> > Hummm... within sim-model the prepend is actually required in the setup where the user loads both neurodamus-core and a model (the new/future setup)
> 
> @ferdonline : what do you see as a solution? As Matthias pointed out on Slack, there is an issue with the existing modules.

I guess the instructions could be adapted, too.

**Comment by ferdonline** [comment]
The truth is that too many people are used to launch neurodamus with special HOC_PATH/init.hoc. So it’s fine doing like this and maybe never support hoc path with multiple entries

**Review by ferdonline — APPROVED** [review]

**Pull request merged**
