### PR TITLE
bump libsonata to v0.1.8

### PR DESCRIPTION
**Pull request by mgeplf**

### CODE REVIEW

**Review by matz-e — DISMISSED** [review]

**Comment by mgeplf** [comment]
whoa, fast

I enable 'auto merge', but now I'm concerned that it's for all PRs, and not just this one - do you know?

**Comment by matz-e** [comment]
> whoa, fast
> 
> I enable 'auto merge', but now I'm concerned that it's for all PRs, and not just this one - do you know?

In my understanding, should just be per PR. And still require approval.

**Comment by matz-e** [comment]
Missing a `depends_on("nlohmann-json")'…

**Comment by alkino** [comment]
Wait for ? https://github.com/BlueBrain/libsonata/pull/131

Include it as a patch?!? @mgeplf

**Comment by alkino** [comment]
Wait the version 0.1.8, 0.1.7 is not buildable in spack

**Review by matz-e — APPROVED** [review]

**Comment by pramodk** [comment]
retest this please

**Pull request merged**
