### PR TITLE
steps: add version 3.6.0

### PR DESCRIPTION
**Pull request by tristan0x**

### CODE REVIEW

**Comment by tristan0x** [comment]
Deployment fails with error message the `Post-Mortem/Test Modules` job:

```
[2021-03-10T06:44:20.721Z] Scheduling project: hpc.module-testing
[2021-03-10T06:44:36.128Z] Starting building: hpc.module-testing #3247
hpc.module-testing #3247 completed with status FAILURE (propagate: false to ignore)
```

Any chance to have more information about may happened?

**Comment by matz-e** [comment]
See here: https://bbpcode.epfl.ch/ci/blue/organizations/jenkins/hpc.module-testing/detail/hpc.module-testing/3247/pipeline

**Comment by matz-e** [comment]
Retest this please.

Let's see if it's persistent.

**Comment by matz-e** [comment]
Retest this please.

I "reset the Jenkins cache"

**Comment by matz-e** [comment]
#1079 for a potential fix for this mess with `freetype`

**Comment by matz-e** [comment]
Rebase on top of latest `develop`?

**Comment by tristan0x** [comment]
retest this please Jenkins

**Review by matz-e — APPROVED** [review]

**Pull request merged**
