### PR TITLE
spack setup: take CMake special modes into account

### PR DESCRIPTION
**Pull request by tristan0x**
`--build` or `-E` options turn CMake in special modes that do not
allow generator or CMake variables to be specified in command line.

This patch allows one to use `spconfig.py` as a complete replacement for CMake,
with CLion for instance where the build command looks like:

```
/path/to/spconfig.py --build /path/to/cmake/builddir --target all -- -j 4
```

Before this patch, end of `spconfig.py` looked like:

```python
cmd = cmdlist("""
/path/to/real/bin/cmake
    -G
    Unix Makefiles
    -DCMAKE_INSTALL_PREFIX:PATH=/home/tristan0x/stow/spack/gcc-7.3.0/omega-h-develop-3pjs7u
    # ...
""") += sys.argv[1:]

proc = subprocess.Popen(cmd, env=env)
proc.wait()
```

After this patch:

```python
if sys.argv[1:2] in [["--build"], ["-E"]]:
    cmd = ["/path/to/real/bin/cmake"]
else:
    cmd = cmdlist("""
        /path/to/real/bin/cmake
        -G
        Unix Makefiles
        -DCMAKE_INSTALL_PREFIX:PATH=/home/tristan0x/stow/spack/gcc-7.3.0/omega-h-develop-3pjs7u
        # ...
    """)
cmd += sys.argv[1:]

proc = subprocess.Popen(cmd, env=env)
proc.wait()
```

### CODE REVIEW

**Review by matz-e — COMMENTED** [review]
Seems a wee bit brittle to me. What if I use `--build=`? Very clion specific…

**Review by matz-e — CHANGES_REQUESTED** [review]
I would rather see this as an argument to `spack setup`:
```
--bare   generate a <blah> without any CMake arguments
```

**Comment by tristan0x** [comment]
> Seems a wee bit brittle to me. What if I use `--build=`? Very clion specific…

`--build=` is not supported by CMake. It raises a parse error.

**Comment by tristan0x** [comment]
> I would rather see this as an argument to `spack setup`:
> 
> ```
> --bare   generate a <blah> without any CMake arguments
> ```

No, because you need the CMake arguments when you create the build directory.

**Review by matz-e — APPROVED** [review]

**Comment by matz-e** [comment]
Fine. Still not liking it, but not really a blocker IMHO. Again, it would be interesting what upstream says.

**Comment by tristan0x** [comment]
> ill not liking it, but not really a blocker

I will improve the patch and you will like it!

**Comment by tristan0x** [comment]
PLEASE DO NOT MERGE THIS YET

**Comment by tristan0x** [comment]
I slightly updated the patch and the PR description. Ready for a second review @matz-e

**Review by matz-e — APPROVED** [review]
No further complaints from my side.

**Pull request merged**
