### PR TITLE
py-emodel-generalisation: Add intel-oneapi-compilers needed by NEURON 9 to compile mechanisms

### PR DESCRIPTION
**Pull request by eleftherioszisis**

### CODE REVIEW

**Comment by eleftherioszisis** [comment]
@arnaudon if this needs to be added to another package instead of the generalisation, let me know.

**Comment by arnaudon** [comment]
can't this module be loaded along with neuron instead of each other code requiring neuron?

**Comment by eleftherioszisis** [comment]
> can't this module be loaded along with neuron instead of each other code requiring neuron?

I don't know the exact reason for that decision, but I would guess those compilers are not always needed. @matz-e may know

@arnaudon what I would like to know is if you import neuron directly or you are using it through another package. If the latter is the case it would be probably better to add this dependency there.

**Comment by matz-e** [comment]
This is not the way as it rebuilds the Intel compilers.

**Comment by eleftherioszisis** [comment]
> This is not the way as it rebuilds the Intel compilers.

@matz-e, what would be the right way? We want this and other packages that use neuron to work out of the box without the users needing to add other modules. It's not their responsibility to know what this package needs so that it works.

**Comment by arnaudon** [comment]
I use it via bluepyopt, bluecellulab, and maybe I import it once some place

**Comment by matz-e** [comment]
Honestly would be best to fix that in NEURON itself. Or injecting the intel module into the neuron one. But that opens another can of worms.

If you blindly add another module or depend on the compiler like that, that can have other side effects like `LD_LIBRARY_PATH` suddenly being set. And given how carelessly we load modules, I don't have the bandwidth to deal with fallout from things like this.

**Comment by matz-e** [comment]
#2335 fixes this by adding the linker component to `neuron`, thus fixing _everything_ depending on neuron, not just the emodel generalization.

**Comment by pramodk** [comment]
> We want this and other packages that use neuron to work out of the box without the users needing to add other modules. 

I am glad that Matthias has made PR to get previous behavior. But, from the NEURON perspective I want to state if you are going to compile MOD files then we expect users to load the compiler module. NEURON tries to make the usage simple but in non-trivial HPC setups like BB5, loading appropriate modules is a norm rather than an exception (e.g. see [our instructions](https://github.com/BlueBrain/spack/wiki/Piz-Daint-Deployment) for all HBP use cases on many other machines).

>  It's not their responsibility to know what this package needs so that it works.

IMHO, what is important here is that we document this need and make sure everyone is informed that this is how they have to change their job script.

We try to make things as simple as possible (e.g. on BB5) but unfortunately, sometimes we can't keep the same old behavior all the time and hence we expect users to adapt.

**Comment by eleftherioszisis** [comment]
> IMHO, what is important here is that we document this need and make sure everyone is informed that this is how they have to change their job script.

Tools that use NEURON for model-management, etc. should not break depending on whether the compilers are loaded or not. 

There is no alternative way for the tool to work; it has to compile the mod files.

Therefore, either NEURON takes care of it, or somehow the compilers need to be included as a spack dependency for the tool. 

Deploying a broken tool unless the user does X,Y, and Z doesn't sound like a solution IMHO.

**Comment by pramodk** [comment]
> Tools that use NEURON for model-management, etc. should not break depending on whether the compilers are loaded or not.
> There is no alternative way for the tool to work; it has to compile the mod files.

Yes, understand and I am aware. Typical case with the many NEURON based software.

> Therefore, either NEURON takes care of it,

I would be more than happy to take care of this in NEURON if there would be an easy or portable way. No intention to make life complicated for end users 😃 ! But, the problem is that these things are very much machine-dependent and there is no way that a package like NEURON can figure out these things.

> somehow the compilers need to be included as a spack dependency for the tool.

That's we are waiting from Spack to happen but it will take time: https://github.com/orgs/spack/projects/3/views/3 (it's a bit more complicated than just adding a dependency in the package).

> Deploying a broken tool unless the user does X,Y, and Z doesn't sound like a solution IMHO.

Honestly, a `"broken tool"` part is a bit of an exaggeration here. As part of the new release, we just asked to change:

```console
module load neuron
```

to 

```console
module load neuron intel-oneapi-compilers
```

If you are telling me that such a single line change can't be done in job scripts by end users then I have to disagree here.

Again, we are trying to make things easy wherever possible and wherever we can provided that there is a time 😃!

**Comment by eleftherioszisis** [comment]
> If you are telling me that such a single line change can't be done in job scripts by end users then I have to disagree here.

It's not about being difficult, but that the users that use a downstream tool will need to know its internals to reason about what is missing.

In the end, this is what I am loading at the moment, but to add that easy-to-include module, I had to reach the conclusion that NEURON 9 module is functionally different than its predecessors, talk with you guys, and then learn those compilers have been removed.

I neither use NEURON directly nor do I know its internals. However, I needed to to make the emodel-generalisation work.

I understand that you have good reasons to separate them. However, it is not fair to expect everyone to know how NEURON works to execute tools/workflows/pipelines that might use it somewhere instead of having tools that are self-contained and functional. 

Thanks for the link for the compilers as dependencies. It would indeed be cool if we could specify them only for the tools that need them.

**Comment by arnaudon** [comment]
in a way, pramod is correct the issue is not to use neuron, but to compile mechs only, and as there is `compile` in `compile mechs`, its never simple

**Comment by pramodk** [comment]
>  had to reach the conclusion that NEURON 9 module is functionally different than its predecessors

Just a bit of correction here: it's not about NEURON 8 vs 9. It's about the new Spack deployment changes. We have been deploying and using NEURON 9 for the last one year already.

> 1. but that the users that use a downstream tool will need to know its internals to reason about what is missing.
> 2. I had to reach the conclusion that NEURON 9 module is functionally different than its predecessors, talk with you guys, and then learn those compilers have been removed.
> 3. it is not fair to expect everyone to know how NEURON works to execute tools/workflows/pipelines that might use it somewhere instead of having tools that are self-contained and functional.

All these 3 points you mentioned are still pointing to what I said in the first comment: if one would have clearly specified something like `"All software that directly or indirectly using NEURON now on requires loading XX module on BB5"` then I it's pretty straightforward and would have avoided any confusion.

I don't mean to be nit-picky, and usually won't jump to these discussions at length :smiley:. I was trying to grasp the key arguments and the significance of the underlying issue (which puzzled me).

We all share the expectation and desire for things to run smoothly "out of the box." And then we enter the practical world...!

**Pull request closed without merging**
