### PR TITLE
add simwriter

### PR DESCRIPTION
**Pull request by genric**
Add Simwriter and its dependencies.

### CODE REVIEW

**Comment by matz-e** [comment]
OK to test

**Review by matz-e — APPROVED** [review]
Did we somehow not have the OpenJDK package before? Does that come from upstream?

**Comment by genric** [comment]
> Did we somehow not have the OpenJDK package before? Does that come from upstream?

I was not able to find one, so added this one: https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/openjdk/package.py

**Comment by matz-e** [comment]
> > Did we somehow not have the OpenJDK package before? Does that come from upstream?
> 
> I was not able to find one, so added this one: https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/openjdk/package.py

Thanks, just wanted to make sure!

**Pull request merged**
