### PR TITLE
zee: now requires cgal

### PR DESCRIPTION
**Pull request by tristan0x**

### CODE REVIEW

**Review by pramodk — APPROVED** [review]

**Comment by pramodk** [comment]
Ahh, CI is failing though

**Comment by tristan0x** [comment]
> Ahh, CI is failing though

The issue is weird, `py-ipython` already depends on `py-backcall`.

**Comment by tristan0x** [comment]
On my mac
```
py-ipykernel@5.1.1%clang@9.0.1 arch=darwin-catalina-skylake
    ^py-ipython@7.4.0%clang@9.0.1 arch=darwin-catalina-skylake
        ^py-appnope@0.1.0%clang@9.0.1 arch=darwin-catalina-skylake
            ^python@3.7.7%clang@9.0.1+bz2+ctypes+dbm+lzma~nis~optimizations patches=210df3f28cde02a8135b58cc4168e70ab91dbf9097359d05938f1e2843875e57 +pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4~uuid+zlib arch=darwin-catalina-skylake
        ^py-backcall@0.1.0%clang@9.0.1 arch=darwin-catalina-skylake
```

**Comment by tristan0x** [comment]
retest this please Jenkins

**Review by matz-e — APPROVED** [review]
As mentioned elsewhere, we should redeploy `applications` to get rid of the bogus installation of `ipython` that's missing `backtrace` in the databas…

**Pull request merged**
