### PR TITLE
Removing sonata variant not used

### PR DESCRIPTION
**Pull request by ferdonline**
Sonata is now a mandatory dependency of synapsetool

### CODE REVIEW

**Review by matz-e — APPROVED** [review]
I concur

**Comment by ferdonline** [comment]
@pramodk @matz-e I would merge this change in #528. What do you think?

**Comment by pramodk** [comment]
Fine to merge in 528. We can see if we can upgrade neuron to latest release in next deployment.

**Comment by ferdonline** [comment]
Going into #528

**Pull request closed without merging**
