### PR TITLE
New pip version

### PR DESCRIPTION
**Pull request by alkino**

### CODE REVIEW

**Comment by pramodk** [comment]
@alkino : check the error in CI : `KeyError: u'No spec with name py-pip in python-dev@0.2%gcc@6.4.0 `.

See the python-dev package where we have:

```python
    def setup_environment(self, spack_env, run_env):
        deps = ['py-pip', 'py-ipython', 'py-virtualenv', 'py-wheel', 'py-cython', 'py-pyspark',
                'py-ipyparallel']
```
`py-pip` needs to be removed from there as well.

**Review by matz-e — APPROVED** [review]
Fine. How does this change the workflow from a user perspective?

**Comment by alkino** [comment]
He can no more do `pip` commands without be in a virtual env. But who did that?

**Comment by matz-e** [comment]
> He can no more do `pip` commands without be in a virtual env. But who did that?

Hm, I think that may generate some push-back. I do that, too, but I can work around this.

**Pull request merged**
