### PR TITLE
add bbp-workflow

### PR DESCRIPTION
**Pull request by genric**

### CODE REVIEW

**Comment by genric** [comment]
Any ideas why jenkins is failing?

**Review by matz-e — CHANGES_REQUESTED** [review]
`py-widgetsnbextension@3.5.999` fails to fetch. Seems like an inconsistency in the dependencies, somehow.

This PR changes too many packages; Part of the changes will be caught by the merge of the current Spack release. Could we hold off on all this?

E.g., we have `zeromq` that has been renamed to `zmq`, and I would like to avoid having continuous merge conflicts while getting the new deployment ready.

**Comment by genric** [comment]
Yeah :) I was sort of waiting for this mega merge but then decided to do at least partial update from upstream spack develop branch. So most the files in this PR should be from there.
When do you plan to do this mega merge of spack release?

**Comment by genric** [comment]
Well :) you've mentioned zmq:
```
16:21:42  ==> Error: 
16:21:42   ............../jenkins/pulls/881/tmp/tmptcfzaehy/libzmq-4.3.2-hl7flqctly/lib/libzmq.so.5.2.2 
16:21:42  contains string
16:21:42   ............../jenkins/pulls/881/deploy/libraries/2020-07-29 
16:21:42  after replacing it in rpaths.
16:21:42  Package should not be relocated.
```

**Comment by matz-e** [comment]
> Well :) you've mentioned zmq:
> 
> ```
> 16:21:42  ==> Error: 
> 16:21:42   ............../jenkins/pulls/881/tmp/tmptcfzaehy/libzmq-4.3.2-hl7flqctly/lib/libzmq.so.5.2.2 
> 16:21:42  contains string
> 16:21:42   ............../jenkins/pulls/881/deploy/libraries/2020-07-29 
> 16:21:42  after replacing it in rpaths.
> 16:21:42  Package should not be relocated.
> ```

Yeah… there's weird stuff going on with it. If you really want this to go in, `zeromq` and the Python package should be purged from all places. In the end, it's got some potential to mess with the merge, though

**Comment by genric** [comment]
I can cleanup `zeromq` but why `python`? That would be massive...

**Comment by matz-e** [comment]
> I can cleanup `zeromq` but why `python`? That would be massive...

`py-zeromq`, not Python itself. Sorry, was ambiguous there :)

**Comment by genric** [comment]
There are no references to `zeromq` in the PR except in `deploy_simstack.sh` files. But jenkins still complains:
```
13:11:55  -- linux-rhel7-x86_64 / intel@19.0.4 ----------------------------
13:11:55  dlfjex7 libsodium@1.0.17
13:11:55  mzfiusk libzmq@4.3.2+libsodium
13:11:55  nsr6km2 pkg-config@0.29.2+internal_glib
13:11:55  msncwce zeromq@4.3.2+libsodium
13:11:55  ### 13:11:55 gathering specs
13:12:34  ### 13:12:33 no specs to install?
13:12:38  ==> Regenerating tcl module files
13:12:38  ### 13:12:38 augmenting packages.yaml
13:12:39  ==> Error: Package 'zeromq' not found.
[Pipeline] }
```
Any ideas? Maybe it caches something?

**Comment by genric** [comment]
@pramodk, any chance somebody could have a look at this?

**Comment by genric** [comment]
Ping?

**Comment by matz-e** [comment]
> This PR changes too many packages; Part of the changes will be caught by the merge of the current Spack release. Could we hold off on all this?

**Comment by genric** [comment]
I would prefer for this to go in because currently instead of using bbp-workflow people have to create and keep updated their virtual envs(this is also not helping with usability at all and I already had multiple support requests because of that...)

**Comment by genric** [comment]
Still same error:
```
17:28:51  ### 17:28:51 augmenting packages.yaml
17:28:53  ==> Warning: python package not activated, skipping: snakemake@5.10.0
17:28:53  ==> Warning: python package not activated, skipping: snakemake@5.10.0
17:28:53  ==> Warning: python package not activated, skipping: snakemake@5.6.0
17:28:53  ==> Warning: python package not activated, skipping: snakemake@5.10.0
17:28:53  ==> Warning: python package not activated, skipping: snakemake@5.10.0
17:28:53  ==> Error: Package 'zeromq' not found.
```
have no idea what is this package augmentation with non-existing packages...

**Comment by jdcourcol** [comment]
@pramodk @matz-e , can we get that in ? I mean this is open since July..

**Comment by matz-e** [comment]
> @pramodk @matz-e , can we get that in ? I mean this is open since July..

Once the CI passes. Less package updates would help. Sorry, I'm lacking a bit of bandwidth for this.

**Comment by pramodk** [comment]
As Matthias said, there are two issues here:

* this has PR has fulled large number of changes from upstream : https://github.com/BlueBrain/spack/pull/881/files. Looking at the diff, it's difficult to find out the impact of this on other deployment.
* CI is still failing

We thought best would be to merge this with new deployment. As we are now close for a new release (matter of ~week), we can wait a bit and then rebase this PR.

**Comment by genric** [comment]
I'd be happy to fix the CI if you could explain what this package.yaml augmentation is... or we can wait one more week I guess...

**Comment by matz-e** [comment]
I think one of the CI issues is that it does not handle the renaming of ZeroMQ very well. So that would actually have to be reverted, which I think will trim down this PR a bit.

**Comment by pramodk** [comment]
I am worried about zeromq and it certainly need careful review.
You can see [this discussion](https://github.com/zeromq/libzmq/issues/3313#issuecomment-604875058) where they are not even bothering to reopen the issue even multiple people have reported the errors.

**Comment by genric** [comment]
So if I understood correctly we'll have to stick to the old zmq?
Unfortunately this is probably the minimal set of deps, as bbp-workflow depends on the new versions from the upstream and they, in turn, depend on renamed zmq.

**Pull request closed without merging**
