### PR TITLE
py-bbp-workflow: bump

### PR DESCRIPTION
**Pull request by genric**
and some stuff from upstream

### CODE REVIEW

**Review by matz-e — COMMENTED** [review]
We're about to merge `upstream`, too. @heerener this may give us some additional conflicts, the packages here may also be newer than 0.19

**Comment by genric** [comment]
@arnaudon any ideas what happened to `BPE2` branch?
https://bbpgitlab.epfl.ch/hpc/spack/-/jobs/562713#L2506

**Comment by matz-e** [comment]
So... this then depends on #1842, which depends on the new deployment. Hopefully ready next week...

**Review by matz-e — DISMISSED** [review]
@heerener opinions?

**Comment by matz-e** [comment]
Ah, and I think this needs a rebase.

**Comment by heerener** [comment]
I've run the cleanup job and triggered a retry on the failed pipeline - let's see whether GitLab gets informed about the result...

**Review by heerener — DISMISSED** [review]

**Review by matz-e — APPROVED** [review]

**Pull request merged**
