### PR TITLE
fix dependency of py-sonata-network-reduction@0.0.9

### PR DESCRIPTION
**Pull request by asanin-epfl**
Will it change the dependency this way or do I need to release a new version of py-sonata-network-reduction?

### CODE REVIEW

**Comment by tomdele** [comment]
I would say this is enough but I never did it. So lets wait on @genric for this one.

**Comment by tomdele** [comment]
You need to update bluepysnap version in py-bluepysnap also

**Comment by asanin-epfl** [comment]
Thank you, completely forgot.

**Comment by matz-e** [comment]
If you update the dependency tree, the software will be rebuild.

**Review by matz-e — APPROVED** [review]

**Review by genric — APPROVED** [review]

**Pull request merged**
