### PR TITLE
snakemake: fix dependencies

### PR DESCRIPTION
**Pull request by matz-e**
Closes #783.

### CODE REVIEW

**Review by mgeplf — APPROVED** [review]
I didn't try and build/run it this time, I asusme you did?

**Comment by matz-e** [comment]
I actually ran the `@develop` version for COVID-19… let me check the "real" module, and then I'll merge.

**Comment by mgeplf** [comment]
Thanks.

What cool new features are you using that needs a newer version?

**Comment by matz-e** [comment]
> Thanks.
> 
> What cool new features are you using that needs a newer version?

None, I forgot how this got into here. I was sanitizing the output a little to have a better idea what's going on under the hood, and that was easiest to do on `master`. The resource management of :snake:make should actually be improved for this, but don't quote me on that. We're running on top of SLURM, that's its own mess.

**Pull request merged**
