### PR TITLE
eigen: Fix build with nvhpc

### PR DESCRIPTION
**Pull request by alkino**

### CODE REVIEW

**Review by matz-e — DISMISSED** [review]
Are you going to upstream this?

**Comment by alkino** [comment]
Yes, I will try ;)

**Comment by alkino** [comment]
https://gitlab.com/libeigen/eigen/-/merge_requests/517 <= Here

**Comment by matz-e** [comment]
Thanks! Meant upstream Spack, actually :sweat_smile:

**Comment by alkino** [comment]
https://gitlab.com/libeigen/eigen/-/commit/001a57519a7aa909d3bf0cd8c6ec8a9cd19d9c70

Patch have been merged upstream

**Comment by alkino** [comment]
https://github.com/spack/spack/pull/24253

Patch is now as a PR in upstream spack

**Comment by matz-e** [comment]
Retest this please

**Comment by alkino** [comment]
Patch merged upstream

**Comment by matz-e** [comment]
Rebase on top of current `develop`, please

**Review by pramodk — APPROVED** [review]
@alkino : this is ready to go?

**Review by matz-e — APPROVED** [review]

**Pull request merged**
