### PR TITLE
create py-minis-validation package

### PR DESCRIPTION
**Pull request by asanin-epfl**

### CODE REVIEW

**Comment by pramodk** [comment]
(as tagged WIP, I converted it to draft)

**Review by matz-e — DISMISSED** [review]

**Comment by asanin-epfl** [comment]
Checked the PR according to our FAQ and there were problems with using the loaded module. Investigating.

**Review by matz-e — DISMISSED** [review]

**Comment by asanin-epfl** [comment]
@matz-e I am sorry for this endless pushing. I will mention you here when it is ready for merging. You can mark it as a draft again.

**Comment by asanin-epfl** [comment]
retest this please

**Comment by asanin-epfl** [comment]
It's good to go. I verified, module works on the PR. @matz-e please review

**Review by matz-e — APPROVED** [review]

**Comment by asanin-epfl** [comment]
thank you so much!

**Pull request merged**
