### PR TITLE
Update mpfr 4.0.2 checksum

### PR DESCRIPTION
**Pull request by cattabiani**
mpfr 4.0.2 was updated and the checksum changed

### CODE REVIEW

**Review by iomaganaris — APPROVED** [review]
LGTM
I also tested it in BB5 and locally
There is just some issue with the `nmodl` package? Maybe the branch should be rebased to `develop`?

**Review by matz-e — APPROVED** [review]

**Comment by pramodk** [comment]
@cattabiani : should be merged?

**Comment by matz-e** [comment]
You have the honor of pushing the button.

**Comment by ferdonline** [comment]
@cattabiani merge or not to merge... 🤔

**Pull request merged**
