### PR TITLE
add new package py-bluepy-snap for bluepysnap

### PR DESCRIPTION
**Pull request by asanin-epfl**

### CODE REVIEW

**Review by matz-e — COMMENTED** [review]
Rebase please to fix some of the tests on the repository. @alkino just fixed quite a few things today.

**Review by matz-e — COMMENTED** [review]
Generic question: to be in line with `pip install`, shouldn't we call this `py-bluepysnap`?

**Comment by tomdele** [comment]
yes indeed `py-bluepysnap` would be better.

**Review by matz-e — APPROVED** [review]
LGTM, thank you!

**Comment by asanin-epfl** [comment]
thank you!

**Pull request merged**
