### PR TITLE
py-pyspark: fix dependencies.

### PR DESCRIPTION
**Pull request by matz-e**

### CODE REVIEW

**Review by jorblancoa — APPROVED** [review]

**Review by st4rl3ss — APPROVED** [review]
LGTM

**Comment by matz-e** [comment]
> LGTM

Should have filled in some details, but this should fix the modules…

**Comment by matz-e** [comment]
Please retest

**Comment by matz-e** [comment]
Retest this please

**Comment by matz-e** [comment]
Retest this please

**Pull request merged**
