### PR TITLE
Adding MorphIO 3.0.2

### PR DESCRIPTION
**Pull request by tomdele**
This new version does not add dependencies that s why the changes are so small for a major bump.

### CODE REVIEW

**Comment by tomdele** [comment]
@GianlucaFicarelli, @matz-e did you experience the same problem before ? 
https://bbpcode.epfl.ch/ci/job/hpc.module-testing/3374/console

At the first glance, it does not seem to fail due to my changes.

**Comment by matz-e** [comment]
Yeah, this is an unrelated failure due to some simulator updates. I've pinged our simulator team about this already.

**Comment by tomdele** [comment]
Thanks @matz-e  for the information. Is there something I should do or should I just wait ?

**Comment by matz-e** [comment]
Retest this please

Let's see if the final tests work now.

**Review by matz-e — APPROVED** [review]
Sorry, should have approved when I retriggered :thinking:

**Comment by tomdele** [comment]
No worries.
Thank you @matz-e  !

**Pull request merged**
