### PR TITLE
libsonata-report: Add support for synapse reports

### PR DESCRIPTION
**Pull request by jorblancoa**

### CODE REVIEW

**Comment by jorblancoa** [comment]
retest this please jenkins

**Comment by jorblancoa** [comment]
retest this jenkins please

**Comment by jorblancoa** [comment]
retest this please

**Comment by jorblancoa** [comment]
retest this jenkins please

**Comment by jorblancoa** [comment]
retest this jenkins please

**Comment by jorblancoa** [comment]
retest this please

**Review by matz-e — APPROVED** [review]

**Pull request merged**
