### PR TITLE
python-dev: add more utilities and bump

### PR DESCRIPTION
**Pull request by matz-e**

### CODE REVIEW

**Comment by pramodk** [comment]
don't remember myself : how previous module 0.3 is excluded?

**Comment by matz-e** [comment]
> don't remember myself : how previous module 0.3 is excluded?

What do you mean?

**Comment by pramodk** [comment]
Was referring to module `0.3` vs `0.4`. With `0.4`, module for 0.3 shouldn't be generated.

**Comment by matz-e** [comment]
Yes… I've added a bit of software to it, and now I've also generalized the treatment of the `bin` directories added to `$PATH`. Thus the bump… 0.3 with the old path should be around 'til the end of the month, still.

**Review by pramodk — APPROVED** [review]

**Pull request merged**
