### PR TITLE
Download ISPC binary files

### PR DESCRIPTION
**Pull request by jorblancoa**

### CODE REVIEW

**Review by cattabiani — APPROVED** [review]
LGTM! I am not sure about other applications. However, with cvf ispc has been installed and tested. Everything works like a charm

**Comment by matz-e** [comment]
But why?

**Comment by cattabiani** [comment]
the code remained stuck at:
```
==> llvm: Executing phase: 'cmake'
==> llvm: Executing phase: 'build'
```
for at least 2h; no error.

**Comment by pramodk** [comment]
For the all practical usage of ISPC (on desktop as well as cluster), no one wants to build LLVM from source to get ISPC binary. Better to just fetch pre-built binary for Windows, Linux or Mac.

**Pull request merged**
