### PR TITLE
Deduplicate syn{,apse-}tool.

### LINKED ISSUE #40: Syntool and SynapseTool build the same software
This should be unified. The URL in the git repo clearly says `synapse-tool` ;)

### PR DESCRIPTION
**Pull request by matz-e**
Fixes #40.

### CODE REVIEW

**Review by tristan0x — COMMENTED** [review]
Aren't `-DLIBHDF5_ROOT` and `-DBOOST_ROOT` variables required in syntool?

**Comment by matz-e** [comment]
If you're OK with the name `synapse-tool`, I can also adjust that package and keep it. I would prefer names that match the git repositories to have a clear association.

I trusted Pramod with the root stuff, `synapse-tool` was a build that works for me.

**Comment by pramodk** [comment]
> Aren't -DLIBHDF5_ROOT and -DBOOST_ROOT variables required in syntool?

@tristan0x : All dependencies are added to `CMAKE_PREFIX_PATH` and hence CMake find_package should find those. (but one could also add those explicitly)

**Review by pramodk — APPROVED** [review]
LGTM

**Comment by matz-e** [comment]
> >     Aren't -DLIBHDF5_ROOT and -DBOOST_ROOT variables required in syntool?
> 
> @tristan0x : All dependencies are added to CMAKE_PREFIX_PATH and hence CMake find_package should find those. (but one could also add those explicitly)

FWIW, I don't think this works reliably with the system installed packages from `packages.yaml`.

**Pull request closed without merging**
