### PR TITLE
Adds support for Caliper variant in CoreNEURON

### PR DESCRIPTION
**Pull request by sergiorg-hpc**

### CODE REVIEW

**Comment by sergiorg-hpc** [comment]
This update depends on a fix in CoreNEURON, do not merge one without the other one:
https://github.com/BlueBrain/CoreNeuron/pull/545

**Comment by sergiorg-hpc** [comment]
@pramodk / @iomaganaris One question, should we also update the Caliper recipe from upstream? I just checked and it changed quite a bit, including a new `CudaPackage` class inheritance that I'm not sure our Spack supports.

**Comment by pramodk** [comment]
Recipe from upstream could be updated if it's compatible with our Spack. Otherwise you can leave it for later.

**Comment by sergiorg-hpc** [comment]
retest this please

**Comment by sergiorg-hpc** [comment]
> Recipe from upstream could be updated if it's compatible with our Spack. Otherwise you can leave it for later.

Done.

**Review by iomaganaris — DISMISSED** [review]

**Comment by sergiorg-hpc** [comment]
My apologies for adding you to the review, @matz-e. I just want to ensure that the use of `conflicts()` with Caliper is correct, to force people to manually specify `~caliper` in older versions. From now on, by default, Caliper is always enabled.

**Comment by sergiorg-hpc** [comment]
please retest this

**Review by matz-e — APPROVED** [review]
Looks legit from my side.

**Comment by sergiorg-hpc** [comment]
please retest this

**Review by pramodk — APPROVED** [review]
LGTM

**Pull request merged**
