### PR TITLE
deploy: add GCC to the NVHPC module definition

### PR DESCRIPTION
**Pull request by matz-e**

### CODE REVIEW

**Comment by matz-e** [comment]
@pramodk:
```
- compiler:
    spec: nvhpc@21.2
    modules: [/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/pulls/1323/deploy/externals/2021-10-08/modules/tcl/linux-rhel7-x86_64/nvhpc/21.2,/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/pulls/1323/deploy/compilers/2021-10-08/modules/tcl/linux-rhel7-x86_64/gcc/9.3.0]
    paths:
      cc: /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/externals/2021-01-06/linux-rhel7-x86_64/gcc-9.3.0/nvhpc-21.2-67d2qp/Linux_x86_64/21.2/compilers/b
in/nvc
      cxx: /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/externals/2021-01-06/linux-rhel7-x86_64/gcc-9.3.0/nvhpc-21.2-67d2qp/Linux_x86_64/21.2/compilers/
bin/nvc++
      f77: /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/externals/2021-01-06/linux-rhel7-x86_64/gcc-9.3.0/nvhpc-21.2-67d2qp/Linux_x86_64/21.2/compilers/
bin/nvfortran
      fc: /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/externals/2021-01-06/linux-rhel7-x86_64/gcc-9.3.0/nvhpc-21.2-67d2qp/Linux_x86_64/21.2/compilers/b
in/nvfortran
    flags: {}
    operating_system: rhel7
    target: x86_64
    environment: {}
    extra_rpaths: []
```

better?

**Comment by pramodk** [comment]
we need gcc before nvhpc because they set CC, CXX env vars?

**Comment by matz-e** [comment]
There you go…

Then what do you need the GCC module for?

Edit: nevermind, I see that now…

**Comment by matz-e** [comment]
Retest this please

**Comment by matz-e** [comment]
Retest this please

**Review by olupton — DISMISSED** [review]
Seems reasonable to me.

**Comment by matz-e** [comment]
Ifff only our cluster would function properly… :(

**Review by olupton — APPROVED** [review]

**Pull request merged**
