### PR TITLE
py-currentscape, py-morph-tool, py-region-grower: simplify dependencies

### PR DESCRIPTION
**Pull request by matz-e**

### CODE REVIEW

**Review by ohm314 — DISMISSED** [review]
lgtm

**Review by GianlucaFicarelli — COMMENTED** [review]
LGTM as well, I just wonder if `+neuron` should be added (or not) to `py-morph-tool` in https://github.com/BlueBrain/spack/blob/91c625a75b8ad0f69a8e83d2f3e3fd469c5d1691/bluebrain/deployment/environments/applications_nse.yaml#L62

**Comment by matz-e** [comment]
> LGTM as well, I just wonder if `+neuron` should be added (or not) to `py-morph-tool` in
> 
> https://github.com/BlueBrain/spack/blob/91c625a75b8ad0f69a8e83d2f3e3fd469c5d1691/bluebrain/deployment/environments/applications_nse.yaml#L62

Good question. @GianlucaFicarelli do you know who could answer that?

**Comment by GianlucaFicarelli** [comment]
> Good question. @GianlucaFicarelli do you know who could answer that?

I see that bluepyopt is optionally used (among other places) when the CLI command `morph-tool convert` is called, here: https://github.com/BlueBrain/morph-tool/blob/43a8fee9644ab96766937b98b65b1be0515e67e4/morph_tool/converter.py#L296-L306

so it seems safer to keep the bluepyopt dependency when the module `py-morph-tool` is loaded explicitly with `module load`.

However, I see that bluepyopt was made optional in https://github.com/BlueBrain/morph-tool/pull/63
@mgeplf do you know more about it, and if the bluepyopt dependency should be kept or not, when building the spack module alone? (used when calling `module load py-morph-tool`)

**Comment by mgeplf** [comment]
> However, I see that bluepyopt was made optional in https://github.com/BlueBrain/morph-tool/pull/63
@mgeplf do you know more about it, and if the bluepyopt dependency should be kept or not, when building the spack module alone? (used when calling module load py-morph-tool)

I think it should be kept, so that the functionality contained in the `extras works directly.

**Comment by matz-e** [comment]
> > However, I see that bluepyopt was made optional in [BlueBrain/morph-tool#63](https://github.com/BlueBrain/morph-tool/pull/63)
> > @mgeplf do you know more about it, and if the bluepyopt dependency should be kept or not, when building the spack module alone? (used when calling module load py-morph-tool)
> 
> I think it should be kept, so that the functionality contained in the `extras works directly.

Changed as requested.

**Review by GianlucaFicarelli — APPROVED** [review]

**Pull request merged**
