### PR TITLE
bluepysnap dependencies update

### PR DESCRIPTION
**Pull request by tomdele**

### CODE REVIEW

**Review by matz-e — DISMISSED** [review]

**Comment by tomdele** [comment]
I promise one day I will make a working spack PR ...

**Comment by matz-e** [comment]
That's a weird failure in the test log.

Retest this please

**Comment by tomdele** [comment]
Yeah I was a bit lost looking at the logs : https://bbpcode.epfl.ch/ci/job/hpc.spack-deployment.pull-requests/1507/console

I was about to ask you about the error part : 
```
10:58:02  /usr/bin/tar: Unexpected EOF in archive
10:58:02  /usr/bin/tar: Error is not recoverable: exiting now
10:58:02  ==> Using cached archive: /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/pulls/1033/deploy/applications/2021-02-03/.cache/_source-cache/git//nse/bluepy/bluepy-v2.0.0.tar.gz
10:58:02  ==> Warning: Fetching from mirror without a checksum!
10:58:02    This package is normally checked out from a version control system, but it has been archived on a spack mirror.  This means we cannot know a checksum for the tarball in advance. Be sure that your connection to this mirror is secure!
10:58:02  ==> Error: ProcessError: Command exited with status 2:
10:58:02      '/usr/bin/tar' '-oxf' '/gpfs/bbp.cscs.ch/ssd/slurmTmpFS/bbprelman/1286195/spack-stage-py-bluepy-2.0.0-l25456ekar3dmjyetjycqbw66hity7a2/bluepy-v2.0.0.tar.gz'
10:58:02  ==> py-bluepy: Executing phase: 'build'
10:58:02  Total 12351 (delta 7002), reused 12351 (delta 7002)
10:58:02  Fetching tags only, you probably meant:
10:58:02    git fetch --tags
10:58:02  ==> py-bluepy: Executing phase: 'install'
10:58:02  ==> Installing py-bluepy-2.0.0-mderrm6ok6en73miz5ww67mn6lsr75cn
10:58:02  ==> No binary for py-bluepy-2.0.0-mderrm6ok6en73miz5ww67mn6lsr75cn found: installing from source
10:58:02  ==> Warning: Skipping build of py-bglibpy-4.4.20-fe6sjc4pthx5mfcev7jwfgvv6rczzxqi since py-bluepy-2.0.0-l25456ekar3dmjyetjycqbw66hity7a2 failed
10:58:02  ==> Error: Failed to install py-bluepy due to InstallError: Install failed for dependency py-bluepy of py-bglibpy
```

**Comment by tomdele** [comment]
Retest this please

**Comment by tomdele** [comment]
We should make a PR at CERN, we found a new quantum system in spack ...

**Comment by tomdele** [comment]
Just for the record: 

I had a weird bug the first time I run 51d3f1f (see : https://bbpcode.epfl.ch/ci/job/hpc.spack-deployment.pull-requests/1513/console):
```
13:53:19  ==> Installing py-bluepy-2.0.0-u7khrdps34c4gdinpfu37ol3upfmucyf
13:53:19  ==> No binary for py-bluepy-2.0.0-u7khrdps34c4gdinpfu37ol3upfmucyf found: installing from source
13:53:19  ==> Warning: Missing a source id for flex@2.5.37
13:53:19  ==> Warning: Missing a source id for flex@2.5.37

13:53:21  
13:53:21  gzip: stdin: decompression OK, trailing garbage ignored
13:53:21  /usr/bin/tar: Child returned status 2
13:53:21  /usr/bin/tar: Error is not recoverable: exiting now
13:53:21  ==> Using cached archive: /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/pulls/1033/deploy/applications/2021-02-03/.cache/_source-cache/git//nse/bluepy/bluepy-v2.0.0.tar.gz
13:53:21  ==> Warning: Fetching from mirror without a checksum!
13:53:21    This package is normally checked out from a version control system, but it has been archived on a spack mirror.  This means we cannot know a checksum for the tarball in advance. Be sure that your connection to this mirror is secure!
13:53:21  ==> Error: ProcessError: Command exited with status 2:
13:53:21      '/usr/bin/tar' '-oxf' '/gpfs/bbp.cscs.ch/ssd/slurmTmpFS/bbprelman/1286422/spack-stage-py-bluepy-2.0.0-u7khrdps34c4gdinpfu37ol3upfmucyf/bluepy-v2.0.0.tar.gz'

13:53:22  ==> Installing py-bluepy-2.0.0-fafoyh3k4pch63dxwuctt2etvsurcnun
13:53:22  ==> No binary for py-bluepy-2.0.0-fafoyh3k4pch63dxwuctt2etvsurcnun found: installing from source
13:53:22  ==> Warning: Skipping build of py-bglibpy-4.4.20-p6q6blpfoyr5bdcrkpeqft6nwrspj4wl since py-bluepy-2.0.0-u7khrdps34c4gdinpfu37ol3upfmucyf failed
13:53:22  ==> Warning: Skipping build of py-sonata-network-reduction-0.1.0-xsp6ovmsvuty4n2et6z7pde4jvv4n55w since py-bglibpy-4.4.20-p6q6blpfoyr5bdcrkpeqft6nwrspj4wl failed
13:53:22  ==> Error: Failed to install py-bluepy due to InstallError: Install failed for dependency py-bluepy of py-sonata-network-reduction
```
And after exploring the different spack packages, I did not find anything bad. So, I just retriggered and it worked.
I have no idea where this comes from.

**Review by matz-e — APPROVED** [review]
Weird… but if it passes…

**Comment by tomdele** [comment]
Thank you @matz-e  !

**Pull request merged**
