### PR TITLE
Bump connectome-tools 0.5.1

### PR DESCRIPTION
**Pull request by GianlucaFicarelli**

### CODE REVIEW

**Comment by GianlucaFicarelli** [comment]
@pramodk any idea why `linux tests / unittests` failed or were cancelled?
`BlueBrain5 Deployment Test Build` was successful.

**Comment by pramodk** [comment]
Can not say for sure. Matthias could have fast answer but he is on vacation.
Is this rebased on top of latest develop? (and I assume you have already tried relaunching once)

**Comment by olupton** [comment]
Could be related to https://github.com/spack/spack/pull/24686 (refers to new python versions, but looks like the CI maybe picks up a new urllib from pypi?) -- probably you are just unlucky that this PR is the first one to run the CI in ~a week.

**Comment by GianlucaFicarelli** [comment]
Thanks @olupton this can be the reason, I see that the tests in the previous PR were using Python 3.6.13, 3.7.10, 3.8.10 while the current one is using 3.6.14, 3.7.11, 3.8.11, and with these versions the fix in that spack PR is needed.

**Review by mgeplf — DISMISSED** [review]
LGTM; can't comment on the CI though

**Comment by olupton** [comment]
If you rebase on `develop` (or merge it in) then https://github.com/BlueBrain/spack/pull/1229 should have fixed the CI

**Comment by GianlucaFicarelli** [comment]
I rebased but there is a different error in https://github.com/BlueBrain/spack/pull/1228/checks?check_run_id=3132554159:
```
________________________ test_list_format_version_json _________________________

    @pytest.mark.maybeslow
    def test_list_format_version_json():
        output = list('--format', 'version_json')
>       assert '  {"name": "cloverleaf3d",' in output
E       assert '  {"name": "cloverleaf3d",' in '[\n  {"name": "3proxy",\n   "latest_version": "0.8.13",\n   "versions": ["0.8.13", "0.8.12", "0.8.11"],\n   "homepage...},\n  {"name": "biobloom",\n   "latest_version": "2.2.0",\n   "versions": ["2.2.0"],\n   "homepage": "https://git\n]\n'

lib/spack/spack/test/cmd/list.py:58: AssertionError

```

**Comment by olupton** [comment]
I had a quick look but couldn't see the underlying cause of that error. I hit retry and it looks happier so far...

**Comment by GianlucaFicarelli** [comment]
> I had a quick look but couldn't see the underlying cause of that error. I hit retry and it looks happier so far...

Thanks, I didn't imagine it could have been a spurious error.

**Review by olupton — APPROVED** [review]

**Pull request merged**
