### PR TITLE
deployment: hook up module tests.

### PR DESCRIPTION
**Pull request by matz-e**
Test module functionality after deployment by triggering a dependent Jenkins plan.

### CODE REVIEW

**Comment by matz-e** [comment]
@pramodk this is some very basic chaining. If the tests for software get more complicated, we'll have to add some logic in here. For now, I think this works. After I get back next week, we can make things more complicated.

**Comment by iomaganaris** [comment]
please retest

**Comment by iomaganaris** [comment]
please retest

**Comment by iomaganaris** [comment]
please retest

**Review by pramodk — APPROVED** [review]

**Pull request merged**
