### PR TITLE
py-sonata-network-reduction@0.0.10

### PR DESCRIPTION
**Pull request by asanin-epfl**

### CODE REVIEW

**Comment by anilbey** [comment]
But the sonata nodes.h5 support is not yet merged to BGLibPy.

**Comment by anilbey** [comment]
I will push that change today.

**Comment by asanin-epfl** [comment]
> But the sonata nodes.h5 support is not yet merged to BGLibPy.

How is that related to this package?

**Comment by anilbey** [comment]
Doesn't BGLibPy need to extract some properties from a nodes.h5 file for this to run?

**Comment by asanin-epfl** [comment]
> Doesn't BGLibPy need to extract some properties from a nodes.h5 file for this to run?

No. I parse `nodes.h5` on my own and use BGLibPy API to instantiate nodes' neurons.

**Comment by anilbey** [comment]
Ok, then it's fine. :+1:

**Review by matz-e — APPROVED** [review]

**Pull request merged**
