### PR TITLE
psp-validation@0.3.0

### PR DESCRIPTION
**Pull request by asanin-epfl**

### CODE REVIEW

**Review by matz-e — APPROVED** [review]

**Comment by asanin-epfl** [comment]
Thank you!

**Comment by asanin-epfl** [comment]
@matz-e The PR was merged yesterday but I still don't see `0.3.0` version in available modules (usually it took a couple of hours to deploy). What could happen? Where should I look for logs?

**Comment by matz-e** [comment]
@asanin-epfl Look at the `hpc.spack-deplyoment` Jenkins™ plan. Not an issue with your changes… I'll look into it

**Comment by asanin-epfl** [comment]
Thank you!

**Pull request merged**
