### PR TITLE
py-bglibpy: set minimal py-bluepy to 2.5.0 #1904

### PR DESCRIPTION
**Pull request by anilbey**
For latest bluepysnap compatibility in #1904

### CODE REVIEW

**Comment by anilbey** [comment]
It is mentioned, no? That's the commit message: `py-bglibpy: set minimal bluepy to 2.5.0 #1904`

**Comment by GianlucaFicarelli** [comment]
Note that `py-bluepy@2.5.0` is not available yet in spack.
It may be simpler to upgrade and fix all the related dependencies in the same PR https://github.com/BlueBrain/spack/pull/1904

**Comment by GianlucaFicarelli** [comment]
> Note that `py-bluepy@2.5.0` is not available yet in spack. It may be simpler to upgrade and fix all the related dependencies in the same PR #1904

I'm going to try to add these changes there

**Comment by anilbey** [comment]
> I'm going to try to add these changes there

Thanks @GianlucaFicarelli !
I'll see to the commit message validator in the meantime.

**Comment by anilbey** [comment]
Commit message validation / validate-commit-messages (pull_request) Successful in 31s  :heavy_check_mark:  Yesss!

**Comment by anilbey** [comment]
The `--force-with-lease` pushes were to re-trigger the commit message validation upon PR title changes. Otherwise it does not get re-triggered.

**Comment by anilbey** [comment]
@GianlucaFicarelli 

> I'm going to try to add these changes there

Should I close this and update these changes there as well?

**Comment by anilbey** [comment]
@GianlucaFicarelli ah thanks ok then I'm closing that one. On bglibpy's side the only change is this `py-bluepy@2.5.0`.

**Pull request closed without merging**
