### PR TITLE
Update TouchDetector to latest version

### PR DESCRIPTION
**Pull request by sergiorg-hpc**

### CODE REVIEW

**Comment by sergiorg-hpc** [comment]
Until the tag has been created on GitLab, this remains as a Draft.

**Comment by sergiorg-hpc** [comment]
please retest

**Comment by sergiorg-hpc** [comment]
please retest jenkins

**Comment by sergiorg-hpc** [comment]
retest this please

**Review by matz-e — APPROVED** [review]

**Pull request merged**
