### PR TITLE
steps: require eigen

### PR DESCRIPTION
**Pull request by cattabiani**
steps: require eigen

### CODE REVIEW

**Comment by cattabiani** [comment]
please retry

**Comment by cattabiani** [comment]
shall I care about package-audits? @matz-e

**Comment by matz-e** [comment]
> shall I care about package-audits? @matz-e

Should be fixed in #1961

**Review by matz-e — COMMENTED** [review]
Rebase on latest develop, please

**Review by matz-e — APPROVED** [review]

**Pull request merged**
