### PR TITLE
Spatial index quaternion

### PR DESCRIPTION
**Pull request by tristan0x**

### CODE REVIEW

**Comment by tristan0x** [comment]
Is this somehow useful for spatial-index @ferdonline ?

**Comment by pramodk** [comment]
@ferdonline  / @st4rl3ss : can you confirm Tristan's question and then we decide to merge this?

**Comment by st4rl3ss** [comment]
This should help solving the issues we're having with gerrit in Spatial Index. If Test Build passes it should be merged.

**Comment by st4rl3ss** [comment]
please retest

**Review by ferdonline — APPROVED** [review]
Thanks @tristan0x, and sorry the delay, I completely overlooked this PR.
Wonder why it fails, but otherwise I'm fine with it

**Comment by st4rl3ss** [comment]
Oh Holy Jenkins, retest this please

**Pull request merged**
