### PR TITLE
Remove old versions of some packages

### PR DESCRIPTION
**Pull request by GianlucaFicarelli**
The removed old packages have been kept originally in https://github.com/BlueBrain/spack/pull/1267
The package placement-algorithm is updated separately in https://github.com/BlueBrain/spack/pull/1399

Other:
- update urls
- update py-bluepyemodel from 0.0.5 to 0.0.8
- verify dependencies

Dependencies based on:

https://bbpgitlab.epfl.ch/cells/bluepyemodel/-/blob/BluePyEModel-v0.0.8/setup.py
https://github.com/BlueBrain/diameter-synthesis/blob/0.2.5/setup.py
https://github.com/BlueBrain/morph-tool/blob/v2.9.0/setup.py
https://bbpgitlab.epfl.ch/nse/morph-validator/-/blob/morph-validator-v0.3.0/setup.py
https://bbpgitlab.epfl.ch/nse/neuroc/-/blob/neuroc-v0.2.8/setup.py
https://github.com/BlueBrain/NeuroM/blob/v3.0.0/setup.py
https://github.com/BlueBrain/NeuroR/blob/v1.4.2/setup.py
https://github.com/BlueBrain/plotly-helper/blob/v0.0.8/setup.py
https://bbpgitlab.epfl.ch/neuromath/region-grower/-/blob/region-grower-v0.3.0/setup.py
https://bbpgitlab.epfl.ch/neuromath/neurots/-/blob/NeuroTS-v2.5.0/setup.py

### CODE REVIEW

**Comment by GianlucaFicarelli** [comment]
Retest this please Jenkins

**Review by matz-e — DISMISSED** [review]

**Comment by matz-e** [comment]
Thanks!

**Comment by GianlucaFicarelli** [comment]
I'm surprised it worked at the first try :D 
I'm adding also @arnaudon to be aware of the update of bluepyemodel from 0.0.5 to 0.0.8 and to know if there is any reason to not update this package (I needed to update it because of the dependency on morph-tool).
And @adrien-berchet for the update of the url of diameter-synthesis from gitlab (archived) to github.

**Review by adrien-berchet — DISMISSED** [review]
LGTM!
Should we tell you when codes are moved to Github? Because we are currently moving several other codes to Github.

**Comment by mgeplf** [comment]
@adrien-berchet > Should we tell you when codes are moved to Github?

Yeah, or, even better, it would be appreciated if you updated spack when new versions are released so we can all share the responsibility.

**Comment by arnaudon** [comment]
Update as much as you want!

**Comment by adrien-berchet** [comment]
> @adrien-berchet > Should we tell you when codes are moved to Github?
> 
> Yeah, or, even better, it would be appreciated if you updated spack when new versions are released so we can all share the responsibility.

Ok, I will try to remember this. We should move NeuroTS (TNS) to Github quite soon so I will update this.

**Review by matz-e — APPROVED** [review]
Excellent, thank you!

**Pull request merged**
