### PR TITLE
fix jupyter notebook

### PR DESCRIPTION
**Pull request by genric**
New versions of tornado break jupyter notebook version 4.

### CODE REVIEW

**Comment by pramodk** [comment]
cc: @jorblancoa 

To solve the issues with bluepyopt, we are also looking at the incompatibilities related to this. See #728.

**Comment by genric** [comment]
> cc: @jorblancoa
> 
> To solve the issues with bluepyopt, we are also looking at the incompatibilities related to this. See #728.

This is exactly what they recommend(downgrade tornado): https://github.com/jupyter/jupyter/issues/334#issuecomment-424226828

**Comment by pramodk** [comment]
> This is exactly what they recommend(downgrade tornado): jupyter/jupyter#334 (comment)

We were also going through all those comments and settled on this [one](https://github.com/jupyter/jupyter/issues/334#issuecomment-38143362). See my stars :D 

So instead of downgrading tornado, we thought it's better to use newer Jupyter client and thats working. Maybe you can test the modules from #728?

Otherwise we can downgrade tornado.

**Comment by genric** [comment]
> > This is exactly what they recommend(downgrade tornado): [jupyter/jupyter#334](https://github.com/jupyter/jupyter/issues/334) (comment)
> 
> We were also going through all those comments and settled on this [one](https://github.com/jupyter/jupyter/issues/334#issuecomment-38143362). See my starts :D
> 
> So instead of downgrading tornado, we thought it's better to use newer Jupyter client and thats working. Maybe you can test the modules from #728?
> 
> Otherwise we can downgrade tornado.

Well, I would prefer to upgrade the whole jupyter(which I was hoping to get for free with mega merge :smile:) Because version 4, is quite bad to say the least...

**Comment by pramodk** [comment]
@genric : can you updates in #545 where we are updating some related packages?

**Comment by genric** [comment]
@pramodk, I didn't get it... Are you suggesting me to put tornado constraint into #545 and abandon this one?

**Comment by matz-e** [comment]
Retest this please.

Any chance we could rebase this onto latest `develop`?

**Comment by genric** [comment]
Well, the rebase failed. Although I'm able to `spack install py-jupyter-notebook` this on bb5.

**Comment by matz-e** [comment]
retest this please

I removed the old PR directory

**Comment by pramodk** [comment]
@genric : the CI shows:

```
2020-04-29T12:54:53.686Z] -- linux-rhel7-x86_64 / intel@19.0.4.243 ------------------------
[2020-04-29T12:54:53.686Z] uzrjfwn hpe-mpi@2.21
[2020-04-29T12:54:53.686Z] ### 14:54:53 gathering specs
[2020-04-29T12:56:30.512Z] ==> Error: Invalid Version range: 4.2:4
```
Can you take a look?

**Comment by genric** [comment]
Yeah, I saw that as well. But I'm puzzled how it arrives at this version spec from the files in the commit...

**Pull request closed without merging**
