### PR TITLE
stat: sync with upstream, deploy 4.0.2

### PR DESCRIPTION
**Pull request by matz-e**

### CODE REVIEW

**Comment by pramodk** [comment]
@matz-e : I didn’t get time to verify if new version is still segfaults.

**Comment by matz-e** [comment]
> @matz-e : I didn’t get time to verify if new version is still segfaults.

Could be done once it's been built

**Comment by pramodk** [comment]
@matz-e : no luck with this yet?

**Comment by matz-e** [comment]
Needs rebase?

**Comment by pramodk** [comment]
I did rebase and push forced - lets see.

**Comment by matz-e** [comment]
Quite out of sync, could be redone with recent upstream and 4.1. But that pulls in too much of a modern X stack on an ancient RedHat.

**Pull request closed without merging**
