### PR TITLE
add emsim spackage

### PR DESCRIPTION
**Pull request by ppodhajski**

### CODE REVIEW

**Review by matz-e — APPROVED** [review]
LGTM. Did you test the resulting module?

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
@matz-e  strange:

`12:23:24  [1m### [4m12:23:24[24m gathering specs(B[m
12:24:21  ==> Error: Cannot depend on 'diffutils' twice`

**Comment by ppodhajski** [comment]
Hi @pramodk, could you please have a look at this error?

` ==> Error: Cannot depend on 'diffutils' twice`

we're rather clueless on this. I cannot reproduce it interactively.

**Comment by matz-e** [comment]
> Hi @pramodk, could you please have a look at this error?
> 
> ` ==> Error: Cannot depend on 'diffutils' twice`
> 
> we're rather clueless on this. I cannot reproduce it interactively.

@pramodk is absent. I'll swing by.

**Comment by antonelepfl** [comment]
I'm testing and it works kind of properly.
When I load this new module I get 
```
>  module load emsim
Autoloading brion/3.0.0/serial
brion/3.0.0(17):ERROR:105: Unable to locate a modulefile for 'brion/3.0.0/serial'
```

**Comment by matz-e** [comment]
> I'm testing and it works kind of properly.
> When I load this new module I get
> 
> ```
> >  module load emsim
> Autoloading brion/3.0.0/serial
> brion/3.0.0(17):ERROR:105: Unable to locate a modulefile for 'brion/3.0.0/serial'
> ```

If the software works itself, then that is just a minor technical detail.

**Comment by antonelepfl** [comment]
Yes sure I just wanted to mention it so there are no surprises later :)
Thank you Matthias

**Pull request merged**
