### PR TITLE
Adding synapsetool 0.4 for the support of sonata

### PR DESCRIPTION
**Pull request by ferdonline**
0.4.1 was the patch for supporting both float and doubles
Dropping old versions

### CODE REVIEW

**Review by matz-e — APPROVED** [review]
LGTM as long as Jenkins succeeds :)

**Comment by ferdonline** [comment]
Error is a bit weird... Could you look into?

**Comment by pramodk** [comment]
@ferdonline  @matz-e  : See this [one](https://github.com/spack/spack/pull/10190#issuecomment-449962219). If this appears too many time, we should cherry [this](https://github.com/spack/spack/commit/fd4e9aa8ec55a3241771088c6c5a841cc384d3a1) commit.

**Comment by pramodk** [comment]
Please retest (solution for now is to re-trigger the build)

**Pull request merged**
