### PR TITLE
adding boost+python to serial libs

### PR DESCRIPTION
**Pull request by ppodhajski**

### CODE REVIEW

**Comment by pramodk** [comment]
@ppodhajski : for testing purpose, could you add `brayns ^brion+python` here? we can then check if boost is correctly use.

**Comment by ppodhajski** [comment]
Hi @pramodk, 

`- brayns@0.8.0 +opendeck +brion ^brion+python`  in _deploy/packages/bbp-packages.yaml_  is not sufficent here?

In the log of "deploy.sh serial-libraries" (self time 19min 27s), I could see boost was built twice, but I fail to interpret it.

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
as per output of job using configs from this PR: 
https://bbpcode.epfl.ch/ci/job/oss.Brayns/build_type=Release,platform=bb5/923/console

`==> boost is installed in an upstream Spack instance at /gpfs/bbp.cscs.ch/apps/hpc/jenkins/pulls/397/deploy/serial-libraries/2019-06-05/linux-rhel7-x86_64/gcc-6.4.0/boost-1.68.0-dmt2ndblol`

**Review by ppodhajski — COMMENTED** [review]
@pramodk maybe instead of specifying boost version as a dependency of assimp and deflect I should add a new line:
`- boost@1.65.0 `
The result shall be the same if I specify  brayns with ^boost@1.65.0 ( to my understanding ?
` brayns@0.8.0  [....]   ^boost@1.65.0`

**Comment by pramodk** [comment]
> The result shall be the same if I specify brayns with ^boost@1.65.0 ( to my understanding ?
brayns@0.8.0 [....] ^boost@1.65.0

No...
* if you have `a^b@versionX`, spack will use b@versionX
*  if you have `a^b` then spack will use b's latest version

**Review by pramodk — APPROVED** [review]

**Pull request merged**
