### PR TITLE
updated bluepymm to 0.7.15

### PR DESCRIPTION
**Pull request by anilbey**
bluepymm version 0.7.15 update

### CODE REVIEW

**Review by matz-e — APPROVED** [review]

**Comment by wvangeit** [comment]
@matz-e Is there an issue with the travis ci reporting?

**Comment by pramodk** [comment]
that's just occasional glitch from travis-ci!

**Comment by wvangeit** [comment]
@pramodk @matz-e It looks like it's failing, it seems it also happened in the previous (non-github-registered) travis build

**Comment by matz-e** [comment]
Yes, see the error message.

**Comment by matz-e** [comment]
[The package will have to be modified according to the new setup function](https://spack.readthedocs.io/en/latest/spack.html#spack.package.PackageBase.setup_build_environment)

**Comment by wvangeit** [comment]
So why was this passing before if we just change the version number?

**Comment by matz-e** [comment]
When did you last change the version number for `bleupymm`?

**Comment by anilbey** [comment]
3 months ago with this commit:  https://github.com/BlueBrain/spack/commit/b373681ac924aba4cc1bd39d03f5ec3383cd16fd

**Comment by matz-e** [comment]
I doubt that…

image

Flake actually failed for that last commit. Could you please split the function as described in the documentation?

**Review by matz-e — CHANGES_REQUESTED** [review]
```
def setup_environment(self, spack_env, run_env):
```
should read

```
def setup_run_environment(self, env):
```

rename `run_env` to `env` in the remaining lines, please.

**Review by matz-e — APPROVED** [review]
Thank you!

**Comment by pramodk** [comment]
> So why was this passing before if we just change the version number?

As Matthias said, the API for setting env variable is changed when we moved to new spack version (~Feb). The CI checks for deprecated API usage whenever package get updated. In this case, as package is being updated first time after the API change, CI complaints.

**Pull request merged**
