### PR TITLE
update h5py to 2.10.0

### PR DESCRIPTION
**Pull request by genric**

### CODE REVIEW

**Review by matz-e — COMMENTED** [review]
Why? Is this upstream?

**Comment by genric** [comment]
No, but it is released: https://github.com/h5py/h5py/releases/tag/2.10.0
And version 2.9.0 still has issues with py3 unicode.

**Comment by genric** [comment]
Apparently we can consider travis build as green(check `#spack` channel for details).

**Review by wizmer — APPROVED** [review]
Could you also make the PR on Spack/Spack ?
Thanks

**Pull request merged**
