### PR TITLE
py-bbp-workflow-cli: bump

### PR DESCRIPTION
**Pull request by genric**

### CODE REVIEW

**Review by matz-e — DISMISSED** [review]
Just a word of caution: I think that Spack removes all non-numeric components, and `3.1.1` may be considered less than the `.dev0` version. If such conflicts arise, or as a general good practice, in the future we can deprecate the `.dev0` version with the option `deprecated=True` to the `version` directive.

**Comment by genric** [comment]
@matz-e thanks for the info! After we'll run some tests I'm hoping to make a proper version release from this draft...

**Comment by genric** [comment]
@matz-e, can we merge this? or we need to wait for mega merge?

**Review by matz-e — APPROVED** [review]
Let's get this in, then I'll redeploy the new Spack after `unstable` has been updated.

**Comment by genric** [comment]
Great, thanks!

**Pull request merged**
