### PR TITLE
add brainbuilder-v0.11.4

### PR DESCRIPTION
**Pull request by mgeplf**

### CODE REVIEW

**Comment by mgeplf** [comment]
Matthis and Benoit are on vacation, so I'll need a review from someone else.

**Review by jorblancoa — APPROVED** [review]

**Comment by mgeplf** [comment]
@jorblancoa Thanks.
Is there anything I need to do to get this deployed?

**Comment by jorblancoa** [comment]
The CI runs every night, so tomorrow you will have them deployed and available.

If you need to test right now you can use your PR modules.
To see how to do that you can check the FAQ (How do I test my modules from the PR?)
https://github.com/BlueBrain/spack/blob/develop/FAQ.md

**Comment by mgeplf** [comment]
Thanks, I can wait until tomorrow.  Cheers.

**Comment by pramodk** [comment]
@mgeplf : we have been [specifically](https://github.com/BlueBrain/spack/blob/c716f5fc74bd386861b119b7b5bacad1ab76b972/deploy/packages/bbp-packages.yaml#L26) installing  `brainbuilder@0.11.3` and hence 0.11.4 is not deployed yet. We need to update that.

> Vishal asked about this today but don't know his Github username

**Pull request merged**
