### PR TITLE
[experimental] add gcc 8.2.0 stuff.

### PR DESCRIPTION
**Pull request by matz-e**
Pull request to test and validate 8.2.0 as a compiler chain.

@arsenius7 I spun off changes related to GCC 8 to this PR, to be able to properly test everything on a longer scale. I'll rebase this and augment it as needed. From the HPC side, we would like to see if you can reproduce your speed-up consistently and documented with the modules that will be generated from this PR.

### CODE REVIEW

**Comment by arsenius7** [comment]
> we would like to see if you can reproduce your speed-up consistently and documented with the modules that will be generated from this PR

OK, thanks, I'll look into it.

**Comment by matz-e** [comment]
`/gpfs/bbp.cscs.ch/apps/hpc/jenkins/pulls/191/config/modules.sh` has the `gcc8` modules available. @arsenius7 would you be able to give us some performance numbers using these modules in comparison to the stock (non-pull) ones?

**Comment by arsenius7** [comment]
OK, I'll try to do it today or tomorrow.

**Comment by arsenius7** [comment]
I know it will sound lame, but I can not reproduce the speedup I reported earlier with `gcc@8.2.0`.

On larger SLURM allocations (`-n100`) now I keep bumping into `Failed to mmap the shared map at the same address in each local rank` error for all variations of modules; and on smaller one-task-per-node allocations(`-N2`) all modules perform same and ~10% slower than `conda` environment.

Maybe it has something to do with `mpi4py` version (`conda` has 2.0, while default one in Spack is 3.0).
I'll get back to you if I collect any meaningful information.

**Comment by pramodk** [comment]
@arsenius7  : 


> Maybe it has something to do with mpi4py version (conda has 2.0, while default one in Spack is 3.0).
I'll get back to you if I collect any meaningful information
> and ~10% slower than conda environment.

With HPE-MPI we have seen some performance issues due to improper pinning. We suggest to use `dplace` along with srun and see if performance improves. See [this ticket](https://bbpteam.epfl.ch/project/issues/browse/HPCTM-1113) for more info. The syntax is : 

```
srun -n X dplace executable
```

> On larger SLURM allocations (-n100) now I keep bumping into Failed to mmap the shared map at the same address in each local rank error for all variations of modules;

Could you install your app with Intel-MPI (`placement-algorithm ^intel-mpi`) and run with same setup? And if that succeed, if you could provide re-producer, that will help us to send detailed logs to HPE.  @ohm314  can help with this.

**Comment by arsenius7** [comment]
A brief summary of my "discoveries" so far.

With default version of Spack `mpi4py` (=3.0.0) I could not get past `Failed to mmap the shared map` on `-n100` allocation.

For `-N4` allocation on a smaller circuit, `conda` environment (`mpi4py==2.0.0`) is ~10% faster than default `placement-algorithm` Spack-packed module.

No observable difference nor from `dplace`, neither from `^intel-mpi`.

With `placement-algorithm^mpi4py==2.0.0` I could get it to run on `-n100`.
Further trying different MPI and compiler I got:

| spec | time (s) |
|------|---------|
| ^mpi4py==2.0.0 | ~180 |
| ^mpi4py==2.0.0^intel-mpi | >1000 |
| ^mpi4py==2.0.0%gcc@8.2.0 | ~145 |

For the reference, `conda` environment with `mpi4py==2.0.0` took ~155s here.

I guess I'll stick to `mpi4py==2.0` for the moment.

**Comment by pramodk** [comment]
>  ^mpi4py==2.0.0^intel-mpi | >1000

For sure there is something wrong here will salloc and srun pinning with Intel MPI.

> I guess I'll stick to mpi4py==2.0 for the moment.

Ok...we can make 2.0 as preferred if people see that as problem.

**Review by tristan0x — APPROVED** [review]
Note that gcc 8.3 has been released 1 month ago. It provides tons of fixes and apparently made substantial 
 improvements regarding vectorizations

**Comment by matz-e** [comment]
Discontinued in favor of redeployment

**Pull request closed without merging**
