### PR TITLE
Add flex and bison for deployment in external and generate modules

### PR DESCRIPTION
**Pull request by pramodk**
- flex & bison are dependency on neuron+coreneuron+nmodl and
    newer versions are required as module during development
  - note: flex/bison is currently coming from legacy tools directory
    and it should be removed

```
----------------------------------------------------------------------------------------- /gpfs/bbp.cscs.ch/apps/tools/modules/tcl/linux-rhel7-x86_64 -----------------------------------------------------------------------------------------
 bison/3.0.5        flex/2.6.3         hpctoolkit/master  likwid/4.3.0       matlab/r2018a      matlab/r2019b      stat/3.0.1         totalview/2018.2.6
```

### CODE REVIEW

**Review by alkino — DISMISSED** [review]

**Review by olupton — DISMISSED** [review]
LGTM, what do we need to do to remove `/gpfs/bbp.cscs.ch/apps/tools/modules/tcl/linux-rhel7-x86_64`...?

**Comment by pramodk** [comment]
I will hold the deployment of this - have to check if adding flex/bison is resulting into lot of deployments. Will take a look at CI log on Monday.

**Review by matz-e — DISMISSED** [review]

**Comment by olupton** [comment]
Retest this please Jenkins

**Review by olupton — APPROVED** [review]
LGTM.

**Comment by pramodk** [comment]
@matz-e : IIUC from from [the build pipeline](https://bbpcode.epfl.ch/ci/blue/organizations/jenkins/hpc.spack-deployment.pull-requests/detail/hpc.spack-deployment.pull-requests/2118/pipeline/84/), not much has rebuilt. So this seems ok to merge?

**Review by matz-e — APPROVED** [review]
Sure.

**Pull request merged**
