### PR TITLE
update entity-management to 1.2.2

### PR DESCRIPTION
**Pull request by genric**

### CODE REVIEW

**Review by matz-e — DISMISSED** [review]

**Comment by genric** [comment]
@matz-e, any ideas why only for py38 we get ``[E501] line too long (92 > 79 characters)``?

**Comment by matz-e** [comment]
No

**Comment by genric** [comment]
Ok, then a more general question: why do we test against py38? Is BBP officially supporting it? If we do, could we then at least make the line length consistent across the versions we support? Thank you.

**Comment by matz-e** [comment]
Standard line length is 79. Don't know why the others didn't trigger on this. One of them has found it. And in the future we will support py38, and drop 36.

**Comment by genric** [comment]
Line length fixed.

**Review by matz-e — APPROVED** [review]

**Pull request merged**
