### PR TITLE
bump py-bbp-workflow

### PR DESCRIPTION
**Pull request by genric**

### CODE REVIEW

**Review by matz-e — DISMISSED** [review]

**Comment by genric** [comment]
Retest this please.

**Comment by matz-e** [comment]
@genric this is on our simulation team, seems there's a recent API change.

**Comment by genric** [comment]
Thanks for the update @matz-e! Was a bit puzzled by the error in CI...

**Comment by matz-e** [comment]
> Thanks for the update @matz-e! Was a bit puzzled by the error in CI...

Yeah, not the most transparent. Feedback I got was that it is something being worked on, so hopefully won't be too long.

**Comment by genric** [comment]
Retest this please.

**Comment by genric** [comment]
Retest this please.

**Review by matz-e — APPROVED** [review]

**Pull request merged**
