### PR TITLE
remove dependency on argparse in scoop

### PR DESCRIPTION
**Pull request by genric**

### CODE REVIEW

**Review by mgeplf — DISMISSED** [review]

**Review by matz-e — DISMISSED** [review]

**Comment by genric** [comment]
Retest this please.

**Comment by matz-e** [comment]
Retest this please

**Comment by genric** [comment]
Any hints about jenkins failure?

**Comment by matz-e** [comment]
> Any hints about jenkins failure?

Someone did not update moved repositories :shrug:

**Comment by matz-e** [comment]
Will need #1234

**Comment by genric** [comment]
Hmm... how did they manage to merge if build is failing?

**Comment by matz-e** [comment]
This may be the first time that those packages are being rebuilt after the move to GitLab

**Review by mgeplf — APPROVED** [review]
LGTM

**Comment by GianlucaFicarelli** [comment]
There is an error in https://bbpcode.epfl.ch/ci/job/nse.python.circuit-build.gerrit/431/TOXENV=py38,platform=bb5/console that seems related to this PR:
> 10:22:28 pkg_resources.DistributionNotFound: The 'argparse>=1.1' distribution was not found and is required by scoop

According to setup.py, argparse is required only for python < 2.7 in the current master, but `argparse>=1.1` is still needed in scoop 0.7.1.1 (the version in spack and also the latest version available on pypi).

**Comment by genric** [comment]
Well, it is obviously a problem of setup.py in those versions(https://github.com/soravux/scoop/issues/16).
How do you suggest to fix it?
Take the latest master to spack? Or just the commit that fixes it? Then we need to confirm bluepyopt people are happy with it.
Or we patch it in spack?

**Comment by mgeplf** [comment]
It's gross, but I think that patching setup.py is probably the best way; scoop seems to be under-developed.

I'm not sure how much scoop is used in `bluepyopt`; so perhaps that dependency can be dropped.  @wvangeit probably knows best.

**Comment by matz-e** [comment]
Yet another parallelism framework? I'd agree that patching `setup.py` would probably be best if the dependency is required.

**Comment by wvangeit** [comment]
I'm ok with dropping the scoop dependency of bluepyopt spack, I don't think anybody is using it anymore.

**Pull request merged**
