### PR TITLE
spark: bump to 3.0.0

### PR DESCRIPTION
**Pull request by matz-e**

### CODE REVIEW

**Comment by matz-e** [comment]
@pramodk We currently have a good "stable" version of Spykunc. Maybe we could get this merged to advance this month and get everything current?

**Comment by matz-e** [comment]
@pramodk, thoughts?

**Review by ferdonline — DISMISSED** [review]
It seems to me everything is pretty self contained, so since it all builds... LGTM

**Comment by matz-e** [comment]
Already needed a rebase :(

**Comment by matz-e** [comment]
Ping!

**Review by alexsavulescu — APPROVED** [review]

**Pull request merged**
