### PR TITLE
Replace the old versions of the nexusforge by the last one (0.6.3)

### PR DESCRIPTION
**Pull request by nabilalibou**

### CODE REVIEW

**Comment by matz-e** [comment]
How about a `rebase`?
image

**Review by matz-e — APPROVED** [review]

**Comment by nabilalibou** [comment]
> How about a rebase?

@matz-e , a simple `git rebase` performed in my local folder would avoid having this mountain of old commits in each future pull request isn't it?

**Comment by matz-e** [comment]
Yes :)

Alternatively, I tend to keep `develop` in sync with the upstream repository, and create temporary branches for pull requests that I throw away after merging. Then I go back to `develop` and just update with `git pull --ff-only`, rinse, repeat

**Comment by nabilalibou** [comment]
Ok I note for the next ones ;)

**Pull request merged**
