### PR TITLE
py-bba-datapush: deploy module

### PR DESCRIPTION
**Pull request by lecriste**
Package created in
https://github.com/BlueBrain/spack/pull/1795/files#diff-1fda5e0a8031fff014bccedb92353952b26ef4d59949c7d4dc22f937fbef7b91

### CODE REVIEW

**Review by matz-e — APPROVED** [review]
Got to say that the naming of these packages is a bit inconsistent (`datafetch` vs `data-push`)

**Comment by lecriste** [comment]
I wondered about that (commit description): https://github.com/BlueBrain/spack/pull/1815/commits/bfc077b9b841b830f2c06ba054094746d6db2386

**Comment by lecriste** [comment]
I tested the new module successfully.

@matz-e, I had noticed the [naming inconsistency](https://github.com/BlueBrain/spack/pull/1815#issuecomment-1405031113) but there are also packages like `py-data-integrity-check`. I have no strong opinion here, if we want to uniform the naming I would go for more `-` than for less.

**Comment by matz-e** [comment]
@lecriste I think naming can be considered later, but should probably happen soon™

**Pull request merged**
