### PR TITLE
py-h5py: deploy module with mpi.

### PR DESCRIPTION
**Pull request by matz-e**
See BSD-210.

### CODE REVIEW

**Comment by pramodk** [comment]
@matz-e : if this is still relevant, could you check CI?

**Comment by matz-e** [comment]
@pramodk rebased.

**Review by pramodk — APPROVED** [review]
I have vague memories - If people are running serial scripts under SLURM then there would be some errors/problems? Or, I think we have made necessary SLURM allocation changes (--pmi=none) to avoid that?

**Comment by matz-e** [comment]
> If people are running serial scripts under SLURM then there would be some errors/problems? Or, I think we have made necessary SLURM allocation changes (--pmi=none) to avoid that?

Yes, our changes to the SLURM setup should avoid this. Still no guarantee, especially if folks load all kinds of modules. Currently, modules may be mixed-and-matched and all kinds of `PYTHONPATH` shenanigans may happen.

**Pull request merged**
