### PR TITLE
Rebase with upstream llnl/develop

### PR DESCRIPTION
**Pull request by pramodk**
@matz-e  : this is rebased on top of upstream.

* As you know the changes in the core best, when time permit, could you look at the core changes ? (i.e. spack/lib).
* Also, I have dropped the squashed spack chain commit. Have to see what might have lost there.

* @tristan0x  : could you confirm why we needed to remove build_type for zee? It seems like new spack doesn't allow empty variant values:

```
→ spack spec cmake
Input spec
--------------------------------
cmake

Concretized
--------------------------------
==> Error: the default cannot be an empty string [zee, variant 'build_type']
```

### CODE REVIEW

**Comment by matz-e** [comment]
Oh boy… I'll maybe best compare the changes between this and `spack/develop` on my workstation / BB5. My Macbook's Firefox isn't even able to render the changes tab correctly.

Dropping the squashed chain should be fine.

**Comment by matz-e** [comment]
Diffing `lib` between `spack/develop` and this branch looks all good to me!

**Comment by matz-e** [comment]
Retest this please

**Comment by matz-e** [comment]
Retest this please

**Comment by matz-e** [comment]
Retest this please

**Comment by ferdonline** [comment]
This is not the most up-to-date commit, right? Probably before commiting this we have to merge our develop branch here.

**Pull request closed without merging**
