### PR TITLE
HPE-MPI: from 2.16 to 2.21

### PR DESCRIPTION
**Pull request by pramodk**

### CODE REVIEW

**Review by jorblancoa — APPROVED** [review]

**Review by matz-e — APPROVED** [review]

**Comment by jorblancoa** [comment]
retest this please

**Comment by pramodk** [comment]
Before merge, we should test the modules manually (simulation) because this is a significant change.

**Comment by pramodk** [comment]
Please retest

**Comment by pramodk** [comment]
@matz-e : https://bbpcode.epfl.ch/ci/blue/organizations/jenkins/hpc.spack-deployment.pull-requests/detail/hpc.spack-deployment.pull-requests/115/pipeline/57

I see:

```

[2020-01-13T09:15:16.469Z] ### 10:15:13 no specs to install?
[2020-01-13T09:15:19.904Z] ==> Regenerating tcl module files
[2020-01-13T09:15:20.179Z] ### 10:15:20 augmenting packages.yaml
[2020-01-13T09:15:24.716Z] ==> Error: Package blender not found.
script returned exit code 1
```

**Comment by pramodk** [comment]
@matz-e @ohm314 : with https://bbpteam.epfl.ch/project/issues/browse/HPCTM-1324, can push the button?

**Comment by matz-e** [comment]
@pramodk if we merge this now, January modules for, e.g., neuron will switch from 2.16 to 2.21 mid-month. If we wait until February 1st, January modules consistently use 2.16, and February modules can be run with 2.21.

Thoughts?

**Comment by pramodk** [comment]
As we updated Jan release yesterday only, I was thinking if we can get this also in soon and then announce changes.

The reason is that in mid-February we are planning IME workshop with DDN and need to prepare our apps & benchmarks for that meeting.

**Comment by ohm314** [comment]
Let's still wait for the next release rather than pushing it out now in the middle of things. For benchmarks we can always build the necessary packages ourselves and have them separate.

**Comment by pramodk** [comment]
@ohm314 : apart from benchmarks, there couple of pending issues:
* https://bbpteam.epfl.ch/project/issues/browse/HPCTM-1321
* https://bbpteam.epfl.ch/project/issues/browse/BSD-77
* https://bbpteam.epfl.ch/project/issues/browse/BSD-7

and there are others.

**Comment by pramodk** [comment]
Already merged with develop. We have to update README later.

**Pull request closed without merging**
