### PR TITLE
bb5: explicitly state that hdf5 is compiled without MPI

### PR DESCRIPTION
**Pull request by matz-e**
This trips me up a lot.

### CODE REVIEW

**Comment by pramodk** [comment]
I took liberty of updating your PR.
Could you check if new boost and hdf5 with gcc 6.4.0 solves your all link issues between different libc++?

**Comment by matz-e** [comment]
OK, now I have the following fun message:
```
/usr/lib/libdl.so: error adding symbols: File in wrong format
```

**Comment by pramodk** [comment]
@matz-e : should be fixed by : https://bbpcode.epfl.ch/code/#/c/41912/

**Review by matz-e — COMMENTED** [review]
LGTM

**Review by pramodk — APPROVED** [review]

**Pull request merged**
