### PR TITLE
Bump neurodamus for most recent patches

### PR DESCRIPTION
**Pull request by ferdonline**
Since release 3.0 neurodamus received a few important fixes. 
Including them as a new patch version still in this month archive.

Bump neurodamus-py 2.0.0 to 2.0.2:
 - Fixing replay to work with multiple populations
 - Ensure data dir when skipping model build
 - Fix skipping synapse creation when weight is 0 (BBPBGLIB-673)
 - Fix deadlock when an exception is thrown from NEURON (BBPBGLIB-678)
 - Logging colors only for tty

Bump neurodamus-core 3.0.0 to 3.0.1:
 - Avoid getting nilSecRef from objects (HPCTM-1381)

### CODE REVIEW

**Review by matz-e — DISMISSED** [review]

**Review by pramodk — CHANGES_REQUESTED** [review]
Can't we include Jorge's fix for py-neurodamus?

**Comment by ferdonline** [comment]
At the time of creation it was not there yet.
Jorge quick fix needs mpi4py to call mpi_abort which is not great
@jorblancoa maybe we can use ctypes to make the c call directly?

EDIT: seems to work

```python
import ctypes
from neuron import h

pc = h.ParallelContext()

if pc.id() == 0:
    print("Im alright now. Entering a deadlocking collective")
    pc.barrier()

elif pc.id() == 1:
    print("Im the sick process! Want to quit right away")
    libpath = ctypes.util.find_library('mpi')
    mpi = ctypes.CDLL(libpath)
    mpi.MPI_Abort(0)
```

**Comment by ferdonline** [comment]
Closing since tags will be updated

**Comment by pramodk** [comment]
I commented on internal PR about ctypes.

**Review by pramodk — APPROVED** [review]
lgtm (didn’t want to block this for ctypes related discussion which is separate thing)

**Pull request merged**
