### PR TITLE
cuda: update recipe, deploy 11.4.2

### PR DESCRIPTION
**Pull request by olupton**
In https://github.com/spack/spack/pull/26892 I added the 3 newest versions of CUDA to upstream.

This PR backports the new versions, but maintains some small differences w.r.t. the upstream version:
- Keep the BBP-specific patch to add the CUPTI library path to `LD_LIBRARY_PATH`
- Drop the upstream `dev` variant and `ncurses` dependency -- even if we don't enable the variant, to make the upstream recipe work we have to backport changes to the `ncurses` recipe that would trigger a lot of rebuilding in our deployment.
- The formatting rules are different between our `develop` and `upstream/develop` 😞

In addition to the above changes to the recipes, modify the BB5 deployment to:
- include CUDA 11.4.2.
- drop CUDA 10.1.243 and a reference to CUDA 11.1.0.

We can use CUDA 11.4 with NVHPC 21.9, which was deployed in https://github.com/BlueBrain/spack/pull/1334 (actually the NVHPC installation bundles CUDA, but in our current setup we only partially use the bundled version).

Note that CUDA 11.4.1+ support GCC 11 and Clang 12 as host compilers, which may be useful for the next redeployment.

### CODE REVIEW

**Comment by olupton** [comment]
Upstream PR with new versions: https://github.com/spack/spack/pull/26892.

**Comment by olupton** [comment]
Rebased on top of #1334. We need nvhpc 21.9 to use cuda 11.4.2.

**Comment by olupton** [comment]
I think this is pretty much ready to go, but ideally we would wait for the review of the upstream PR to conclude first so we stay in sync.

**Review by iomaganaris — APPROVED** [review]
LGTM :+1:

**Review by pramodk — APPROVED** [review]
LGTM!

**Pull request merged**
