### PR TITLE
Coreneuron knl

### PR DESCRIPTION
**Pull request by st4rl3ss**

### CODE REVIEW

**Comment by pramodk** [comment]
@st4rl3ss : lets check this once Ioannis is back

**Comment by st4rl3ss** [comment]
Yeah, it's giving a weird error. Better to check with him.
Would you kindly approve the other PR that built correctly if you think they're ok?

**Comment by st4rl3ss** [comment]
please retest

**Comment by st4rl3ss** [comment]
please retest

**Comment by pramodk** [comment]
@st4rl3ss  : could you change the prefix to `/knl` in : https://github.com/BlueBrain/spack/blob/develop/deploy/configs/applications/modules.yaml ? 

And could you verify with the module name that is being generated?

**Review by pramodk — APPROVED** [review]

**Comment by matz-e** [comment]
> > @st4rl3ss : could you change the prefix to /knl in : https://github.com/BlueBrain/spack/blob/develop/deploy/configs/applications/modules.yaml ?
>
> And could you verify with the module name that is being generated?

@pramodk I think this is currently causing trouble, because there should be a module file `…/python3` generated, and then a file `…/python3/knl`, which assumes that the former is a *directory not a file*. We need to revert this.

**Pull request merged**
