### PR TITLE
spack setup: new --shebang option

### PR DESCRIPTION
**Pull request by tristan0x**
Allow to specify another shebang in spconfig.py script.

Rationale: `build-env` set PYTHONPATH and PYTHONHOME that can crash other python
interpreter. For instance:
```
[tcarel@lambda]$ spack setup zee@develop

[tcarel@lambda]$ head -n1 spconfig.py
/home/tcarel/src/github.com/pyenv/pyenv/shims/python

[tcarel@lambda]$ spack build-env zee@develop bash --norc

[tcarel@build-env]$ ../spconfig.py ..
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007fffedac8740 (most recent call first):
Aborted (core dumped)
```

This kind of issue motivated this patch where the python interpreter
to use is not necessarily the one that has been used to create spconfig.py

A fix for the situation above is: `spack setup --shebang env zee@develop`

### CODE REVIEW

**Review by matz-e — COMMENTED** [review]
Seems sensible to me. @pramodk ?

**Review by matz-e — APPROVED** [review]
I think it would be worthwhile pushing this upstream and get their opinion, too.

**Comment by tristan0x** [comment]
ping @pramodk

**Review by pramodk — APPROVED** [review]
Looks good to me (but have little experience).

As Matthias suggested, I would upstream and tag citibeth for opinion.

**Pull request merged**
