### PR TITLE
add bbp root ca to py-certifi

### PR DESCRIPTION
**Pull request by genric**

### CODE REVIEW

**Review by matz-e — DISMISSED** [review]

**Comment by genric** [comment]
Any ideas, @matz-e? retest?

**Comment by matz-e** [comment]
@genric just restarted the "science" stage

Would really like to find out how to give everyone the rights to restart stages.

**Comment by genric** [comment]
> @genric just restarted the "science" stage
> 
> Would really like to find out how to give everyone the rights to restart stages.

Yep, would be nice. Rebase/push for now :)

**Review by matz-e — APPROVED** [review]
Seems legit. Thank you!

**Comment by genric** [comment]
Thank you!

**Pull request merged**
