### PR TITLE
bump py-dask

### PR DESCRIPTION
**Pull request by arnaudon**

### CODE REVIEW

**Comment by arnaudon** [comment]
@asanin-epfl , @GianlucaFicarelli  told me this could hurt you?

**Comment by asanin-epfl** [comment]
Is there any specific reason to have this Dask version?

**Comment by arnaudon** [comment]
I'm runing with dask-mpi some heavy stuff, and it was quite unstable (loosing workers, etc...). I tried with local install of latest dask version, and it seems to work fine (still testing more). It seems that they fixed some bugs, or incompatibilities with dask-mpi. What codes need a specific dask version? We can try to see if this one does not break any? Dask seems to be moving fast, so better to keep up with it i think, to have all latest features and bug fixed?

**Comment by asanin-epfl** [comment]
ok, don't you need to update py-dask-mpi package as well?

**Comment by arnaudon** [comment]
no this one was latest version already. So several tools need to be udpated for this PR to pass (minis-validation, bbp-workflow, placement-algorithm and morph-tool). @asanin-epfl , any other ones? I can fix the version in these. dask of placement-algo is not used (I may remove it as well), and morph-tool is not used much, so latest version should work. 
I'll ask genrich for bbp-workflow, not sure who is maintainint minis-validation.

**Comment by genric** [comment]
It would be good to start by taking ``2020.12.0`` from upstream. Please also include updates to ``py-distributed`` package.

**Comment by arnaudon** [comment]
@genric, you mean to have both versions, this 2020, and the one I had put?

**Comment by genric** [comment]
@arnaudon, yes. There is also a bunch of dependency version resolution introduced upstream.

**Pull request closed without merging**
