### PR TITLE
hpe-mpi: hdf5: add patched version received from HPE support

### PR DESCRIPTION
**Pull request by pramodk**
This patched version fixes the issue encountered by @1uc
  see https://github.com/1uc/hpe-mpi-io-bug

### CODE REVIEW

**Comment by 1uc** [comment]
Might work. Valgrind can't find anything other than the usual "conditional jump or move depends on uninitialized value(s)" and neither the reproducer not the acceptance test is segfaulting.

**Comment by 1uc** [comment]
I'm not sure that the change is sufficient. Somehow only darshan is getting rebuilt, when we'd expect virtually every package to be rebuilt (because almost everything depends on MPI).

**Review by matz-e — DISMISSED** [review]
Needs this changed: https://github.com/BlueBrain/spack/blob/develop/bluebrain/deployment/environments/externals.yaml#L115

**Comment by pramodk** [comment]
HPE support has confirmed that this version has passed QA. So good to deploy in production.

**Comment by 1uc** [comment]
AFAICT, the new modules aren't affected by the bug anymore either.

**Review by 1uc — APPROVED** [review]

**Pull request merged**
