### PR TITLE
Deploy to /gpfs/bbp.cscs.ch/ssd/apps instead of /gpfs/bbp.cscs.ch/apps

### PR DESCRIPTION
**Pull request by MatMaul**

### CODE REVIEW

**Comment by matz-e** [comment]
Wait… is normal `apps` not on SSDs?

**Comment by pramodk** [comment]
@MatMaul : now thinking more about this : we are using `/gpfs/bbp.cscs.ch/apps/hpc/` everywhere (e.g. MODULEPATH that put in bashrc).

So if things fail, I wonder if it is good idea to have consistency everywhere :)

**Review by matz-e — APPROVED** [review]

**Review by pramodk — APPROVED** [review]

**Comment by MatMaul** [comment]
Actually the changes I need are the one on the bashrc in `/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/config/modules.sh` :) I understood that this file would be generated by Jenkins (through the Jenkinsfile) but I am perhaps wrong, if it is manual or happening elsewhere let me know.

**Comment by pramodk** [comment]
> but I am perhaps wrong, if it is manual or happening elsewhere let me know.

ok, now I remember the shell script is then sourced for all users. Its fine!

**Pull request merged**
