### PR TITLE
updated BGLibPy to 4.3.12

### PR DESCRIPTION
**Pull request by anilbey**
BGLibPy Changelog:
 4.3.9:
 - Add support for a* targets in connection blocks

 4.3.8:
 - Vectorised usage of bluepy api for get_sonama_mecombo_emodels

 4.3.4:
 - Add node_properties_available to check if nodes.h5 can be used
 - Add get_sonata_mecombo_emodels to extract nodes.h5 properties
 - setup.py to use bluepy[sonata]>=0.14.12, needed for bluepysnap
 - Add bglibpy/tests/examples/sim_sonata_node/ test directory

 4.3:
 - Add ability to read inh/exc minis from sonata nodes file
 - Add use scaling based on hill coefficient / extracellular calcium concentration
 - Add ability to read conductance ratio from sonata nodes file
 - Rely on BluePy to read nrn.h5 version
 - Execute nosetests in parallel
 - Add OMP_NUM_THREADS=1 to test to avoid running out of resources
 - Stop testing for deprecation warning when using .syns
 - Use lru_cache to optimize bluepy query
 - Add CHANGELOG

### CODE REVIEW

**Review by matz-e — APPROVED** [review]

**Comment by anilbey** [comment]
When can this be merged? The people working on the recent circuits require this version of BGLibPy to support the SONATA nodes file. It would be great to have this version available to them.

**Comment by matz-e** [comment]
You can't hit the "Squash and merge" button?

**Comment by anilbey** [comment]
No, I only have a close and a comment button :)

**Comment by matz-e** [comment]
Which @BlueBrain teams do you belong to?

**Comment by anilbey** [comment]
Only the cells team.

**Comment by matz-e** [comment]
I've added the cells team with write access. You should be able to push branches to this repository and merge PRs.

**Pull request merged**
