### PR TITLE
whitelist graphviz

### PR DESCRIPTION
**Pull request by genric**

### CODE REVIEW

**Comment by pramodk** [comment]
As a module, is this used by end users?

**Comment by genric** [comment]
It will be used in our sphinx build(to generate documentation with some nice graphs :)

**Comment by matz-e** [comment]
Well, well… @pramodk I just came across a use for it, too. Visualizing Snakemake.

**Review by matz-e — APPROVED** [review]
Selfishly motivated, but oh well. There's at least two distinct users from two distinct teams now.

**Comment by pramodk** [comment]
> There's at least two distinct users from two distinct teams now.

If you guys would be using this on BB5 then it's ok. Not a problem.
If it's going to be used only by bbprelman only under CI then something to consider.

**Comment by genric** [comment]
@pramodk so what other alternatives do I have to get graphviz on bb5 nodes in jenkins?

**Pull request merged**
