### PR TITLE
fix: don't consider external extensions.

### PR DESCRIPTION
**Pull request by matz-e**

### CODE REVIEW

**Comment by pramodk** [comment]
@matz-e  : is this to avoid issue when uninstalling extension?

I wonder about if there are any implication. I never had trouble with external packages but I have to admit I haven't tried "extensions".

What happens when we specify extension as an external and generate module? Does module get correct path?

**Comment by matz-e** [comment]
@pramodk yes, this seems to be only triggered with extensions.

> What happens when we specify extension as an external and generate module? Does module get correct path?

I'll have to test that. Is it a good idea to generate modules for external packages, though? I seem to re-generate the python modules a lot, and I'm not really a fan of that.

**Comment by pramodk** [comment]
> Is it a good idea to generate modules for external packages, though?

I also don't think we need to generate module...go ahead with merge if this is working with your setup.

**Review by pramodk — APPROVED** [review]

**Comment by pramodk** [comment]
Please retest

**Pull request merged**
