### PR TITLE
steps: update deployment dependencies

### PR DESCRIPTION
**Pull request by tristan0x**

### CODE REVIEW

**Comment by tristan0x** [comment]
There is a CI issue I don't understand @matz-e 

```
2021-03-08T22:58:33.501Z] ==> Error: Name clashes detected in module files:
[2021-03-08T22:58:33.501Z] file: /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/pulls/1076/deploy/libraries/2021-03-08/modules/tcl/linux-rhel7-x86_64/petsc/3.14.1
[2021-03-08T22:58:33.501Z] spec: petsc@3.14.1%gcc@9.3.0~X~batch~cgns~complex~cuda~debug+double~exodusii~fftw~giflib+hdf5+hypre~int64~jpeg~knl~libpng~libyaml~memkind+metis~moab~mpfr+mpi~mumps~p4est~random123~saws+shared~suite-sparse+superlu-dist~trilinos~valgrind clanguage=C arch=linux-rhel7-x86_64
[2021-03-08T22:58:33.501Z] spec: petsc@3.14.1%gcc@9.3.0~X~batch~cgns~complex~cuda~debug+double~exodusii~fftw~giflib+hdf5+hypre+int64~jpeg~knl~libpng~libyaml~memkind+metis~moab~mpfr+mpi~mumps~p4est~random123~saws+shared~suite-sparse+superlu-dist~trilinos~valgrind clangua
```

I understand it is because I specified 2 PETSc specs in `environments/externals.yaml`. But there are also 2 boost specs so I don't understand why it doesn't complain about boost also.

**Comment by matz-e** [comment]
Sorry, was busy with that workshop. As the error message says, there's a clash in the *module* name. I.e., we need to tune the module configuration to pick up only one of the specs of `steps`.

**Comment by tristan0x** [comment]
retest this please Jenkins

**Comment by matz-e** [comment]
@tristan0x, I think this could also benefit from a rebase!

**Review by matz-e — APPROVED** [review]

**Pull request merged**
