### PR TITLE
Added newer version of Darshan packages and enable modules

### PR DESCRIPTION
**Pull request by pramodk**

### CODE REVIEW

**Review by matz-e — APPROVED** [review]
LGTM.

**Comment by pramodk** [comment]
Travis fails because of:

```
        msg = 'there are {0} packages still using old APIs in this PR [{1}]'
1828>       assert not failing, msg.format(
1829            len(failing), ','.join(failing)
1830        )
1831E       AssertionError: there are 1 packages still using old APIs in this PR [darshan-runtime]
1832E       assert not ['darshan-runtime']
```

**Comment by pramodk** [comment]
Travis fails because of:

```
        msg = 'there are {0} packages still using old APIs in this PR [{1}]'
1828>       assert not failing, msg.format(
1829            len(failing), ','.join(failing)
1830        )
1831E       AssertionError: there are 1 packages still using old APIs in this PR [darshan-runtime]
1832E       assert not ['darshan-runtime']
```

**Comment by matz-e** [comment]
Also done in #788

**Pull request closed without merging**
