### PR TITLE
Update CoreNEURON package to include summation soma reports

### PR DESCRIPTION
**Pull request by sergiorg-hpc**

### CODE REVIEW

**Comment by jorblancoa** [comment]
retest this please

**Comment by jorblancoa** [comment]
retest this please

**Comment by jorblancoa** [comment]
retest this please

**Comment by sergiorg-hpc** [comment]
retest this please

**Comment by jorblancoa** [comment]
retest this please

**Comment by jorblancoa** [comment]
retest this please

**Review by jorblancoa — APPROVED** [review]

**Pull request merged**
