### PR TITLE
Neuron package update

### PR DESCRIPTION
**Pull request by pramodk**

### CODE REVIEW

**Review by matz-e — APPROVED** [review]
Looks sensible to me. I guess CI will have to wait until GH is fully functional again?

**Comment by pramodk** [comment]
Please retest

**Comment by ferdonline** [comment]
Good gitHub is finally back and tests went well! Merging

**Comment by wvangeit** [comment]
I pulled the latest develop branch and built neuron. But I'm still getting
```
>>> import neuron
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named neuron
```

Doesn't a pythonpath have to be set in the module ?

```
└──> module show neuron-develop-gcc-7.3.0-oglhphj
-------------------------------------------------------------------
/home/vangeit/private/src/bbpspack/share/spack/modules/linux-ubuntu18.04-x86_64/neuron-develop-gcc-7.3.0-oglhphj:

module-whatis    NEURON is a simulation environment for single and networks of neurons. 
prepend-path     LD_LIBRARY_PATH /home/vangeit/private/src/bbpspack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/neuron-develop-oglhphj7o2v2r4qqzkschaz5zzibgjt7/lib 
prepend-path     LIBRARY_PATH /home/vangeit/private/src/bbpspack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/neuron-develop-oglhphj7o2v2r4qqzkschaz5zzibgjt7/lib 
prepend-path     CPATH /home/vangeit/private/src/bbpspack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/neuron-develop-oglhphj7o2v2r4qqzkschaz5zzibgjt7/include 
prepend-path     CMAKE_PREFIX_PATH /home/vangeit/private/src/bbpspack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/neuron-develop-oglhphj7o2v2r4qqzkschaz5zzibgjt7/ 
prepend-path     CPATH /home/vangeit/private/src/bbpspack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/libxml2-2.9.8-xhsbjjjj4jdo5vv4nszwu5edip4fhebh/include/libxml2 
prepend-path     PATH /home/vangeit/private/src/bbpspack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/neuron-develop-oglhphj7o2v2r4qqzkschaz5zzibgjt7/x86_64/bin 
prepend-path     LD_LIBRARY_PATH /home/vangeit/private/src/bbpspack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/neuron-develop-oglhphj7o2v2r4qqzkschaz5zzibgjt7/x86_64/lib 
-------------------------------------------------------------------
```

**Comment by ferdonline** [comment]
Indeed I see no Pythonpath was set. Myself I typically start  "nrniv -python" to avoid this kind of problems.
I will update the build spec to include the PYTHONPATH. But did it ever
work??

**Comment by wvangeit** [comment]
Ok, thanks. Not sure it every worked, I never used spack-neuron.
I would avoid using "nrniv -python", from my experience many users load python and then import neuron. If you always do it that away you can immediately detect problems other users might have.

**Pull request merged**
