### PR TITLE
Added newer versions of bluepy and bluepysnap

### PR DESCRIPTION
**Pull request by joni-herttuainen**
Added 
- `bluepy v2.4.3`
- `bluepysnap v0.13.0`

I kept the previous versions for now.

### CODE REVIEW

**Comment by mgeplf** [comment]
> I kept the previous versions for now.

Are other software pinned to those versions?

**Review by matz-e — APPROVED** [review]
Seems fine. I have no strong opinions on older versions if the package does not have convoluted dependency requirements.

**Comment by joni-herttuainen** [comment]
> Are other software pinned to those versions?

No, there's none. That was more like just-in-case. Do I interpret correctly that you'd rather not have them?

**Comment by mgeplf** [comment]
> Do I interpret correctly that you'd rather not have them?

I think in general, we should try to limit them.  Having a *single* previous version can be useful if we're getting close to the end of the month (when things are going to be permanent).

Let's go w/ what is there for now, but we should form a concensus at some point.

**Review by mgeplf — APPROVED** [review]

**Pull request merged**
