### PR TITLE
snakemake: assorted fixes.

### PR DESCRIPTION
**Pull request by matz-e**

### CODE REVIEW

**Comment by matz-e** [comment]
Tested with `export HOME=$MY_TEMPORARY_DIRECTORY` and loading module.

**Review by mgeplf — APPROVED** [review]
I'm going to believe your testing

**Review by pramodk — APPROVED** [review]

**Comment by matz-e** [comment]
> I'm going to believe your testing

I don't. We should still come up with an isolation procedure to make sure binaries work.

**Comment by mgeplf** [comment]
Yup, agreed about automated checks.  I was just signalling that I didn't actually build it myself, in this case.

**Comment by matz-e** [comment]
> Yup, agreed about automated checks. I was just signalling that I didn't actually build it myself, in this case.

`source /gpfs/bbp.cscs.ch/apps/hpc/jenkins/pulls/508/config/modules.sh` lets one testdrive the module.

**Pull request merged**
