### PR TITLE
update bluepymm to 0.7.65

### PR DESCRIPTION
**Pull request by anilbey**
I noticed neuron isn't getting loaded upon loading py-bluepymm.
I expect the change in `depends_on('neuron+python', type='run')` to fix it.
Also the version got updated.

### CODE REVIEW

**Review by matz-e — COMMENTED** [review]
Seems like Jénkins finished already. Did you test that the module after `unset MODULEPATH` and sourcing `/gpfs/bbp.cscs.ch/ssd/apps/jenkins/pulls/986/config/modules.sh` works OK? (paths may be similar…)

**Comment by anilbey** [comment]
> Seems like Jénkins finished already. Did you test that the module after `unset MODULEPATH` and sourcing `/gpfs/bbp.cscs.ch/ssd/apps/jenkins/pulls/986/config/modules.sh` works OK? (paths may be similar…)

@matz-e  The directory above (/gpfs/bbp.cscs.ch/ssd/apps/jenkins) does not exist. Is it changed?

**Comment by matz-e** [comment]
Forgot an `hpc` after `apps`

**Comment by anilbey** [comment]
Thanks. Now I tested. It is OK.
After loading py-bluepymm/0.7.65, these following modules are loaded.

```
Currently Loaded Modulefiles:
  1) unstable             3) py-efel/3.0.80       5) py-bluepymm/0.7.65
  2) python/3.7.4         4) hpe-mpi/2.21 
```

BluePyMM and its modules also get imported successfully.

```
>>> import bluepymm
>>> bluepymm.__dir__()
['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__path__', '__file__', '__cached__', '__builtins__', '_version', '__version__', 'tools', 'prepare_combos', 'legacy', 'bluepymm', 'run_combos', 'select_combos', 'validate_output', 'main', 'run']
```

**Review by matz-e — APPROVED** [review]
Good to go!

**Pull request merged**
