### PR TITLE
Add bglibpy and reportinglib to deployed packages

### PR DESCRIPTION
**Pull request by ferdonline**

### CODE REVIEW

**Review by wvangeit — APPROVED** [review]

**Comment by ferdonline** [comment]
@matz-e @pramodk Would it make sense to have some module hierarchy? Maybe a namespace for centrally deployed packages, so we could do e.g.`module load bbp/neurondamus-x ?` 
Currently it's a bit problematic when we use more than one stack wit modules.

**Review by pramodk — APPROVED** [review]

**Comment by pramodk** [comment]
Not sure I understood what you meant by module hierarchy. Let's discuss tomorrow.

**Comment by wvangeit** [comment]
Will this now automatically be deployed on BB5 ? Or is there an extra step ?

**Comment by pramodk** [comment]
Once it merged, Jenkins is supposed to trigger the deployment.

But @matz-e noticed some hiccups recently due to some Jenkins plugin updates. @matz-e, could you confirm the recent status?

**Comment by pramodk** [comment]
Just to add : this is begin investigated in : https://bbpteam.epfl.ch/project/issues/browse/HELP-10129

As GitHub triggers are not working with Jenkins, modules are getting deployed on nightly basis.

**Comment by pramodk** [comment]
FYI, issue with auto-deployment after GitHub merge [seems to be solved](https://bbpcode.epfl.ch/ci/blue/organizations/jenkins/hpc.spack-deployment/detail/hpc.spack-deployment/1006/pipeline).

@wvangeit  : bglibpy modules are deployed on BB5: 

```
------------------------------------ /gpfs/bbp.cscs.ch/apps/hpc/jenkins//modules/applications/2019-04/tcl/linux-rhel7-x86_64 ------------------------------------
brainbuilder/0.10.2/python3            neurodamus-hippocampus/0.1/python3     psp-validation/0.1.12/python3          py-efel/3.0.22/python3
brainbuilder/0.10.4/python3            neurodamus-hippocampus/0.2/knl/python3 py-basalt/0.2.3/python3                py-pytouchreader/1.4.0/python3
brainbuilder/0.10.5/python3            neurodamus-hippocampus/0.2/python3     py-basalt/0.2.4/python3                reportinglib/2.5.1
brayns/0.8.0/python3                   neurodamus-neocortex/0.1/knl/python3   py-bglibpy/4.0.17/python2              reportinglib/develop
connectome-tools/0.3.0/python3         neurodamus-neocortex/0.1/python3       py-bglibpy/4.0.17/python3              spykfunc/0.13.2/python3
functionalizer/3.12.1                  neurodamus-thalamus/0.1/knl/python3    py-bluepymm/0.6.38/python2             steps/3.4.1/python3/parallel
neurodamus/hippocampus/python3         neurodamus-thalamus/0.1/python3        py-bluepymm/0.6.38/python3             synapsetool/0.4.1/parallel
neurodamus/master/python3              parquet-converters/0.3                 py-bluepyopt/1.6.56/python2            touchdetector/4.4.2
neurodamus/plasticity/knl/python3      placement-algorithm/2.0.7/python3      py-bluepyopt/1.6.56/python3
neurodamus/plasticity/python3          placement-algorithm/2.0.8/python3      py-efel/3.0.22/python2
```

@ferdonline is working on adapting our neurodamus deployments bglibpy friendly (#341).

**Comment by wvangeit** [comment]
Thanks, at first sight it seems to work.

**Pull request merged**
