### PR TITLE
Update Bash recipe from upstream

### PR DESCRIPTION
**Pull request by sergiorg-hpc**

### CODE REVIEW

**Comment by matz-e** [comment]
Why?

**Comment by pramodk** [comment]
> Why?

C++20 support from latest bash version 😉 (just kidding here 😄)

**Comment by sergiorg-hpc** [comment]
> > Why?
> 
> C++20 support from latest bash version 😉 (just kidding here 😄)

Haha 😂. @st4rl3ss and I found a way to swap the terminal from the remote session in VSCode. Although he is using his own ZSH installation, I wanted to give it a try with the latest and greatest Bash there is on Spack. Hence, the upgrade.

There is no harm in this, just a small version update.

**Review by matz-e — APPROVED** [review]
Fair enough. All shells are equal, can I expect something similar for zsh, too?

That aside, I think the installed versions on the cluster should be fine, shells are mature.

**Comment by sergiorg-hpc** [comment]
> Fair enough. All shells are equal, can I expect something similar for zsh, too?
> 
> That aside, I think the installed versions on the cluster should be fine, shells are mature.

I just checked and the `zsh` recipe is identical, except minor changes like the copyright date and others. Merged!

**Pull request merged**
