### PR TITLE
py-bluepy: update to v2.5.3

### PR DESCRIPTION
**Pull request by GianlucaFicarelli**
Update py-bluepy and relax pandas requirements

### CODE REVIEW

**Review by joni-herttuainen — DISMISSED** [review]

**Comment by GianlucaFicarelli** [comment]
@Adrien4193 I'm relaxing the py-bluepy dependency in py-bcsb to be `>=2.5.1` instead of `==2.5.1`, so we can keep only the latest version of bluepy in spack (2.5.3 with this PR, no breaking changes with 2.5.1). Is it ok?

The py-bcsb package has been added in https://github.com/BlueBrain/spack/pull/2110

**Review by joni-herttuainen — APPROVED** [review]

**Comment by GianlucaFicarelli** [comment]
@matz-e is it possible to retry https://bbpgitlab.epfl.ch/hpc/module-testing/-/jobs/977659 without restarting the full CI?

**Comment by Adrien4193** [comment]
If it is compatible it is ok for me.

**Comment by mgeplf** [comment]
@Adrien4193 > If it is compatible it is ok for me.
Note that bluepy is basically in maintenance mode, and that the transition to bluepysnap should be starting for circuits that are SONATA compatible.  There is documentation and examples about how this transtion can happen.

**Review by Adrien4193 — APPROVED** [review]

**Pull request merged**
