### PR TITLE
Marconi and Galileo system update @ CINECA

### PR DESCRIPTION
**Pull request by pramodk**

### CODE REVIEW

**Review by matz-e — DISMISSED** [review]

**Comment by matz-e** [comment]
Retest this please

**Comment by pramodk** [comment]
@jorblancoa : please take a look.

**Review by jorblancoa — DISMISSED** [review]

**Review by matz-e — APPROVED** [review]
Looks OK to me.

BTW, the Spack environments should be concretized together… I'm wondering if we couldn't use those more.

**Comment by pramodk** [comment]
> BTW, the Spack environments should be concretized together… I'm wondering if we couldn't use those more.

Environments seems like quite popular now. I never get time to look at that. If you see those as useful in our workflows, we should introduce those slowly.

**Pull request merged**
