### PR TITLE
make binaries from pngquant module available for bbp-analysis-framework

### PR DESCRIPTION
**Pull request by genric**

### CODE REVIEW

**Comment by pramodk** [comment]
@genric : to reduce the #modules, what if we do this via setup_run_environemnt method? (I.e. add PATH to the module of bbp-analysis-framework directly)

**Review by matz-e — CHANGES_REQUESTED** [review]
I concur with @pramodk, please this to `bbp-analysis-framework`:
```python
def setup_run_environment(self, env):
     env.prepend_path('PATH', self.spec['pngquant'].prefix.bin
```

**Comment by genric** [comment]
Done.

**Comment by matz-e** [comment]
> Done.

Tested and works?

**Comment by genric** [comment]
> > Done.
> 
> Tested and works?

Yep.

**Review by matz-e — APPROVED** [review]

**Comment by matz-e** [comment]
> > > Done.
> > 
> > 
> > Tested and works?
> 
> Yep.

All good then!

**Pull request merged**
