### PR TITLE
Adjust installation directory for software to have a specific prefix.

### LINKED ISSUE #177: Should use SPACK_INSTALL_PATH instead of INSTALL_PATH
From README instructions, it is required to export INSTALL_PATH environment variable

```
export INSTALL_PATH=$HOME/software
```

This variable is a way to global and could conflict with existing installations. Variable should be named `SPACK_INSTALL_PREFIX` for instance.

### PR DESCRIPTION
**Pull request by matz-e**
Fixes #177.

### CODE REVIEW

**Review by tristan0x — APPROVED** [review]
I didn't find any other relevant occurence of `INSTALL_PATH` in spack repository. This has a major impact on BB5. Existing spack users should be informed of this change

**Comment by matz-e** [comment]
Done via Slack for our team.

@arsenius7 this will maybe affect you: instead of exporting `INSTALL_PATH`, please set `SPACK_INSTALL_PATH` if you are using a `config.yaml` symlinked from `/gpfs/…/hpc/jenkins`

**Comment by tristan0x** [comment]
@arsenius7 this is actually `SPACK_INSTALL_PREFIX`, not `SPACK_INSTALL_PATH`.

**Comment by arsenius7** [comment]
OK, thanks.

**Comment by matz-e** [comment]
Ooops, sorry!

**Pull request merged**
