### PR TITLE
py-libsonata: Bump to 0.1.5

### PR DESCRIPTION
**Pull request by jorblancoa**

### CODE REVIEW

**Review by sergiorg-hpc — APPROVED** [review]

**Review by matz-e — APPROVED** [review]

**Comment by jorblancoa** [comment]
module-testing fails
https://bbpcode.epfl.ch/ci/blue/organizations/jenkins/hpc.module-testing/detail/hpc.module-testing/2736/pipeline

Any ideas?

**Comment by matz-e** [comment]
> module-testing fails
> https://bbpcode.epfl.ch/ci/blue/organizations/jenkins/hpc.module-testing/detail/hpc.module-testing/2736/pipeline
> 
> Any ideas?

Yes. Something rebuild some Python package using GCC for the C++ part, as some env variable may be missing. Remind me tomorrow to backport this.

**Comment by jorblancoa** [comment]
retest this please jenkins

**Comment by jorblancoa** [comment]
retest this please jenkins

**Pull request merged**
