### PR TITLE
First deployment draft.

### PR DESCRIPTION
**Pull request by matz-e**
@pramodk to give this some visibility, also to other people.

I've just copied the files from `spack_deploy` into the `deploy/` subdirectory, including the README. We should make further changes here, I'll add a commit next that trims down the amount of packages we generate for testing.

### CODE REVIEW

**Comment by pramodk** [comment]
Add action items as we find them : 

- [x] If one of the compiler installation fails, configure_compilers should be called for all compilers
- [x] Intel packages might fail during re-installation, remove `$HOME/intel/.pset ` directory (see spack/spack/issues/9713)
- [x] store all variants in `packages.yaml`
- [x] two builds run concurrently on Jenkins agent `bb5-full`? (I was expected it to run one after another as there is a single executor; see builds [14](https://bbpcode.epfl.ch/ci/blue/organizations/jenkins/hpc.spack-deployment/detail/hpc.spack-deployment/14/pipeline) and [15](https://bbpcode.epfl.ch/ci/blue/organizations/jenkins/hpc.spack-deployment/detail/hpc.spack-deployment/15/pipeline))
- [x] if compilers and tools built before 12:00AM and libraries/application on next day, is there any issue?
- [x] [store unit test results properly](https://bbpteam.epfl.ch/project/issues/browse/HPCTM-1152)
- [ ] makes module path as env variable in `config.yaml` that can be updated for monthly deployment
- [ ] move commercial packages (e.g. intel, allinea, cuda, mpis) to tools
- [ ] activate python packages so that they appear in `packages.yaml`
   > just added this. Need to verify what happens when a newer version/different version of a python package gets installed. `-f` for activate just skips dependencies, does not overwrite other versions.
- [x] update spack config or jenkins executor to run with 36 processes? 72 might be overkill
- [x] py-numpy to use intel-mkl instead of openblas in GNU toolchain?
- [x] identify duplicate installations, update specs / version preferences to avoid redundancy 
- [x]  are there any failures in applications and libraries? see [1](https://bbpcode.epfl.ch/ci/job/hpc.spack-deployment/14/artifact/stacks/applications.xml) and [2](https://bbpcode.epfl.ch/ci/job/hpc.spack-deployment/14/artifact/stacks/libraries.xml)
- [x] hdf5, neuron (and spark?) exclude in export as those non-mpi versions will be preferred for concretisation
- [x] module path should be prepended to avoid writing to system compilers!
- [x] do not use source & binary cache for applications  (to avoid `@develop` being cached, it should be always fetched from repo and built from source)
```
==> Compilers are defined in the following files:
    /gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment/install/compilers/1970-01-03/data/.spack/compilers.yaml
    /gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment/install/compilers/1970-01-03/data/.spack/linux/compilers.yaml
/gpfs/bbp.cscs.ch/apps/compilers/install/pgi-18.4/linux86-64/18.4/bin is not writable
cp: cannot create regular file ‘/gpfs/bbp.cscs.ch/apps/compilers/install/pgi-18.4/linux86-64/18.4/bin/localrc.bbpv1’: Permission denied
```

**Comment by matz-e** [comment]
>     * [ ]  two builds run concurrently on Jenkins agent `bb5-full`? (I was expected it to run one after another as there is a single executor; see builds [14](https://bbpcode.epfl.ch/ci/blue/organizations/jenkins/hpc.spack-deployment/detail/hpc.spack-deployment/14/pipeline) and [15](https://bbpcode.epfl.ch/ci/blue/organizations/jenkins/hpc.spack-deployment/detail/hpc.spack-deployment/15/pipeline))
/hpc.spack-deployment/14/artifact/stacks/applications.xml) and [2](https://bbpcode.epfl.ch/ci/job/hpc.spack-deployment/14/artifact/stacks/libraries.xml)

Fixed in the configuration; I had it in my mind that concurrent builds had to be *enabled*, but they have to be explicitly *disabled*.

**Comment by matz-e** [comment]
>     * [ ]  if compilers and tools built before 12:00AM and libraries/application on next day, is there any issue?

Since the next stage will always take the last parent directory, I don't think that this will be an issue.

**Comment by pramodk** [comment]
Summary of the updates / bug fixes : 

* pyarrow arrow was missing numpy dependency : 

```
-- Found PythonLibs: some-path/linux-rhel7-x86_64/gcc-6.4.0/python-3.6.5-sltypve7z5/lib/libpython3.6m.so
CMake Error at cmake_modules/FindNumPy.cmake:62 (message):
  NumPy import failure:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named 'numpy'

Call Stack (most recent call first):
  CMakeLists.txt:197 (find_package)
-- Configuring incomplete, errors occurred!
See also "/tmp/kumbhar/spack-stage/spack-stage-w3eF9R/pyarrow-0.11.0/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
See also "/tmp/kumbhar/spack-stage/spack-stage-w3eF9R/pyarrow-0.11.0/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeError.log".
error: command 'cmake' failed with exit status 1
==> Error: ProcessError: Command exited with status 1:
    'some-path/linux-rhel7-x86_64/gcc-6.4.0/python-3.6.5-sltypve7z5/bin/python3.6' '-s' 'setup.py' '--no-user-cfg' 'build_ext' '--with-parquet'

###   pyarrow-0.11.0/CMakeLists.txt has

find_package(PythonLibsNew REQUIRED)
find_package(NumPy REQUIRED)
include(UseCython)
```

* when spark is external package, spykfunc can't access `spec['java']` as dependency DAG is trimmed. As a "workaround", added `java` as direct dependency in `spykfunc`.

```
==> Installing spykfunc
==> Error: KeyError: 'No spec with name java in spykfunc@0.11.0%gcc@6.4.0 arch=linux-rhel7-x86_64  ^arrow@0.11.0%gcc@6.4.0 build_type=Release +parquet+python arch=linux-rhel7-x86_64  ^binutils@2.31.1%gcc@6.4.0+gold~libiberty+nls~plugins arch=linux-rhel7-x86_64  ^boost@1.68.0%gcc@6.4.0+atomic+chrono~clanglibcpp cxxstd=default
         71        run_env.set('HADOOP_HOME', self.spec['hadoop'].prefix)
  >>     72        run_env.set('JAVA_HOME', self.spec['java'].prefix)
         73        run_env.set('SPARK_HOME', self.spec['spark'].prefix)
```

* Readline LIBRARY_PATH path is not brought by neuron. Added readline as direct dependency in neurodamus. 

```
libtool: link: /opt/hpe/hpc/mpt/mpt-2.16/bin/mpicxx -O2 -g -o special some-path/linux-rhel7-x86_64/intel-18.0.3/neuron-2018-10-6e2yclxgoi/x86_64/lib/nrnmain.o some-path/linux-rhel7-x86_64/intel-18.0.3/neuron-2018-10-6e2yclxgoi/x86_64/lib/ivocmain.o some-path/linux-rhel7-x86_64/intel-18.0.3/neuron-2018-10-6e2yclxgoi/x86_64/lib/nvkludge.o ALU.o ASCIIrecord.o BinReportHelper.o BinReports.o BK.o cacum_hip.o CaDynamics_DC0_hip.o CaDynamics_DC0.o CaDynamics_DC1.o CaDynamics_DC2.o CaDynamics_DC_hip.o CaDynamics_E2.o CaDynamics_E3.o CaDynamics_E.o cagk_hip.o Ca_HVA2.o cahva_hip.o Ca_HVA.o _calcium2.o _calciumc_concentration.o calcium_dynamics.o _calcium.o calcium_shaul.o cal_hip.o calva_hip.o Ca_LVA.o Ca_LVAs.o Ca_LVAst.o Ca.o can_hip.o cat_hip.o CoreConfig.o _CSA.o _CSK.o DetAMPANMDA.o DetGABAAB.o epsp.o gap.o GluSynapse.o _GNoise.o HCN1_0061.o HCN2_0062.o HCN3_0063.o hcn3.o HCN4_0064.o hd2_hip.o hdf5.o hdf5new.o HDF5reader.o HDF5record.o hd_hip.o h_hip.o HHK1.o HHK2.o HHK3.o HHK_MC.o HHK.o _iAHP.o Ih.o IM2.o _iM.o Im.o ISynAMPAEx.o ISynNMDAEx.o kad2_hip.o kad_hip.o KahpM95_hip.o kap2_hip.o kap_hip.o KCa1.o KCa2.o KCa3.o Kd.o kdr2_hip.o kdr_hip.o KdShu2007.o Kfast10oct07.o Kfast_E.o Kfast.o Kfast_S.o km1.o km2_hip.o km_hip.o K_P.o K_Ps.o K_Pst.o Kslow10oct07.o Kslow_E.o Kslow.o Kslow_S.o K_T.o K_Ts.o K_Tst.o Kv1_1.o Kv1_2.o Kv1_3.o Kv1_4.o Kv1_5.o Kv1_6.o Kv2_1.o Kv2_2.o Kv3_1.o Kv3_3.o Kv3_4.o lookupTableV2.o memoryaccess.o MemUsage.o Na10oct07.o na2.o na3_hip.o na4_hip.o Na_E.o na_hip.o Na.o Nap_E.o Nap_Et2.o Nap.o Na_S.o NaTa_t.o NaTaxon.o NaTg2.o NaTg.o NaTs2_t.o NaTs.o Nav1_6.o nax_hip.o netstim_inhpoisson.o new_calcium_channels.o _outside_calcium_concentration.o ProbAMPA.o ProbAMPANMDA_EMS.o ProbAMPANMDA.o ProbGABAAB_EMS.o ProbGABAA_EMS.o ProbGABAA.o ProbNMDA.o ProfileHelper.o pump.o sk2_hip.o SK_E2.o SK_E.o sk_hip.o SK_S.o SKv3_1.o SKv3_1t.o SpikeWriter.o StdpWADoublet.o StdpWATriplet.o StochKv2.o StochKv3.o StochKv.o SynapseReader.o tmgExSyn.o tmgInhSyn.o traub.o TTXDynamicsSwitch.o utility.o VecStim.o xtra.o mod_func.o  -L/gpfs/bbp.cscs.ch/project/proj16/kumbhar/tmp/install/linux-rhel7-x86_64/gcc-6.4.0/synapsetool-0.3.2-7zsaap/lib64 -lsyn2 -Lsome-path/linux-rhel7-x86_64/gcc-6.4.0/boost-1.68.0-axz6nzwljj/lib -lboost_system-mt -lboost_filesystem-mt -L/gpfs/bbp.cscs.ch/project/proj16/kumbhar/tmp/install/linux-rhel7-x86_64/gcc-6.4.0/coreneuron-plasticity-mqixqr/lib64 -lcoreneuron -L/gpfs/bbp.cscs.ch/project/proj16/kumbhar/tmp/install/linux-rhel7-x86_64/gcc-6.4.0/reportinglib-develop-j6xfqk/lib64 -lreportinglib -Lsome-path/linux-rhel7-x86_64/gcc-6.4.0/hdf5-1.10.3-qvyixse54y/lib some-path/linux-rhel7-x86_64/gcc-6.4.0/hdf5-1.10.3-qvyixse54y/lib/libhdf5.so -Lsome-path/linux-rhel7-x86_64/gcc-6.4.0/zlib-1.2.11-w43e56tzqj/lib -lz -Lsome-path/linux-rhel7-x86_64/intel-18.0.3/neuron-2018-10-6e2yclxgoi/x86_64/lib some-path/linux-rhel7-x86_64/intel-18.0.3/neuron-2018-10-6e2yclxgoi/x86_64/lib/libnrnoc.so some-path/linux-rhel7-x86_64/intel-18.0.3/neuron-2018-10-6e2yclxgoi/x86_64/lib/libnrniv.so some-path/linux-rhel7-x86_64/intel-18.0.3/neuron-2018-10-6e2yclxgoi/x86_64/lib/libivoc.so some-path/linux-rhel7-x86_64/intel-18.0.3/neuron-2018-10-6e2yclxgoi/x86_64/lib/liboc.so some-path/linux-rhel7-x86_64/intel-18.0.3/neuron-2018-10-6e2yclxgoi/x86_64/lib/libneuron_gnu.so some-path/linux-rhel7-x86_64/intel-18.0.3/neuron-2018-10-6e2yclxgoi/x86_64/lib/libscopmath.so some-path/linux-rhel7-x86_64/intel-18.0.3/neuron-2018-10-6e2yclxgoi/x86_64/lib/libsparse13.so some-path/linux-rhel7-x86_64/intel-18.0.3/neuron-2018-10-6e2yclxgoi/x86_64/lib/libsundials.so some-path/linux-rhel7-x86_64/intel-18.0.3/neuron-2018-10-6e2yclxgoi/x86_64/lib/libnrnmpi.so some-path/linux-rhel7-x86_64/intel-18.0.3/neuron-2018-10-6e2yclxgoi/x86_64/lib/libmemacs.so some-path/linux-rhel7-x86_64/intel-18.0.3/neuron-2018-10-6e2yclxgoi/x86_64/lib/libmeschach.so some-path/linux-rhel7-x86_64/intel-18.0.3/neuron-2018-10-6e2yclxgoi/x86_64/lib/libivos.so -lreadline -lncurses some-path/linux-rhel7-x86_64/intel-18.0.3/neuron-2018-10-6e2yclxgoi/x86_64/lib/libnrnpython.so /gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment/install/compilers/2018-11-23/linux-rhel7-x86_64/gcc-4.8.5/gcc-6.4.0-nm7hcmfc6b/lib/../lib64/libstdc++.so -Lsome-path/linux-rhel7-x86_64/intel-18.0.3/python-2.7.15-a5avapuzfm/lib -lpython2.7 -lpthread -lutil -lm -ldl -Wl,-rpath -Wl,some-path/linux-rhel7-x86_64/gcc-6.4.0/hdf5-1.10.3-qvyixse54y/lib -Wl,-rpath -Wl,some-path/linux-rhel7-x86_64/intel-18.0.3/neuron-2018-10-6e2yclxgoi/x86_64/lib -Wl,-rpath -Wl,/gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment/install/compilers/2018-11-23/linux-rhel7-x86_64/gcc-4.8.5/gcc-6.4.0-nm7hcmfc6b/lib/../lib64 -Wl,-rpath -Wl,some-path/linux-rhel7-x86_64/gcc-6.4.0/hdf5-1.10.3-qvyixse54y/lib -Wl,-rpath -Wl,some-path/linux-rhel7-x86_64/intel-18.0.3/neuron-2018-10-6e2yclxgoi/x86_64/lib -Wl,-rpath -Wl,/gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment/install/compilers/2018-11-23/linux-rhel7-x86_64/gcc-4.8.5/gcc-6.4.0-nm7hcmfc6b/lib/../lib64 -Wl,-rpath -Wl,some-path/linux-rhel7-x86_64/intel-18.0.3/python-2.7.15-a5avapuzfm/lib
/usr/bin/ld: cannot find -lreadline
```

* Added python 3 compatible version of py-dbf and removed py-enum34 dependency 

* Added parquet-converters version 0.2 instead of 0.2.1

**Comment by pramodk** [comment]
Observations from recent build:

- [ ] can we make below error message concise / one liner ? below is too verbose : 

```
==> Error: 
 /dev/shm/jenkins/tmpEuc0Fz/gcc-6.4.0-i6lyqfscua/bin/x86_64-pc-linux-gnu-gcc-ranlib 
contains string
 /gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment/install/compilers/1357-01-01 
after replacing it in rpaths.
Package should not be relocated.
 Use -a to override.
```
- [ ] patchelf recurssion ([see](https://bbpcode.epfl.ch/ci/blue/organizations/jenkins/hpc.spack-deployment/detail/hpc.spack-deployment/161/pipeline/31)). In serial-libraries, its even worse!
```
....
==> Searching for binary cache of patchelf
==> Installing patchelf from binary cache
==> Already downloaded /gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment/deploy/spack/var/spack/stage/build_cache/linux-rhel7-x86_64-gcc-4.8.5-patchelf-0.9-xuekuiiyp7w6r2jfm77wvggut5incnor.spack
==> Relocating package from
  /gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment/install/compilers/1234-12-12 to /gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment/install/compilers/1357-01-01.
==> Installing patchelf
==> Searching for binary cache of patchelf
==> Installing patchelf from binary cache
==> Already downloaded /gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment/deploy/spack/var/spack/stage/build_cache/linux-rhel7-x86_64-gcc-4.8.5-patchelf-0.9-xuekuiiyp7w6r2jfm77wvggut5incnor.spack
==> Relocating package from
  /gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment/install/compilers/1234-12-12 to /gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment/install/compilers/1357-01-01.
==> Installing patchelf
==> Searching for binary cache of patchelf
==> Installing patchelgpg: Signature made Thu 06 Dec 2018 05:26:46 PM CET using RSA key ID A719D8B3
gpg: Good signature from "Don't trust me™ (GPG created for Spack) <fake.bbp@epfl.ch>"
gpg: Signature made Thu 06 Dec 2018 05:26:46 PM CET using RSA key ID A719D8B3
gpg: Good signature from "Don't trust me™ (GPG created for Spack) <fake.bbp@epfl.ch>"
gpg: Signature made Thu 06 Dec 2018 05:26:46 PM CET using RSA key ID A719D8B3
gpg: Good signature from "Don't trust me™ (GPG created for Spack) <fake.bbp@epfl.ch>"
==> Error: maximum recursion depth exceeded in __instancecheck__
f from binary cache
==> Already downloaded /gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment/deploy/spack/var/spack/stage/build_cache/linux-rhel7-x86_64-gcc-4.8.5-patchelf-0.9-xuekuiiyp7w6r2jfm77wvggut5incnor.spack
==> Relocating package from
```

- [x] show spec name along with hash during caching : `### 20:23:06 ...caching aitwg5q`

- [x] bzip2 rpath is not properly updated? 

```
==> No binary for boost found: installing from source
bzip2: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
/bin/tar: Child returned status 127
/bin/tar: Error is not recoverable: exiting now
```

if I look at binary:

```
$ objdump -x /gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment/install/serial-libraries/1357-01-01/linux-rhel7-x86_64/gcc-6.4.0/bzip2-1.0.6-lcfurlokv3/bin/bzip2 | grep RPA
  RPATH                /gpfs/bbp.cscs.ch/apps/compilers/install/gcc-6.4.0/lib:/gpfs/bbp.cscs.ch/apps/compilers/install/gcc-6.4.0/lib64:@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@/linux-rhel7-x86_64/gcc-6.4.0/bzip2-1.0.6-lcfurlokv3/lib:@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@/linux-rhel7-x86_64/gcc-6.4.0/bzip2-1.0.6-lcfurlokv3/lib64
```
~~I wonder if we should do static build for bzip2 (bzip2 is special case where binary is used during build stage of packages).~~
Edit : I couldn't re-produce the above rpath issue locally.

**Comment by pramodk** [comment]
this has been already push forced to develop

**Pull request closed without merging**
