### PR TITLE
Simulation Software Updates - October release

### PR DESCRIPTION
**Pull request by ferdonline**
* Adding neurodamus-core 2.7.1 
* Update Neurodamus spack recipe: Removing sonata variant not used
* synapsetool: bump to 0.5.4

### CODE REVIEW

**Comment by ferdonline** [comment]
I think releasing a new simulation stack every month is enough (critical fixes should be exceptions).
Like this we avoid the mess of the 100s of installed but unused versions

**Comment by pramodk** [comment]
I would like to integrate support for current report from @iomaganaris in this release. It will be great addition!

**Review by matz-e — APPROVED** [review]

**Comment by ferdonline** [comment]
@pramodk @matz-e When shall we merge this?

**Comment by pramodk** [comment]
@ferdonline : I just bump up the neurodamus-core version [here](https://github.com/BlueBrain/spack/pull/528/commits/e3e5496f6136ebc3608376cc161af12901dc47d4).

**Review by pramodk — APPROVED** [review]
Once CI passes, we should merge this. Also importantly, we have to send email notification to users tomorrow.

**Review by iomaganaris — APPROVED** [review]

**Comment by ferdonline** [comment]
Was any notification sent out?

**Pull request merged**
