### PR TITLE
Remove compiler name from modules

### PR DESCRIPTION
**Pull request by pramodk**

### CODE REVIEW

**Comment by pramodk** [comment]
@ohm314 : ping!

**Comment by timocafe** [comment]
Pong

Envoyé de mon GameBoy

**Review by ohm314 — APPROVED** [review]
I agree if modules are only generated for select packages. The spack build path should, however, contain the compiler name/version for clarity.

**Comment by pramodk** [comment]
> The spack build path should, however, contain the compiler name/version for clarity.

Install path scheme has that already : 

```
install_path_scheme: '${ARCHITECTURE}/${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}-${HASH:6}'
```

**Comment by pramodk** [comment]
>Pong
> Envoyé de mon GameBoy

@timocafe   :)

**Pull request merged**
