### PR TITLE
Keep ascii decoding errors from popping up.

### PR DESCRIPTION
**Pull request by matz-e**

### CODE REVIEW

**Review by ohm314 — APPROVED** [review]
seems reasonable, given that `gcc` otherwise generates quoted strings, which are not properly processed by spack

**Comment by ferdonline** [comment]
Maybe on the neurodamus side we can replace results after building with the new locale settings. We don't expect users to build neurodamus by themselves (If they do they can't anyway complain to us)

**Comment by matz-e** [comment]
@pramodk I'm merging this. I've played around with other settings, and GCC does not behave as expected. Attempting to fix this in the printout with `encode`/`decode` has been futile so far.

**Comment by pramodk** [comment]
Ok..👍

**Pull request merged**
