### PR TITLE
deployment: only cache and install when actionable.

### PR DESCRIPTION
**Pull request by matz-e**

### CODE REVIEW

**Comment by matz-e** [comment]
Retest this please

**Comment by matz-e** [comment]
Retest this please

**Comment by matz-e** [comment]
Retest this please

**Comment by matz-e** [comment]
@pramodk checked with neuron as discussed, and quite a few of the applications got rebuilt. The other optimizations that I played with don't seem to improve our deployment, probably since we build on an SSD file system rather than the HDDs that back my home.

**Review by pramodk — APPROVED** [review]

**Pull request merged**
