### PR TITLE
Update the coreneuron version to commit 846b3a6

### PR DESCRIPTION
**Pull request by WeinaJi**

### CODE REVIEW

**Review by ferdonline — DISMISSED** [review]

**Review by matz-e — DISMISSED** [review]

**Comment by pramodk** [comment]
this CI fails because GPU build of coreneuron uses nvcc (cuda) and that requires newer GCC than system 4.8.5 cc: @olupton 

@matz-e : our generated `compilers.yaml` has:

```
- compiler:
    spec: nvhpc@20.9
    modules: [/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/externals/2021-01-06/modules/tcl/linux-rhel7-x86_64/nvhpc/20.9]
    paths:
      cc: /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/externals/2021-01-06/linux-rhel7-x86_64/gcc-9.3.0/nvhpc-20.9-rqj5oq/Linux_x86_64/20.9/compilers/bin/nvc
      cxx: /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/externals/2021-01-06/linux-rhel7-x86_64/gcc-9.3.0/nvhpc-20.9-rqj5oq/Linux_x86_64/20.9/compilers/bin/nvc++
      f77: /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/externals/2021-01-06/linux-rhel7-x86_64/gcc-9.3.0/nvhpc-20.9-rqj5oq/Linux_x86_64/20.9/compilers/bin/nvfortran
      fc: /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/externals/2021-01-06/linux-rhel7-x86_64/gcc-9.3.0/nvhpc-20.9-rqj5oq/Linux_x86_64/20.9/compilers/bin/nvfortran
    flags: {}
    operating_system: rhel7
    target: x86_64
    environment: {}
    extra_rpaths: []
- compiler:
    spec: nvhpc@21.2
    modules: [/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/externals/2021-01-06/modules/tcl/linux-rhel7-x86_64/nvhpc/21.2]
    paths:
      cc: /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/externals/2021-01-06/linux-rhel7-x86_64/gcc-9.3.0/nvhpc-21.2-67d2qp/Linux_x86_64/21.2/compilers/bin/nvc
      cxx: /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/externals/2021-01-06/linux-rhel7-x86_64/gcc-9.3.0/nvhpc-21.2-67d2qp/Linux_x86_64/21.2/compilers/bin/nvc++
      f77: /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/externals/2021-01-06/linux-rhel7-x86_64/gcc-9.3.0/nvhpc-21.2-67d2qp/Linux_x86_64/21.2/compilers/bin/nvfortran
      fc: /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/externals/2021-01-06/linux-rhel7-x86_64/gcc-9.3.0/nvhpc-21.2-67d2qp/Linux_x86_64/21.2/compilers/bin/nvfortran
    flags: {}
```

One option is in the `    modules: ` key we can load `gcc` before loading nvhpc (typical approach used in Cray environment)

**Comment by matz-e** [comment]
@pramodk shouldn't `nvhpc` then autoload `gcc` as a general rule?

**Comment by pramodk** [comment]
Yes exactly. But that's what `modules` key in `compilers.yaml` does, right? (as compiler is not dependency, what is another way to achieve this? 🤔 )

**Comment by matz-e** [comment]
> Yes exactly. But that's what `modules` key in `compilers.yaml` does, right? (as compiler is not dependency, what is another way to achieve this? thinking )

Regular `autoload`. But since `gcc` is not a direct dependency, that'll involve some hacks. Thus I'd rather prefer to shim the `gcc` module into the `module` keys there.

**Comment by pramodk** [comment]
>  But since gcc is not a direct dependency, that'll involve some hacks. Thus I'd rather prefer to shim the gcc module into the module keys there.

Yup, thats what I meant as well.

**Comment by WeinaJi** [comment]
The deployment test build still fails.
```
[2021-10-11T13:18:24.060Z] + spack-check /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/pulls/1321/config/modules.sh
[2021-10-11T13:18:24.060Z] /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/pulls/1321/spack/deploy/bin/spack-check: line 8: /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/pulls/1321/config/modules.sh: No such file or directory
script returned exit code 1
```
What does this error mean ? @matz-e

**Comment by pramodk** [comment]
I am fixing above error. Just few more minutes...

**Comment by pramodk** [comment]
By the way, actual errors are shown under Test: https://bbpcode.epfl.ch/ci/blue/organizations/jenkins/hpc.spack-deployment.pull-requests/detail/hpc.spack-deployment.pull-requests/2605/tests

```console
[INFO] Running: make -j1 -f /gpfs/bbp.cscs.ch/ssd/slurmTmpFS/bbprelman/2770758/spack-stage-coreneuron-1.0.0.20211008-dbmvjvs7mrayqt6cpjjttfcx4jqowiea/spack-build-dbmvjvs/share/coreneuron/nrnivmodl_core_makefile ROOT=/gpfs/bbp.cscs.ch/ssd/slurmTmpFS/bbprelman/2770758/spack-stage-coreneuron-1.0.0.20211008-dbmvjvs7mrayqt6cpjjttfcx4jqowiea/spack-build-dbmvjvs MOD2CPP_BINARY=/gpfs/bbp.cscs.ch/ssd/slurmTmpFS/bbprelman/2770758/spack-stage-coreneuron-1.0.0.20211008-dbmvjvs7mrayqt6cpjjttfcx4jqowiea/spack-build-dbmvjvs/bin/mod2c_core MODS_PATH=x86_64/corenrn/mod2c BUILD_TYPE=STATIC NRN_PRCELLSTATE=0
Default NMODL flags:
diff: x86_64/corenrn/mod2c/_mod_func.cpp: No such file or directory
Please verify that both the operating system and the processor support Intel(R) AVX512ER and AVX512PF instructions.
```
Basically, `mod2c` binary is compiled for KNL and can't be executed on Skylake/Cascadelake nodes.

**Comment by WeinaJi** [comment]
All tests have passed. Can we merge this spack PR ?

**Review by matz-e — APPROVED** [review]
Good from my uneducated side.

**Review by olupton — APPROVED** [review]

**Pull request merged**
