### PR TITLE
matio: update to last version and to github archive

### PR DESCRIPTION
**Pull request by alkino**
sourceforce is really slow and sometimes hangout

### CODE REVIEW

**Comment by tristan0x** [comment]
which packages require libmatio?

**Comment by alkino** [comment]
> which packages require libmatio?

trilinos

**Comment by alkino** [comment]
retest this please Jenkins

**Comment by alkino** [comment]
retest this please Jenkins

**Comment by alkino** [comment]
@tristan0x do you want to accept this?

**Review by matz-e — APPROVED** [review]
Sourceforge has essentially rendered itself useless by now…

**Pull request merged**
