### PR TITLE
brion: Deploy both brion 3.1.0 and 3.2.0

### PR DESCRIPTION
**Pull request by jorblancoa**
- Both needed by different packages

### CODE REVIEW

**Comment by tomdele** [comment]
Hope we will be fine with this one !!

**Comment by jorblancoa** [comment]
The CI fails when testing brion/3.2.0
https://bbpcode.epfl.ch/ci/blue/organizations/jenkins/hpc.module-testing/detail/hpc.module-testing/2152/pipeline/

` python -c 'import brain'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'brain'`

Maybe @ppodhajski knows what could be the issue? Does the test needs to be updated for brion 3.2.0? it was working before for 3.1.0

**Comment by ppodhajski** [comment]
looking into it now and looping in @NadirRoGue

**Comment by ppodhajski** [comment]
@jorblancoa will have a patch today

**Comment by ppodhajski** [comment]
merged https://github.com/BlueBrain/spack/pull/836

**Comment by ppodhajski** [comment]
retest this please

**Review by pramodk — APPROVED** [review]

**Pull request merged**
