### PR TITLE
Deploy Regiodesics 0.1.2

### PR DESCRIPTION
**Pull request by lguyot**
**Change log:**

-  nrrd header management fix (space directions field)

- simplified interface for direction vectors computations [BBPP2-310]

### CODE REVIEW

**Review by matz-e — APPROVED** [review]

**Comment by lguyot** [comment]
Retest this please

**Comment by lguyot** [comment]
Retest this please

**Comment by matz-e** [comment]
That's a weird failure! I'll investigate tomorrow

**Comment by matz-e** [comment]
For good measure:

Retest this please

**Comment by matz-e** [comment]
Starting with a fresh build, deleted old build directory

Retest this please

**Comment by matz-e** [comment]
@lguyot could you please rebase this on top of the latest `develop`? There were some fundamental changes merged in the last few days

**Comment by lguyot** [comment]
@matz-e Done. Does it help?

**Comment by matz-e** [comment]
@lguyot, yes, thank you!

We recently switched compilers, and "older" pull requests don't handle such a change well.

**Pull request merged**
