### PR TITLE
add GLM flag to Brayns

### PR DESCRIPTION
**Pull request by ppodhajski**

### CODE REVIEW

**Review by NadirRoGue — DISMISSED** [review]

**Review by matz-e — DISMISSED** [review]

**Comment by ppodhajski** [comment]
retriggering travis-ci as I got this meaningful error on worker

```There was an error in the .travis.yml file from which we could not recover.
Unfortunately, we do not know much about this error.```

**Comment by ppodhajski** [comment]
retest this please

**Comment by matz-e** [comment]
> retriggering travis-ci as I got this meaningful error on worker
> 
> ```
> Unfortunately, we do not know much about this error.```
> ```

Awesome! Upstream switched to Github™ Actions®, we're going to follow with the new deployment… coming real soon!

**Comment by matz-e** [comment]
Retest this please

Purged the build directory which was based on the previous deployment.

**Review by matz-e — APPROVED** [review]
Looks good to me, @ppodhajski, @NadirRoGue if you still need this

**Comment by NadirRoGue** [comment]
I just tested this because I completely forgot about it. It works, and is picking the correct glm from the modules

`[+] /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/libraries/2021-01-06/linux-rhel7-x86_64/gcc-9.3.0/glm-0.9.9.3-5nwixo`

For me its fine, @ppodhajski ?

**Comment by NadirRoGue** [comment]
This PR is not needed anymore, thanks.

**Pull request closed without merging**
