### PR TITLE
deploy neurodamus-core/neorcortex/hippocampus/mousify/thalamus/py-neurodamus/libsonata-report

### PR DESCRIPTION
**Pull request by WeinaJi**
**Updates**
- Neuron 8.0a
- CoreNeuron 1.0a
- Neurodamus-core 3.2.0
- Latest sim/models
- py-neruodamus 2.4.0
- libsonata-report 0.1a

This PR is combined with #1036 #1032

### CODE REVIEW

**Review by pramodk — DISMISSED** [review]
LGTM

**Comment by pramodk** [comment]
On Monday, can you check with @jorblancoa  & @sergiorg-hpc  about any changes in coreneuron+reportinglibg/libsonata for the deployment? I am not up to date with just in case there are any updates.

**Comment by WeinaJi** [comment]
Retest this please

**Comment by jorblancoa** [comment]
retest this please

**Comment by jorblancoa** [comment]
retest this please

**Review by ferdonline — DISMISSED** [review]

**Review by matz-e — DISMISSED** [review]

**Review by pramodk — CHANGES_REQUESTED** [review]
Same as https://github.com/BlueBrain/spack/pull/1032#pullrequestreview-583145226

**Comment by WeinaJi** [comment]
@alkino  I have merged with your PR #1036 , could you please check if the change is all included ?

**Comment by jorblancoa** [comment]
Simulation stack triggered
https://bbpcode.epfl.ch/ci/blue/organizations/jenkins/hpc.SimulationStack/detail/hpc.SimulationStack/3206/pipeline

**Review by pramodk — APPROVED** [review]
LGTM

**Review by ferdonline — APPROVED** [review]

**Pull request merged**
