### PR TITLE
synapsetool: bump to 0.5.4

### PR DESCRIPTION
**Pull request by matz-e**

### CODE REVIEW

**Review by jorblancoa — APPROVED** [review]

**Comment by ferdonline** [comment]
Please use this one instead (unless there are critical changes)

**Review by ferdonline — CHANGES_REQUESTED** [review]
It will trigger simulation stack redeployment. It wold be nicer to deploy it in https://github.com/BlueBrain/spack/pull/528

**Comment by matz-e** [comment]
> It will trigger simulation stack redeployment. It wold be nicer to deploy it in #528

I'm fine with collecting commits in that PR, but would like to have it merged rather soon. Maybe an update a week if needed? Would you be able to cherry-pick this commit on top of there?

**Comment by ferdonline** [comment]
Well, we are already in October, from a calendar perspective we can deploy any time now :)

> Maybe an update a week if needed?

I agree, if there is anything critical we can shorten the cycles

> Would you be able to cherry-pick this commit on top of there?

sure, can do that.

**Comment by pramodk** [comment]
I didnt understand one thing: even if we add new version, in this kind of scenarios, why can't we keep previous one preferred and other tools explicitly depend on new version? (or vice-a-versa)

**Comment by matz-e** [comment]
> I didnt understand one thing: even if we add new version, in this kind of scenarios, why can't we keep previous one preferred and other tools explicitly depend on new version? (or vice-a-versa)

I think this is another slippery slope into dependency hell just for the sake of reducing compile time.

**Comment by pramodk** [comment]
> slippery slope into dependency hell just for the sake of reducing compile time.

No...I am not concerned by compile time but the validation aspects. We haven't linked simulation CI with deployment (we just have basic functional tests) and hence if we are re-deploying production stack with newer sonata/synapsetool library, it would be helpful to have that going through CI.

**Pull request closed without merging**
