### PR TITLE
Added support for neurodamus-thalamus+knl

### PR DESCRIPTION
**Pull request by st4rl3ss**

### CODE REVIEW

**Comment by st4rl3ss** [comment]
Check passed, I also tested the PR build and now the module "neurodamus-thalamus/0.1/python3-knl" is in the list.

**Comment by st4rl3ss** [comment]
please retest

**Review by pramodk — APPROVED** [review]

**Comment by pramodk** [comment]
Please retest

**Comment by st4rl3ss** [comment]
please retest

**Comment by st4rl3ss** [comment]
Closes HPCTM-1198.

**Pull request merged**
