### PR TITLE
deployment: fix python module location.

### PR DESCRIPTION
**Pull request by matz-e**

### CODE REVIEW

**Review by pramodk — COMMENTED** [review]
I expect python to be built in serial libraries. Even if we have python installed in external stage, I thought we decided to ignore that.

Do we chain external stage?

**Review by matz-e — COMMENTED** [review]
@pramodk I've tested this locally with `py-six`. It will register external modules correctly, even when we specify the path, and use them to autoload in module generation. I think this is the overall behavior we desire.

**Comment by matz-e** [comment]
> I expect python to be built in serial libraries. Even if we have python installed in external stage, I thought we decided to ignore that.
> 
> Do we chain external stage?

We don't chain the external stage, and we register python as an `external_path`. Serial produces the python module, but due to the way modules are handled, the python module will not be considered by subsequent stages.

**Comment by matz-e** [comment]
Please retest

`omega-h` failed due to fetching issues.

**Comment by matz-e** [comment]
@pramodk first results look good:
```
❯ head -n 25 /gpfs/bbp.cscs.ch/apps/hpc/jenkins/pulls/236/deploy/serial-libraries/2019-03-12/modules/tcl/linux-rhel7-x86_64/python-dev/0.1/python3
#%Module1.0
## Module file created by spack (https://github.com/spack/spack) on 2019-03-12 11:03:15.796712
##
## python-dev@0.1%gcc@6.4.0 arch=linux-rhel7-x86_64 /7br7bqr
##


module-whatis "Meta package to bundle python packages for development"

proc ModulesHelp { } {
puts stderr "Meta package to bundle python packages for development"
}

if { [ module-info mode load ] && ![ is-loaded python/3.6.5 ] } {
    puts stderr "Autoloading python/3.6.5"
    module load python/3.6.5
}
if { [ module-info mode load ] && ![ is-loaded hdf5/1.10.4/serial ] } {
    puts stderr "Autoloading hdf5/1.10.4/serial"
    module load hdf5/1.10.4/serial
}

prepend-path CMAKE_PREFIX_PATH "/gpfs/bbp.cscs.ch/apps/hpc/jenkins/pulls/236/deploy/serial-libraries/2019-03-12/linux-rhel7-x86_64/gcc-6.4.0/python-dev-0.1-7br7bqrkgt/"
prepend-path PYTHONPATH "/gpfs/bbp.cscs.ch/apps/hpc/jenkins/pulls/236/deploy/serial-libraries/2019-03-12/linux-rhel7-x86_64/gcc-6.4.0/py-pillow-5.1.0-v6ec3aexf4/lib/python3.6/site-packages"
prepend-path PYTHONPATH "/gpfs/bbp.cscs.ch/apps/hpc/jenkins/pulls/236/deploy/serial-libraries/2019-03-12/linux-rhel7-x86_64/gcc-6.4.0/py-ipykernel-4.5.0-a2ufflfqpy/lib/python3.6/site-packages"
```

**Comment by matz-e** [comment]
retest this please

**Comment by matz-e** [comment]
retest this please

**Review by pramodk — APPROVED** [review]

**Pull request merged**
