### PR TITLE
multi-comp-mesher: new OIST package / cgal: add 5.0.2

### PR DESCRIPTION
**Pull request by tristan0x**

### CODE REVIEW

**Review by matz-e — DISMISSED** [review]

**Comment by tristan0x** [comment]
retest this please Jenkins

**Review by matz-e — DISMISSED** [review]

**Review by pramodk — DISMISSED** [review]

**Review by pramodk — COMMENTED** [review]
@tristan0x : if you want to deploy this in production, should add some alpha version.

**Comment by tristan0x** [comment]
> @tristan0x : if you want to deploy this in production, should add some alpha version.

Thank you @pramodk 
I forgot to push a change I had on BB5 providing release v1.0.0
It should be good now.

**Comment by pramodk** [comment]
Is module needed for this? In that case we have to whitelist that.

**Comment by tristan0x** [comment]
> Is module needed for this?

Yes!

> In that case we have to whitelist that.

Done in bb6c8f8

**Comment by pramodk** [comment]
@tristan0x : still relevant?

**Comment by tristan0x** [comment]
Yes, but I didn't take the time to figure what is wrong in the cgal build

**Comment by matz-e** [comment]
@tristan0x : still relevant?

**Comment by tristan0x** [comment]
Yeah, it would be helpful to have this on BB5. I will try to work on it this week @matz-e 
Thanks

**Comment by matz-e** [comment]
5.0.3 is available by now.

**Pull request closed without merging**
