### PR TITLE
provide snakemake executable for circuit-build

### PR DESCRIPTION
**Pull request by asanin-epfl**

### CODE REVIEW

**Comment by matz-e** [comment]
Have you tested the generated module?

**Comment by asanin-epfl** [comment]
Can you advice on how to do it properly? I couldn't do it on BB5:
```
-bash-4.2$ spack install circuit-build
....
==> Successfully installed circuit-build
  Fetch: 2.66s.  Build: 4.00s.  Total: 6.66s.
[+] /gpfs/bbp.cscs.ch/home/sanin/software/install/linux-rhel7-x86_64/gcc-8.3.0/circuit-build-3.1.1-nf4ois
-bash-4.2$ ls /gpfs/bbp.cscs.ch/home/sanin/software/install/linux-rhel7-x86_64/gcc-8.3.0/circuit-build-3.1.1-nf4ois
bin  lib
-bash-4.2$ module load /gpfs/bbp.cscs.ch/home/sanin/software/install/linux-rhel7-x86_64/gcc-8.3.0/circuit-build-3.1.1-nf4ois
ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for '/gpfs/bbp.cscs.ch/home/sanin/software/install/linux-rhel7-x86_64/gcc-8.3.0'
```
```
-bash-4.2$ module load $(spack module tcl find --full-path circuit-build)
ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for '/gpfs/bbp.cscs.ch/home/sanin/software/modules/tcl/linux-rhel7-x86_64/circuit-build'
```

**Comment by matz-e** [comment]
From the FAQ:
```
  $ module purge
  $ unset MODULEPATH
  $ source /gpfs/bbp.cscs.ch/apps/hpc/jenkins/pulls/924/config/modules.sh
  $ module load unstable circuit-build
```

**Comment by asanin-epfl** [comment]
Thank you! The link to FAQ would have been sufficient.

**Comment by asanin-epfl** [comment]
I checked. It works:
```
-bash-4.2$ module purge
-bash-4.2$ unset MODULEPATH
-bash-4.2$ source /gpfs/bbp.cscs.ch/apps/hpc/jenkins/pulls/924/config/modules.sh
-bash-4.2$ module load unstable circuit-build
Autoloading python/3.7.4
-bash-4.2$ snakemake
Error: no Snakefile found, tried Snakefile, snakefile, workflow/Snakefile, workflow/snakefile.
-bash-4.2$ 
```

**Comment by matz-e** [comment]
> Thank you! The link to FAQ would have been sufficient.

Didn't have an anchor to the item :)

**Review by matz-e — APPROVED** [review]

**Pull request merged**
