### PR TITLE
Adding docopt as a dependency to neurodamus+python

### PR DESCRIPTION
**Pull request by ferdonline**

### CODE REVIEW

**Review by iomaganaris — APPROVED** [review]
LGTM

**Comment by ferdonline** [comment]
Already updated the commit message in neurodamus-py change

**Comment by matz-e** [comment]
why?

**Comment by ferdonline** [comment]
> why?

Dont worry, I'm planning to soon have a proper neurodamus-python package.

**Comment by matz-e** [comment]
> > why?
> 
> Dont worry, I'm planning to soon have a proper neurodamus-python package.

I'm more for barebones `argparse`. Just checked, and `docopt` had it's last commit nearly 1.5 years ago, I would suspect `click` to be similar…

**Comment by ferdonline** [comment]
Until we decide to get rid of it...

**Pull request merged**
