### PR TITLE
deploy: add py-basalt module

### PR DESCRIPTION
**Pull request by tristan0x**

### CODE REVIEW

**Review by matz-e — APPROVED** [review]
LGTM. Don't see any random Yaml changes.

**Comment by tristan0x** [comment]
> LGTM. Don't see any random Yaml changes.

I can't believe I did it right the first time! Thanks @matz-e

**Comment by matz-e** [comment]
CI will tell. Retest this please.

**Comment by tristan0x** [comment]
\o/

**Comment by matz-e** [comment]
```
❯ . /gpfs/bbp.cscs.ch/apps/hpc/jenkins/pulls/285/config/modules.sh
❯ module load py-basalt/0.2.1/python3
Autoloading python/3.6.5
Autoloading cmake/3.13.0
```
All is well!

**Pull request merged**
