### PR TITLE
spykfunc: pin JDK, too.

### PR DESCRIPTION
**Pull request by matz-e**
Last bit to avoid rebuilding a lot of stuff in pull requests.

### CODE REVIEW

**Review by alexsavulescu — DISMISSED** [review]

**Review by alexsavulescu — DISMISSED** [review]

**Comment by matz-e** [comment]
Retest this please

**Comment by matz-e** [comment]
Retest this please

Our good old GPFS is "slow"

**Comment by matz-e** [comment]
Retest this please

**Comment by matz-e** [comment]
Retest this please

**Comment by matz-e** [comment]
Retest this please

**Review by alexsavulescu — APPROVED** [review]

**Comment by alexsavulescu** [comment]
sehr schone reparatur

**Comment by matz-e** [comment]
:D

**Pull request merged**
