### PR TITLE
deployment: comment if install specs are missing for modules.

### PR DESCRIPTION
**Pull request by matz-e**

### CODE REVIEW

**Comment by matz-e** [comment]
Please retest

**Comment by matz-e** [comment]
retest this please

**Comment by matz-e** [comment]
retest this please

**Comment by matz-e** [comment]
retest this please

**Comment by matz-e** [comment]
retest this please

**Comment by matz-e** [comment]
retest this please

**Comment by matz-e** [comment]
retest this please

**Comment by matz-e** [comment]
retest this please

**Comment by pramodk** [comment]
@matz-e : is this still relevant?

**Comment by matz-e** [comment]
Let's lay this to rest. May look into this again with GitLab CI.

**Pull request closed without merging**
