### PR TITLE
Update BGLibPy version to 4.2.14

### PR DESCRIPTION
**Pull request by anilbey**
There have been some changes in BGLibPy as well :)

### CODE REVIEW

**Comment by anilbey** [comment]
Ping @wvangeit

**Comment by pramodk** [comment]
@anilbey : LGTM. Could you take a quick look at [CI test failures](https://travis-ci.org/BlueBrain/spack/builds/654964549?utm_source=github_status&utm_medium=notification)? We have enabled some more checks and it would be easy to fix/improve package: 

```
>       assert not failing, msg.format(
1832            len(failing), ','.join(failing)
1833        )
1834E       AssertionError: there are 1 packages still using old APIs in this PR [py-bglibpy]
1835E       assert not ['py-bglibpy']
```

**Comment by wvangeit** [comment]
What is the new vs old API?

**Comment by matz-e** [comment]
> What is the new vs old API?

It's `setup_{dependent_,}environment` that has been replaced by `setup_{dependent_,}{run,build}_environment`.

E.g. https://spack.readthedocs.io/en/latest/spack.html#spack.package.PackageBase.setup_run_environment

**Comment by asanin-epfl** [comment]
@anilbey FYI there is #720. You can take changes from there. You would also need `py-pebble` and `py-scoope` packages changes.

**Comment by wvangeit** [comment]
Btw, @anilbey, I think we should remove the pinned version of BluePy

**Comment by anilbey** [comment]
@wvangeit  there are

https://github.com/BlueBrain/spack/blob/ceb461a16219546bf0c46034563511366e585e53/var/spack/repos/builtin/packages/py-bglibpy/package.py#L22

and

https://github.com/BlueBrain/spack/blob/ceb461a16219546bf0c46034563511366e585e53/deploy/packages/bbp-packages.yaml#L129

Should both be removed?

**Comment by wvangeit** [comment]
I'd leave the bbp-packages yaml up to the bluepy developers. But BGLibPy should not install an older version of bluepy.

**Review by matz-e — APPROVED** [review]

**Pull request merged**
