### PR TITLE
Add python packages required to use hpc-coding-conventions

### PR DESCRIPTION
**Pull request by tristan0x**
This pull-request provides Spack packages for `cmake-format` and `pre-commit`, along with all the missing dependent packages.

### CODE REVIEW

**Comment by matz-e** [comment]
Do you plan on auto-loading these via `python-dev`?

**Review by matz-e — APPROVED** [review]
LGTM

**Comment by tristan0x** [comment]
> Do you plan on auto-loading these via `python-dev`?

What is the rationale behind `python-dev`? Is this supposed to provide BB5 users a default python environment? If so, yes that would be cool to have `py-cmake-format` and `py-pre-commit` in this.

**Comment by matz-e** [comment]
> > Do you plan on auto-loading these via `python-dev`?
> 
> What is the rationale behind `python-dev`? Is this supposed to provide BB5 users a default python environment? If so, yes that would be cool to have `py-cmake-format` and `py-pre-commit` in this.

Yes, it's a package with commonly used python packages as dependencies to have a functional python.

**Review by pramodk — APPROVED** [review]

**Pull request merged**
