### PR TITLE
Update common submodule with changes related to vascouplingB

### PR DESCRIPTION
**Pull request by iomaganaris**

### CODE REVIEW

**Review by cattabiani — APPROVED** [review]
LGTM

**Review by matz-e — APPROVED** [review]

**Comment by iomaganaris** [comment]
@matz-e by merging this there going to be new modules deployed that use this new `common` version, right?

**Comment by matz-e** [comment]
@iomaganaris all modules listed above by the CI comment :)

**Comment by iomaganaris** [comment]
@matz-e the CI in the commit merged in `develop` has finished but I still see the old modules being deployed in BB5:
```
bash-4.2$ module show /gpfs/bbp.cscs.ch/ssd/apps/bsd/modules/2022-12/applications/linux-rhel7-skylake/neurodamus-neocortex-multiscale/1.10-2.12.10
-------------------------------------------------------------------
/gpfs/bbp.cscs.ch/ssd/apps/bsd/modules/2022-12/applications/linux-rhel7-skylake/neurodamus-neocortex-multiscale/1.10-2.12.10:

module-whatis    Neurodamus with built-in neocortex model
prepend-path     PATH /gpfs/bbp.cscs.ch/ssd/apps/bsd/2022-01-10/stage_applications/install_intel-2021.4.0-skylake/neurodamus-neocortex-1.10-2.12.10-nfj4p6/bin
...
bash-4.2$ ll /gpfs/bbp.cscs.ch/ssd/apps/bsd/modules/2022-12/applications/linux-rhel7-skylake/neurodamus-neocortex-multiscale/1.10-2.12.10
-rw-rw-r--+ 1 bbpcihpcdeploy bbp 6575 Dec 19 15:11 /gpfs/bbp.cscs.ch/ssd/apps/bsd/modules/2022-12/applications/linux-rhel7-skylake/neurodamus-neocortex-multiscale/1.10-2.12.10
bash-4.2$ ll /gpfs/bbp.cscs.ch/ssd/apps/bsd/2022-01-10/stage_applications/install_intel-2021.4.0-skylake/neurodamus-neocortex-1.10-2.12.10-nfj4p6/bin
total 552
-rwxr-xr-x+ 1 bbpcihpcdeploy bbp   4138 Dec 16 16:09 build_neurodamus.sh
-rwxr-xr-x+ 1 bbpcihpcdeploy bbp 552592 Dec 16 16:09 special
```
It seems like the module file got updated but its content was not

**Comment by matz-e** [comment]
Indeed, I overlooked that this is a resource, not a dependency! Maybe your base branch had some stuff that needed rebuilding, thus Spack built something in the PR, but not on the cluster.

I'm afraid we'll have to bump neurodamus-model, then.

**Pull request merged**
