### PR TITLE
Remove unset LC_ALL

### PR DESCRIPTION
**Pull request by jorblancoa**
- Removed the unset(LC_ALL) from neuron and reportinglib
- Enough to keep it on neurodamus-model

### CODE REVIEW

**Review by matz-e — APPROVED** [review]

**Review by pramodk — APPROVED** [review]

**Comment by ferdonline** [comment]
So... I stumbled upon this:
> setlocale changes the behaviour of sscanf (e.g. the way floats are decoded "." vs ",")

Well, in mod files we use extensively 'sprintf and sscanf'.

Other good reference: https://www.gnu.org/software/libc/manual/html_node/Effects-of-Locale.html

But... something is strange with mod files: 
```
A C program inherits its locale environment variables when it starts up. This happens automatically. 
However, these variables do not automatically control the locale used by the library functions, 
because ISO C says that all programs start by default in the standard `C' locale. 
To use the locales specified by the environment, you must call setlocale.
```

**Comment by ferdonline** [comment]
Disassembling the compiled sources we see that indeed all printf, sscanf incur slighly different binary, namely the instruction `LEAq` .e.g: `leaq	3189(%rip), %rsi` instead of `leaq	3187(%rip), %rsi`
Remarkably, the offset was always by 2 (3189 - 3187).
After some research, some good related documentation: [https://gcc.gnu.org/onlinedocs/gcc/Environment-Variables.html
](https://gcc.gnu.org/onlinedocs/gcc/Environment-Variables.html)
Important excerpts:
> The LC_CTYPE environment variable specifies character classification. GCC uses it to determine the character boundaries in a string; this is needed for some multibyte encodings that contain quote and escape characters that are otherwise interpreted as a string end or escape.

> If the LC_ALL environment variable is set, it overrides the value of LC_CTYPE and LC_MESSAGES; otherwise, LC_CTYPE and LC_MESSAGES default to the value of the LANG environment variable. If none of these variables are set, GCC defaults to traditional C English behavior.

So I guess this means that it is dangerous to set LC_ALL. Spack should instead define LC_MESSAGES.
For the moment we can override the LC_CTYPE back to the system one, otherwise string functions will probably handle UTF-8 thinking it is plain C. (where is the portability?)

Some interesting finding with @jorblancoa:
In neuron, locale LC_CTYPE setting is always overridden by the environment. This in principle shouldn't be the case per the documentation of setlocale.
```C
setlocale(LC_ALL, "");  // This should tell the system "dont use 'C' and use the env variables to set LC_*
setlocalestr = setlocale(LC_TIME, NULL);  // This is to retrieve a given setting. LC_ALL will retrieve 6 settings
printf("Current locale: %s\n", setlocalestr);
```

**Comment by matz-e** [comment]
@ferdonline I've experimented with setting `LC_MESSAGES` only, yet GCC did not, as per documentation, use that locale for it's output. Not sure what else in my environment I should have changed.

**Comment by ferdonline** [comment]
This is kind of crazy, but worth a look. Some people report errors and even crashes when the source code strings are interpreted in a different way.
For e.g., to control that GCC has few options:
-finput-charset: input character set, i.e. how the source code file is encoded
-fexec-charset: execution character set, i.e. how to encode string literals
-fwide-exec-charset: wide execution character set, i.e. how to encode wide string literals

I dont see, however, such options for icc.
So, there is a possibility we have a non-latin1 character in a data file which only gets well parsed if LC_ALL enables UTF-8. Not being well parsed, well, I guess it takes us to "undefined-behavior" land.

**Comment by ferdonline** [comment]
Latest findings by @jorblancoa is that order of mechanism registration matters.
In neuron when compiling mods using nrnivmodl is discovers them using `ls`. However `ls` respects system LC_ALL (we can even see in coreutils/src/ls.c +1458 `setlocale (LC_ALL, "");`) and results get different.
Coreneuron in turn uses gnu make $sort which is not bound to locale. Notoriously, most programs and scripting languages ignore LC_ALL, including Python. By default they use the equivalent of LC_ALL=c

@pramodk @jamesgking We have to decide whether to keep this odd behavior (and translate it to coreneuron), or to change nrnivmodl to do standard ordering which implies changing reference results.

**Comment by jorblancoa** [comment]
More discoveries!

Registration order of the mod files inside mod_func.c matters for the results of the simulations.
In case of Neuron, the order of the modules in this file is set by performing a 'ls' into the lib/modlib folder (https://github.com/neuronsimulator/nrn/blob/master/bin/nrnivmodl.in), and because 'ls' depends on the LC environment, it will generate different results depending if LC_ALL is not set or LC_ALL=C (actually LC_COLLIDE=C is enough to get different results).
When LC_ALL is not set, the results match, otherwise results are slightly different on (at least) the scx-1k-v5 simulation. 
You can see the numerical differences only by increasing the precision on the somaDump.

Then in case of CoreNeuron, the order of the modules is generated in the Makefile (https://github.com/BlueBrain/CoreNeuron/blob/master/extra/nrnivmodl_core_makefile.in) using the builtin gnu sort command. This will create always the same result no matter what the LC environment is (the same than 'ls' when LC_ALL=C), so the results will not match at least on the scx-1k-v5 simulation.

A possible solution would be to use in both cases LC_ALL="" ls 
This way the results will always be consistent with the base simulations. 
Other ideas are welcome!

**Comment by pramodk** [comment]
> @pramodk @jamesgking We have to decide whether to keep this odd behavior (and translate it to coreneuron), or to change nrnivmodl to do standard ordering which implies changing reference results.

Note that the order in coreneuron registration doesnt matter for simulation. CoreNEURON takes model from NEURON and continues execution as provided by NEURON.

So as long as we are consistent in NEURON / nrnivmodl, its fine.

As users would be building special from nrnivmodl (outside Spack context), I would be in favour of `LC_ALL=""` in neurodamus or nrnivmodl.

**Pull request merged**
