### PR TITLE
neurodamus-neocortex: bump to version 1.14

### PR DESCRIPTION
**Pull request by WeinaJi**

### CODE REVIEW

**Comment by WeinaJi** [comment]
@pramodk @matz-e , is it ok to deploy neocortex ? This is requested in  https://bbpteam.epfl.ch/project/issues/browse/BBPBGLIB-1123

**Comment by pramodk** [comment]
Fine to deploy but just mentioning: #2294 is also going to re-generate modules. I will let @matz-e comment on what he prefers (merge them together to avoid unnecessary #files?).

**Review by matz-e — APPROVED** [review]
Generating modules is fine. Changes should be kept separate, @pramodk

**Comment by pramodk** [comment]
Ok 👍 

(yes, I was just thinking of another unnecessary ~500 files on GPFS. Hence the commits could be merged in the same PR. But yeah, we don't have rebase-n-merge strategy enabled...)

**Pull request merged**
