### PR TITLE
added emacs as package and module

### PR DESCRIPTION
**Pull request by st4rl3ss**
build tentative, do not merge yet.

### CODE REVIEW

**Comment by matz-e** [comment]
ok to test

**Comment by st4rl3ss** [comment]
Is this REALLY all it's needed to add a new package and module to spack?

**Comment by matz-e** [comment]
Well, the package is already there, you just added it to the deployment.

BTW, what I talked about:
```
~ matwolf@bbpv2
❯ . /gpfs/bbp.cscs.ch/apps/hpc/jenkins/pulls/277/config/modules.sh

~ matwolf@bbpv2
❯ module av emacs

 /gpfs/bbp.cscs.ch/apps/hpc/jenkins/pulls/277/modules/tools/2019-03/tcl/linux-rhel7-x86_64
emacs/26.1
```

**Comment by matz-e** [comment]
`spack edit emacs` will actually open the recipe to compile emacs.

**Comment by st4rl3ss** [comment]
This solves #274

**Comment by pramodk** [comment]
@st4rl3ss : did you check if modules work correctly? (by loading it from PR build directory)

**Review by pramodk — APPROVED** [review]

**Comment by matz-e** [comment]
@pramodk I showed @st4rl3ss this yesterday. Emacs works for me, spacemacs loads.

**Comment by matz-e** [comment]
@st4rl3ss I think this is ready to "squash and merge". If you mention `Fixes #274` in the commit message, that issue should be closed automatically.

**Pull request merged**
