### PR TITLE
pyjwt version bump 2.0.1 hotfix

### PR DESCRIPTION
**Pull request by genric**

### CODE REVIEW

**Comment by genric** [comment]
Could you please trigger `unstable` redeploy once this is merged, thanks!

**Review by matz-e — APPROVED** [review]

**Comment by genric** [comment]
Any change of building `unstable` with this hotfix?

**Comment by matz-e** [comment]
Ah, sorry

**Comment by matz-e** [comment]
Finally! https://bbpcode.epfl.ch/ci/blue/organizations/jenkins/hpc.spack-deployment/detail/hpc.spack-deployment/3141/pipeline/ has completed, stuff should be available now!

**Comment by genric** [comment]
Great! Many thanks!

**Pull request merged**
