### PR TITLE
Bumped brainbuilder == 0.12.1

### PR DESCRIPTION
**Pull request by tomdele**
Releasing of brainbuilder 0.12.1

### CODE REVIEW

**Comment by asanin-epfl** [comment]
Good to go from my point of view. I would wait for @matz-e opinion.

**Review by matz-e — APPROVED** [review]
Looks fine to me

**Comment by tomdele** [comment]
Waiting for the tests and we should be good.
Thank you guys.

**Comment by tomdele** [comment]
Should I be worried by the failing coverage ?
 
https://codecov.io/gh/BlueBrain/spack/compare/9f17fe1c063d6af13969eff94bedcbd7b6695588...309f0975c61de876cbf2d4ada6cbc2a28c22f2e3

**Comment by matz-e** [comment]
> Should I be worried by the failing coverage ?
> 
> https://codecov.io/gh/BlueBrain/spack/compare/9f17fe1c063d6af13969eff94bedcbd7b6695588...309f0975c61de876cbf2d4ada6cbc2a28c22f2e3

For the record: the answer is *no*.

**Pull request merged**
