### PR TITLE
bump libsonata to v0.1.16

### PR DESCRIPTION
**Pull request by GianlucaFicarelli**

### CODE REVIEW

**Comment by GianlucaFicarelli** [comment]
FYI @WeinaJi @1uc

**Comment by 1uc** [comment]
Perfect, thank you.

**Review by matz-e — APPROVED** [review]

**Comment by WeinaJi** [comment]
Thanks. It fixes our pipeline tests.

**Review by matz-e — DISMISSED** [review]
I restarted the Spykfunc test, it's more a GPFS issue than anything

**Comment by cattabiani** [comment]
I am blocked by this PR. May we merge it soon?

**Comment by WeinaJi** [comment]
@matz-e , is the new tag of `spykfunc` ready to go ?

**Review by matz-e — APPROVED** [review]

**Pull request merged**
