### PR TITLE
bump placement-algorithm for synthesis

### PR DESCRIPTION
**Pull request by arnaudon**
v2.1.1 -> v2.1.2

### CODE REVIEW

**Review by matz-e — APPROVED** [review]

**Comment by arnaudon** [comment]
This is going to fail: https://bbpcode.epfl.ch/ci/job/nse.python.placement-algorithm/77/

**Comment by mgeplf** [comment]
Oh our Jenkins overlord, retest this please

**Comment by matz-e** [comment]
Next time, use the bowing emoji. I'm going to require that from now on. (also, every retrigger will have to sound more enthusiastic than the previous one…)

**Comment by mgeplf** [comment]
▄█▀█●

**Comment by arnaudon** [comment]
be careful with such emojis!

**Pull request merged**
