### PR TITLE
Add totalview v2022.1.11 to the deployment

### PR DESCRIPTION
**Pull request by pramodk**
I downloaded this version back in March 2022 itself but don't clearly remember if there were any issues while using this. So once this PR is built, @olupton can test the module and give a 💚 for merging!

### CODE REVIEW

**Comment by pramodk** [comment]
@matz-e :  It's true that the spack recipe uses :

>     resource(
>        name='x86_64',
>        url='file://{0}/totalview_2021.4.10_linux_x86-64.tar'.format(os.getcwd()),

and I see the following error in CI:

```console
1837==> Error: Manual download is required for totalview. Refer to https://www.roguewave.com/products-services/totalview for download instructions.
[1838](https://bbpgitlab.epfl.ch/hpc/spack/-/jobs/277907#L1838)==> Fetching file:///gpfs/bbp.cscs.ch/ssd/apps/bsd/pulls/1628/mirror/proprietary/totalview/totalview-2022.1.11.tar
```

I didn't look at the cause in detail but I believe previously the same pattern worked i.e. I was expecting `/gpfs/bbp.cscs.ch/apps/hpc/download/totalview/totalview-2022.1.11.tar` to be used via spack-mirror:

**Review by matz-e — DISMISSED** [review]
Cleaned PR directory and re-run, so proprietary mirroring setup works fine now.

**Comment by olupton** [comment]
I haven't tested 2022.1 yet, but I see there is now a 2022.2 that includes support for CUDA 11.6 and 11.7, so maybe we should jump straight to that?

**Comment by pramodk** [comment]
Updated and tested now with 2022.2.13

image

**Review by olupton — APPROVED** [review]
LGTM, I didn't test the module myself

**Pull request merged**
