### PR TITLE
Added dependencies to currentscape module.

### PR DESCRIPTION
**Pull request by AurelienJaquier**
I would like to add dependencies to the currentscape module.
The palettable package is accessible via pypi. Can I add it to the dependencies like this?

### CODE REVIEW

**Comment by matz-e** [comment]
> I would like to add dependencies to the currentscape module.
> The palettable package is accessible via pypi. Can I add it to the dependencies like this?

In principle yes, but the package name is slightly off. See this:
```
❯ spack list palettable
==> 1 packages.
py-palettable
```

**Review by matz-e — APPROVED** [review]
Seems legit.

**Comment by AurelienJaquier** [comment]
Thank you for your help, Matthias.
It looks like some tests are failing, I don't know why. Should I merge nonetheless?

**Comment by matz-e** [comment]
>  It looks like some tests are failing, I don't know why. Should I merge nonetheless?

Flake8 is passing, I think this is good to merge. Github actions are pulled in from upstream and only activated with the recent merge. I'm still sorting them out in a different PR

**Pull request merged**
