### PR TITLE
Adding packages needed by viz team to libraries.

### PR DESCRIPTION
**Pull request by ppodhajski**
- external: freeimage,libjpeg-turbo
  - serial: deflect, rockets

### CODE REVIEW

**Comment by matz-e** [comment]
OK to test

**Review by matz-e — APPROVED** [review]
LGTM

**Comment by pramodk** [comment]
@ppodhajski  : your account has been added. Next time you would be able  to trigger CI.

**Review by pramodk — APPROVED** [review]

**Comment by ppodhajski** [comment]
please merge

**Pull request merged**
